//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 6200.6.8.2.1
//
#ifndef HKAttributeConceptSelection_h
#define HKAttributeConceptSelection_h
@import Foundation;

#include "HKConceptSelection.h"

@interface HKAttributeConceptSelection : HKConceptSelection

@property (readonly, nonatomic) long long type;
@property (readonly, nonatomic) unsigned long long operatorType;
@property (readonly, copy, nonatomic) id <NSCopying, NSSecureCoding, NSObject> value;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (id)initWithAttribute:(long long)attribute operatorType:(unsigned long long)type value:(id)value;

@end

#endif /* HKAttributeConceptSelection_h */
