//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 6200.6.8.2.1
//
#ifndef HKFeatureAvailabilityRequirementOnboardingRecordIsNotPresent_h
#define HKFeatureAvailabilityRequirementOnboardingRecordIsNotPresent_h
@import Foundation;

#include "HKFeatureAvailabilityOnboardingRecordRequirement.h"
#include "HKFeatureAvailabilityRequirement-Protocol.h"

@interface HKFeatureAvailabilityRequirementOnboardingRecordIsNotPresent : HKFeatureAvailabilityOnboardingRecordRequirement <HKFeatureAvailabilityRequirement>

@property (readonly, nonatomic) NSString *requirementDescription;
@property (readonly, nonatomic) NSArray *requiredEntitlements;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)requirementIdentifier;

/* instance methods */
- (id)isSatisfiedWithOnboardingRecord:(id)record dataSource:(id)source error:(id *)error;

@end

#endif /* HKFeatureAvailabilityRequirementOnboardingRecordIsNotPresent_h */
