//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2226.120.19.0.0
//
#ifndef NEAppProxyProvider_h
#define NEAppProxyProvider_h
@import Foundation;

#include "NETunnelProvider.h"

@interface NEAppProxyProvider : NETunnelProvider

@property (nonatomic) unsigned long long maxWriteSize;

/* instance methods */
- (void)cancelProxyWithError:(id)error;
- (void)fetchFlowStatesWithCompletionHandler:(id /* block */)handler;
- (_Bool)handleNewFlow:(id)flow;
- (_Bool)handleNewUDPFlow:(id)udpflow initialRemoteEndpoint:(id)endpoint;
- (_Bool)handleNewUDPFlow:(id)udpflow initialRemoteFlowEndpoint:(id)endpoint;
- (void)startProxyWithOptions:(id)options completionHandler:(id /* block */)handler;
- (void)stopProxyWithReason:(long long)reason completionHandler:(id /* block */)handler;

@end

#endif /* NEAppProxyProvider_h */
