//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2511.35.2.9.9
//
#ifndef _MKMultiPartLabelCacheKey_h
#define _MKMultiPartLabelCacheKey_h
@import Foundation;

@interface _MKMultiPartLabelCacheKey : NSObject <NSCopying>

@property (readonly, copy, nonatomic) NSAttributedString *attributedString;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } size;

/* instance methods */
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (id)initWithAttributedString:(id)string size:(struct CGSize { double x0; double x1; })size;

@end

#endif /* _MKMultiPartLabelCacheKey_h */
