//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2511.35.2.9.9
//
#ifndef MKPlaceHeaderButton_h
#define MKPlaceHeaderButton_h
@import Foundation;

#include "MKVibrantView.h"
#include "_MKPlaceActionButtonController.h"
#include "_MKPlaceActionControlledButton-Protocol.h"

@class NSLayoutConstraint, UIButton;

@interface MKPlaceHeaderButton : UIButton <_MKPlaceActionControlledButton> {
    /* instance variables */
    unsigned long long _buttonType;
    _Bool _primary;
    NSLayoutConstraint *_heightConstraint;
    MKVibrantView *_vibrantView;
    _Bool _buttonHighlighted;
}

@property (weak, nonatomic) _MKPlaceActionButtonController *buttonController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })titleRectForContentRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)setHighlighted:(_Bool)highlighted;
- (id)init;
- (void)_contentSizeDidChange;
- (void)_setVibrantView;
- (void)applyButtonDefaultConfiguration;
- (void)buttonSelected:(id)selected;
- (_Bool)_isTintColorWhite;
- (id)_primaryButtonColor;
- (id)_primaryButtonTextColor;
- (void)_updateStyleNonPrimaryButton;
- (void)_updateStylePrimaryButton;
- (void)infoCardThemeChanged;
- (id)initWithPrimaryType:(unsigned long long)type;
- (void)placeActionButtonControllerTextDidChange:(id)change;
- (void)setPrimaryTitle:(id)title;
- (void)setPrimaryTitle:(id)title subtitle:(id)subtitle;
- (void)updateButtonWithHighlighted:(_Bool)highlighted;

@end

#endif /* MKPlaceHeaderButton_h */
