//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 147.0.0.0.0
//
#ifndef SYNotesActivationClient_h
#define SYNotesActivationClient_h
@import Foundation;

@protocol OS_dispatch_queue;

@interface SYNotesActivationClient : NSObject

@property (retain, nonatomic) NSXPCConnection *_connection;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *_clientQueue;

/* instance methods */
- (void)_setConnection:(id)connection;
- (id)init;
- (void)_ensureConnection;
- (void)_clientQueue:(id)queue;
- (void)activateNotesWithUserActivity:(id)activity completion:(id /* block */)completion;

@end

#endif /* SYNotesActivationClient_h */
