//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3031.122.1.0.0
//
#ifndef PPSProcessMetricCollection_h
#define PPSProcessMetricCollection_h
@import Foundation;

#include "PPSMetricSample.h"

@interface PPSProcessMetricCollection : NSObject <NSSecureCoding, NSCopying>

@property (retain, nonatomic) PPSMetricSample *energyCost;
@property (retain, nonatomic) PPSMetricSample *energyOverhead;
@property (retain, nonatomic) PPSMetricSample *cpuCost;
@property (retain, nonatomic) PPSMetricSample *cpuSeconds;
@property (retain, nonatomic) PPSMetricSample *cpuSecondsWithoutVouchers;
@property (retain, nonatomic) PPSMetricSample *cpuSecondsWithVouchers;
@property (retain, nonatomic) PPSMetricSample *cpuEnergy;
@property (retain, nonatomic) PPSMetricSample *cpuEnergyWithoutVouchers;
@property (retain, nonatomic) PPSMetricSample *cpuEnergyWithVouchers;
@property (retain, nonatomic) PPSMetricSample *gpuCost;
@property (retain, nonatomic) PPSMetricSample *gpuTime;
@property (retain, nonatomic) PPSMetricSample *gpuEnergy;
@property (retain, nonatomic) PPSMetricSample *gpuEnergyWithoutVouchers;
@property (retain, nonatomic) PPSMetricSample *gpuEnergyWithVouchers;
@property (retain, nonatomic) PPSMetricSample *networkCost;
@property (retain, nonatomic) PPSMetricSample *networkingPower;
@property (retain, nonatomic) PPSMetricSample *wifiIn;
@property (retain, nonatomic) PPSMetricSample *wifiOut;
@property (retain, nonatomic) PPSMetricSample *cellIn;
@property (retain, nonatomic) PPSMetricSample *cellOut;
@property (retain, nonatomic) PPSMetricSample *locationCost;
@property (retain, nonatomic) PPSMetricSample *ongoingLocation;
@property (retain, nonatomic) PPSMetricSample *applicationState;
@property (retain, nonatomic) PPSMetricSample *cpuInstructions;
@property (retain, nonatomic) PPSMetricSample *cpuPInstructions;
@property (retain, nonatomic) PPSMetricSample *bytesRead;
@property (retain, nonatomic) PPSMetricSample *bytesWritten;
@property (retain, nonatomic) PPSMetricSample *aneEnergy;
@property (retain, nonatomic) PPSMetricSample *aneTime;
@property (retain, nonatomic) PPSMetricSample *qosUtility;
@property (retain, nonatomic) PPSMetricSample *qosBackground;
@property (retain, nonatomic) PPSMetricSample *qosUserInitiated;
@property (retain, nonatomic) PPSMetricSample *qosUserInteractive;
@property (retain, nonatomic) PPSMetricSample *qosDefault;
@property (retain, nonatomic) PPSMetricSample *qosMaintenance;
@property (retain, nonatomic) PPSMetricSample *qosUnspecified;
@property (retain, nonatomic) PPSMetricSample *locationDesiredAccuracy;
@property (retain, nonatomic) PPSMetricSample *displayPower;
@property (retain, nonatomic) PPSMetricSample *weightOnScreen;
@property (nonatomic) int pid;
@property (retain, nonatomic) NSNumber *coalitionID;
@property (retain, nonatomic) NSString *processName;
@property (retain, nonatomic) NSString *bundleID;
@property (retain, nonatomic) NSNumber *sampleTime;
@property (nonatomic) _Bool audioActive;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)_metricSamplePropertyKeys;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)clearMetrics;
- (void)encodeWithCoder:(id)coder;
- (id)description;
- (const char *)_stringForApplicationState:(unsigned int)state;
- (void)combineWithProcessMetricCollection:(id)collection;

@end

#endif /* PPSProcessMetricCollection_h */
