//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4479.122.1.0.0
//
#ifndef BRAccountDescriptor_h
#define BRAccountDescriptor_h
@import Foundation;

@interface BRAccountDescriptor : NSObject <NSSecureCoding> {
    /* instance variables */
    NSString *_personaIdentifier;
}

@property (readonly, nonatomic) NSString *accountIdentifier;
@property (readonly, nonatomic) NSString *domainIdentifier;
@property (readonly, nonatomic) _Bool isLoggedInToCloudDocs;
@property (readonly, nonatomic) _Bool isDataSeparated;
@property (readonly, nonatomic) NSString *organizationName;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (_Bool)mightHaveDataSeparatedAccountDescriptor;
+ (void)refreshCache:(_Bool)cache;
+ (id)accountDescriptorForURL:(id)url;
+ (id)accountDescriptorForAccountID:(id)id mustBeLoggedIn:(_Bool)in;
+ (id)accountDescriptorForPersonaID:(id)id mustBeLoggedIn:(_Bool)in;
+ (void)clearAccountDescriptorCache;
+ (id)allEligibleAccountDescriptors;
+ (id)accountDescriptorForPersonaID:(id)id;
+ (id)accountDescriptorForAccountID:(id)id;
+ (id)matchDomainWithAccountAndStampDomainIfNeeded:(id)needed withAccounts:(id)accounts persistDomain:(_Bool *)domain error:(id *)error;
+ (id)accountDescriptorForURL:(id)url mustBeLoggedIn:(_Bool)in;
+ (id)allLoggedInAccountDescriptors;

/* instance methods */
- (id)personaIdentifier;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)description;
- (id)initWithPersonaIdentifier:(id)identifier accountIdentifier:(id)identifier domainIdentifier:(id)identifier organizationName:(id)name dataSeparated:(_Bool)separated loggedInToCloudDocs:(_Bool)docs;

@end

#endif /* BRAccountDescriptor_h */
