//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4479.122.1.0.0
//
#ifndef BRUploadAllFilesOperation_h
#define BRUploadAllFilesOperation_h
@import Foundation;

#include "BRContainer.h"
#include "BROperation.h"

@interface BRUploadAllFilesOperation : BROperation {
    /* instance variables */
    BRContainer *_container;
}

@property (copy) id /* block */ uploadAllFilesCompletion;

/* instance methods */
- (void)main;
- (id)initWithContainer:(id)container;
- (id)init;
- (void)finishWithResult:(id)result error:(id)error;

@end

#endif /* BRUploadAllFilesOperation_h */
