//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3532.5.3.100.0
//
#ifndef TISKEvent_h
#define TISKEvent_h
@import Foundation;

#include "TISKEventProtocol-Protocol.h"
#include "TISKTap.h"

@interface TISKEvent : NSObject <TISKEventProtocol>

@property (nonatomic) int type;
@property (retain, nonatomic) TISKTap *tap;
@property (nonatomic) _Bool emojiSearchMode;
@property (nonatomic) unsigned long long order;
@property (nonatomic) _Bool hasTimestamp;

/* instance methods */
- (id)privateDescription;
- (id)description;
- (double)touchDownTimestamp;
- (id)init:(int)init emojiSearchMode:(_Bool)mode order:(long long)order tap:(id)tap;
- (_Bool)isMissingATouch;
- (id)downTouchEvent;
- (id)init:(int)init emojiSearchMode:(_Bool)mode order:(long long)order;
- (_Bool)isValidCandidate:(id)candidate;
- (void)reportInterKeyTiming:(id)timing previousEvent:(id)event;
- (void)reportToSession:(id)session;
- (double)touchUpTimestamp;
- (id)upTouchEvent;

@end

#endif /* TISKEvent_h */
