//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 5883.0.0.0.0
//
#ifndef SXAnalyticsReportingContainer_h
#define SXAnalyticsReportingContainer_h
@import Foundation;

#include "SXAnalyticsReporting-Protocol.h"
#include "SXAnalyticsReportingContainer-Protocol.h"

@interface SXAnalyticsReportingContainer : NSObject <SXAnalyticsReportingContainer>

@property (readonly, nonatomic) id <SXAnalyticsReporting> analyticsReporting;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)registerAnalyticsReporting:(id)reporting;

@end

#endif /* SXAnalyticsReportingContainer_h */
