//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 304.5.4.102.0
//
#ifndef PBFDataStoreArchiveMetadata_h
#define PBFDataStoreArchiveMetadata_h
@import Foundation;

@interface PBFDataStoreArchiveMetadata : NSObject

@property (readonly, nonatomic) unsigned long long version;
@property (readonly, nonatomic) NSString *archiveName;
@property (readonly, nonatomic) NSURL *archiveURL;
@property (readonly, nonatomic) NSDate *creationDate;

/* instance methods */
- (id)initWithURL:(id)url;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;

@end

#endif /* PBFDataStoreArchiveMetadata_h */
