//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2288.0.0.0.0
//
#ifndef BUTemporaryDirectory_h
#define BUTemporaryDirectory_h
@import Foundation;

@interface BUTemporaryDirectory : NSObject {
    /* instance variables */
    NSString *_path;
    _Bool _leak;
}

/* instance methods */
- (id)initWithError:(id *)error;
- (id)URL;
- (void)dealloc;
- (id)path;
- (id)init;
- (_Bool)_createDirectoryWithSignature:(id)signature subdirectory:(id)subdirectory error:(id *)error;
- (id)initForWritingToURL:(id)url error:(id *)error;
- (id)initWithSignature:(id)signature error:(id *)error;
- (id)initWithSignature:(id)signature subdirectory:(id)subdirectory error:(id *)error;
- (void)leakTemporaryDirectory;

@end

#endif /* BUTemporaryDirectory_h */
