//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 70.0.0.0.0
//
#ifndef _TtC33iCloudSubscriptionOptimizerDaemon16PFLDataCollector_h
#define _TtC33iCloudSubscriptionOptimizerDaemon16PFLDataCollector_h
@import Foundation;

@class Swift.Bool, Swift.Int64, _$sSa -> iCloudSubscriptionOptimizerCore.SubscriptiondPFLMessage, _$sSa -> iCloudSubscriptionOptimizerDaemon.BiomeICloudSubscription, _$sSa -> iCloudSubscriptionOptimizerDaemon.LabeledNotification, _TtCs12_SwiftObject, iCloudSubscriptionOptimizerDaemon.BiomeManager;

@interface _TtC33iCloudSubscriptionOptimizerDaemon16PFLDataCollector : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSa -> iCloudSubscriptionOptimizerCore.SubscriptiondPFLMessage pflMessages;
    iCloudSubscriptionOptimizerDaemon.BiomeManager biomeManager;
    Swift.Int64 numOffsets;
    _$sSa -> iCloudSubscriptionOptimizerDaemon.LabeledNotification notificationsFromNotifStream;
    _$sSa -> iCloudSubscriptionOptimizerDaemon.BiomeICloudSubscription notificationsFromSubStream;
    Swift.Bool dummyPflData;
}

@end

#endif /* _TtC33iCloudSubscriptionOptimizerDaemon16PFLDataCollector_h */
