//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef ALAssetRepresentationPrivate_h
#define ALAssetRepresentationPrivate_h
@import Foundation;

#include "ALAssetsLibrary.h"
#include "ALAssetsLibraryAsset-Protocol.h"

@class PLManagedAsset, PLPhotoLibrary;
@protocol PLSidecar;

@interface ALAssetRepresentationPrivate : NSObject <ALAssetsLibraryAsset> {
    /* instance variables */
    PLPhotoLibrary *_photoLibrary;
}

@property (retain, nonatomic) PLManagedAsset *photo;
@property (retain, nonatomic) PLPhotoLibrary *_photoLibrary;
@property (retain, nonatomic) id <PLSidecar> sidecar;
@property (copy, nonatomic) NSString *extension;
@property (nonatomic) ALAssetsLibrary *library;
@property (nonatomic) _Bool isValid;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)_clearFileDescriptorQueue;
+ (int)_fileDescriptorForPersistentURL:(id)url;
+ (void)_setupFileDescriptorQueue;
+ (int)_updateFileDescriptor:(int)descriptor forPersistentURL:(id)url;

/* instance methods */
- (void)dealloc;
- (void)libraryDidChange;
- (_Bool)_isImage;
- (_Bool)_isVideo;
- (void)_performBlockAndWait:(id /* block */)wait;
- (id)initWithManagedAsset:(id)asset sidecar:(id)sidecar extension:(id)extension library:(id)library;

@end

#endif /* ALAssetRepresentationPrivate_h */
