//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 48.501.0.0.0
//
#ifndef CADSPSubset_h
#define CADSPSubset_h
@import Foundation;

#include "CADSPSubsetModel.h"

@interface CADSPSubset : NSObject {
    /* instance variables */
    struct shared_ptr<AudioDSPGraph::Subset> { struct Subset *__ptr_; struct __shared_weak_count *__cntrl_; } _this;
}

@property (readonly, nonatomic) CADSPSubsetModel *model;
@property (readonly, copy, nonatomic) NSArray *boxes;

/* instance methods */
- (id)initWithSubset:(struct shared_ptr<AudioDSPGraph::Subset> { struct Subset *x0; struct __shared_weak_count *x1; })subset model:(id)model boxes:(id)boxes;
- (_Bool)loadStrip:(id)strip type:(unsigned int)type error:(id *)error;
- (_Bool)loadStrip:(id)strip type:(unsigned int)type withResourcePath:(id)path error:(id *)error;
- (id)saveStrip:(unsigned int)strip error:(id *)error;

@end

#endif /* CADSPSubset_h */
