//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2422.120.23.0.9
//
#ifndef SUCoreBiomeEventPayloadBase_h
#define SUCoreBiomeEventPayloadBase_h
@import Foundation;

@interface SUCoreBiomeEventPayloadBase : NSObject

@end

#endif /* SUCoreBiomeEventPayloadBase_h */
