//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1642.6.5.0.0
//
#ifndef PKTextureLoadDescriptor_h
#define PKTextureLoadDescriptor_h
@import Foundation;

@protocol MTLDevice;

@interface PKTextureLoadDescriptor : NSObject {
    /* instance variables */
    unsigned long long _storageMode;
}

@property (readonly, nonatomic) id <MTLDevice> device;
@property (nonatomic) _Bool premultiplyAlpha;
@property (readonly, nonatomic) struct CGColorSpace * colorSpace;
@property (readonly, nonatomic) int renderingIntent;

/* instance methods */
- (void)dealloc;
- (id)init;
- (id)initForDevice:(id)device;
- (id)createLoaderForCGImage:(struct CGImage *)cgimage;
- (void)setColorSpace:(struct CGColorSpace *)space renderingIntent:(int)intent;

@end

#endif /* PKTextureLoadDescriptor_h */
