//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 7019.0.0.0.0
//
#ifndef AWDPushConnectionConnected_h
#define AWDPushConnectionConnected_h
@import Foundation;

@class PBCodable;

@interface AWDPushConnectionConnected : PBCodable <NSCopying> {
    /* instance variables */
    struct { unsigned int timestamp:1; unsigned int connectDuration:1; unsigned int connectionType:1; unsigned int dnsDuration:1; unsigned int dualChannelState:1; unsigned int linkQuality:1; unsigned int tlsDuration:1; } _has;
}

@property (readonly, nonatomic) _Bool hasGuid;
@property (retain, nonatomic) NSString *guid;
@property (nonatomic) _Bool hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) _Bool hasConnectDuration;
@property (nonatomic) unsigned int connectDuration;
@property (nonatomic) _Bool hasConnectionType;
@property (nonatomic) unsigned int connectionType;
@property (nonatomic) _Bool hasLinkQuality;
@property (nonatomic) int linkQuality;
@property (nonatomic) _Bool hasDualChannelState;
@property (nonatomic) unsigned int dualChannelState;
@property (nonatomic) _Bool hasDnsDuration;
@property (nonatomic) unsigned int dnsDuration;
@property (nonatomic) _Bool hasTlsDuration;
@property (nonatomic) unsigned int tlsDuration;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (void)copyTo:(id)to;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)dealloc;
- (void)writeTo:(id)to;
- (id)dictionaryRepresentation;
- (id)description;
- (_Bool)isEqual:(id)equal;

@end

#endif /* AWDPushConnectionConnected_h */
