//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 359.6.1.0.0
//
#ifndef HMIVideoAnalyzerDynamicConfiguration_h
#define HMIVideoAnalyzerDynamicConfiguration_h
@import Foundation;

#include "HMFLogging-Protocol.h"

@class HMFObject;

@interface HMIVideoAnalyzerDynamicConfiguration : HMFObject <HMFLogging, NSSecureCoding>

@property long long decodeMode;
@property _Bool shouldEncode;
@property struct { long long x0; int x1; unsigned int x2; long long x3; } timelapseInterval;
@property _Bool recognizeFaces;
@property long long eventTriggers;
@property (retain) NSArray *activityZones;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)logCategory;

/* instance methods */
- (id)attributeDescriptions;
- (id)initWithCoder:(id)coder;
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;

@end

#endif /* HMIVideoAnalyzerDynamicConfiguration_h */
