//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.1.0.0
//
#ifndef DODMLASRSchemaDODMLASRDecodingResult_h
#define DODMLASRSchemaDODMLASRDecodingResult_h
@import Foundation;

#include "DODMLASRSchemaDODMLASRDecodingMetrics.h"
#include "SISchemaInstrumentationMessage.h"

@interface DODMLASRSchemaDODMLASRDecodingResult : SISchemaInstrumentationMessage {
    /* instance variables */
    struct { unsigned int decodeDurationInNs:1; unsigned int oneBestTranscriptLinkIndex:1; } _has;
}

@property (copy, nonatomic) NSString *configName;
@property (nonatomic) _Bool hasConfigName;
@property (copy, nonatomic) NSArray *tokens;
@property (copy, nonatomic) NSArray *utterances;
@property (retain, nonatomic) DODMLASRSchemaDODMLASRDecodingMetrics *decodingMetrics;
@property (nonatomic) _Bool hasDecodingMetrics;
@property (nonatomic) unsigned long long decodeDurationInNs;
@property (nonatomic) _Bool hasDecodeDurationInNs;
@property (copy, nonatomic) NSArray *alignments;
@property (copy, nonatomic) NSArray *entityScoreResults;
@property (nonatomic) unsigned int oneBestTranscriptLinkIndex;
@property (nonatomic) _Bool hasOneBestTranscriptLinkIndex;
@property (readonly, nonatomic) NSData *jsonData;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (unsigned long long)hash;
- (id)applySensitiveConditionsPolicy:(id)policy;
- (void)writeTo:(id)to;
- (id)initWithJSON:(id)json;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:(id)dictionary;
- (id)dictionaryRepresentation;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)alignmentsCount;
- (void)clearUtterances;
- (unsigned long long)utterancesCount;
- (void)clearAlignments;
- (void)addAlignments:(id)alignments;
- (void)addEntityScoreResults:(id)results;
- (void)addTokens:(id)tokens;
- (void)addUtterances:(id)utterances;
- (id)alignmentsAtIndex:(unsigned long long)index;
- (void)clearEntityScoreResults;
- (void)clearTokens;
- (void)deleteAlignments;
- (void)deleteConfigName;
- (void)deleteDecodeDurationInNs;
- (void)deleteDecodingMetrics;
- (void)deleteEntityScoreResults;
- (void)deleteOneBestTranscriptLinkIndex;
- (void)deleteTokens;
- (void)deleteUtterances;
- (id)entityScoreResultsAtIndex:(unsigned long long)index;
- (unsigned long long)entityScoreResultsCount;
- (id)tokensAtIndex:(unsigned long long)index;
- (unsigned long long)tokensCount;
- (id)utterancesAtIndex:(unsigned long long)index;

@end

#endif /* DODMLASRSchemaDODMLASRDecodingResult_h */
