//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.1.0.0
//
#ifndef NLXSchemaSSUBackgroundUpdateAppInfo_h
#define NLXSchemaSSUBackgroundUpdateAppInfo_h
@import Foundation;

#include "SISchemaInstrumentationMessage.h"

@interface NLXSchemaSSUBackgroundUpdateAppInfo : SISchemaInstrumentationMessage {
    /* instance variables */
    struct { unsigned int numCacheFilesRemoved:1; } _has;
}

@property (copy, nonatomic) NSString *appBundleIdSaltedHash;
@property (nonatomic) _Bool hasAppBundleIdSaltedHash;
@property (nonatomic) unsigned int numCacheFilesRemoved;
@property (nonatomic) _Bool hasNumCacheFilesRemoved;
@property (copy, nonatomic) NSArray *categoryInfos;
@property (readonly, nonatomic) NSData *jsonData;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (unsigned long long)hash;
- (id)applySensitiveConditionsPolicy:(id)policy;
- (void)writeTo:(id)to;
- (id)initWithJSON:(id)json;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:(id)dictionary;
- (id)dictionaryRepresentation;
- (_Bool)isEqual:(id)equal;
- (void)addCategoryInfos:(id)infos;
- (id)categoryInfosAtIndex:(unsigned long long)index;
- (unsigned long long)categoryInfosCount;
- (void)clearCategoryInfos;
- (void)deleteAppBundleIdSaltedHash;
- (void)deleteCategoryInfos;
- (void)deleteNumCacheFilesRemoved;

@end

#endif /* NLXSchemaSSUBackgroundUpdateAppInfo_h */
