//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 251.35.2.9.11
//
#ifndef MUPlaceHeaderButtonsSectionControllerDelegate_Protocol_h
#define MUPlaceHeaderButtonsSectionControllerDelegate_Protocol_h
@import Foundation;

@protocol MUPlaceHeaderButtonsSectionControllerDelegate <NSObject>

@required

/* required instance methods */
- (void)placeHeaderButtonsSectionController:(id)controller didSelectPrimaryType:(unsigned long long)type withPresentationOptions:(id)options;

@optional

@end

#endif /* MUPlaceHeaderButtonsSectionControllerDelegate_Protocol_h */
