//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 524.0.7.0.0
//
#ifndef PRDevicePoseValidator_h
#define PRDevicePoseValidator_h
@import Foundation;

#include "PRPose.h"

@protocol OS_os_log;

@interface PRDevicePoseValidator : NSObject {
    /* instance variables */
    NSObject<OS_os_log> *_logger;
}

@property (nonatomic) double maximumSpeed;
@property (retain, nonatomic) PRPose *previousPose;

/* instance methods */
- (id)initWithMaximumSpeed:(double)speed;
- (_Bool)validatePose:(id)pose;

@end

#endif /* PRDevicePoseValidator_h */
