//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 130.4.1.0.0
//
#ifndef _TtCC24SensitiveContentAnalysis23_AnalysisHistoryXPCHost14SessionHandler_h
#define _TtCC24SensitiveContentAnalysis23_AnalysisHistoryXPCHost14SessionHandler_h
@import Foundation;

@class Foundation.UUID, SensitiveContentAnalysis.MessageHandlers, SensitiveContentAnalysis._AnalysisHistoryXPCHost ?, Swift.Int32 ?, XPC.XPCSession, _$sSo16RBSProcessHandleCSg, _TtCs12_SwiftObject;

@interface _TtCC24SensitiveContentAnalysis23_AnalysisHistoryXPCHost14SessionHandler : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    XPC.XPCSession session;
    Foundation.UUID uuid;
    SensitiveContentAnalysis.MessageHandlers handlers;
    SensitiveContentAnalysis._AnalysisHistoryXPCHost ? host;
    Swift.Int32 ? pid;
    _$sSo16RBSProcessHandleCSg processHandle;
}

@end

#endif /* _TtCC24SensitiveContentAnalysis23_AnalysisHistoryXPCHost14SessionHandler_h */
