//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1202.5.1.0.0
//
#ifndef SUUIProductPageTableLockupsSection_h
#define SUUIProductPageTableLockupsSection_h
@import Foundation;

#include "SUUIArtworkRequestDelegate-Protocol.h"
#include "SUUIMissingItemDelegate-Protocol.h"
#include "SUUIMissingItemLoader.h"
#include "SUUIProductPageTableHeaderView.h"
#include "SUUIProductPageTableSection.h"
#include "SUUIProductPageTableSeparatorView.h"
#include "SUUIResourceLoader.h"
#include "SUUIStyledImageDataConsumer.h"

@class UIImage;

@interface SUUIProductPageTableLockupsSection : SUUIProductPageTableSection <SUUIArtworkRequestDelegate, SUUIMissingItemDelegate> {
    /* instance variables */
    NSMapTable *_artworkRequests;
    SUUIProductPageTableSeparatorView *_footerView;
    SUUIProductPageTableHeaderView *_headerView;
    NSArray *_lockups;
    SUUIMissingItemLoader *_missingItemLoader;
    UIImage *_placeholderImage;
    SUUIStyledImageDataConsumer *_productImageDataConsumer;
}

@property (retain, nonatomic) SUUIResourceLoader *resourceLoader;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (long long)numberOfRowsInSection;
- (id)_missingItemLoader;
- (id)_productImageForItem:(id)item;
- (void)artworkRequest:(id)request didLoadImage:(id)image;
- (id)footerViewForTableView:(id)view;
- (id)headerViewForTableView:(id)view;
- (double)heightForCellInTableView:(id)view indexPath:(id)path;
- (id)initWithLockups:(id)lockups title:(id)title;
- (void)missingItemLoader:(id)loader didLoadItems:(id)items invalidItemIdentifiers:(id)identifiers;
- (id)selectionActionForTableView:(id)view indexPath:(id)path;
- (id)tableViewCellForTableView:(id)view indexPath:(id)path;

@end

#endif /* SUUIProductPageTableLockupsSection_h */
