//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef PXSharedLibraryPhotoKitDataSourceManager_h
#define PXSharedLibraryPhotoKitDataSourceManager_h
@import Foundation;

#include "PXPhotoLibraryUIChangeObserver-Protocol.h"
#include "PXSharedLibraryDataSourceManager.h"

@class PHFetchResult, PHPhotoLibrary;

@interface PXSharedLibraryPhotoKitDataSourceManager : PXSharedLibraryDataSourceManager <PXPhotoLibraryUIChangeObserver> {
    /* instance variables */
    long long _type;
    PHFetchResult *_fetchResult;
    PHPhotoLibrary *_photoLibrary;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedLibraryDataSourceManagerForPhotoLibrary:(id)library;
+ (id)previewDataSourceManagerForPhotoLibrary:(id)library;
+ (id)invitationsDataSourceManagerForPhotoLibrary:(id)library;
+ (id)exitingDataSourceManagerForPhotoLibrary:(id)library;

/* instance methods */
- (id)createInitialDataSource;
- (id)fetchSharedLibrary;
- (void)photoLibraryDidChangeOnMainQueue:(id)queue withPreparedInfo:(id)info;
- (id)prepareForPhotoLibraryChange:(id)change;
- (void)fetchSharedLibraryForURL:(id)url completionHandler:(id /* block */)handler;
- (id)fetchExiting;
- (id)initWithType:(long long)type fetchResult:(id)result;
- (id)init;
- (id)fetchPreview;

@end

#endif /* PXSharedLibraryPhotoKitDataSourceManager_h */
