//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef PXStoryCompanionTimelineRequestConfiguration_h
#define PXStoryCompanionTimelineRequestConfiguration_h
@import Foundation;

@class PHAssetCollection;
@protocol OS_dispatch_queue;

@interface PXStoryCompanionTimelineRequestConfiguration : NSObject <NSCopying>

@property (nonatomic) long long songsProducerKind;
@property (retain, nonatomic) PHAssetCollection *assetCollection;
@property (nonatomic) struct CGSize { double x0; double x1; } viewportSize;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (id)initWithAssetCollection:(id)collection viewportSize:(struct CGSize { double x0; double x1; })size;

@end

#endif /* PXStoryCompanionTimelineRequestConfiguration_h */
