//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef _UIDatePickerMode_TimeInterval_h
#define _UIDatePickerMode_TimeInterval_h
@import Foundation;

#include "_UIDatePickerMode.h"

@interface _UIDatePickerMode_TimeInterval : _UIDatePickerMode {
    /* instance variables */
    double _componentWidth;
}

/* class methods */
+ (long long)datePickerMode;
+ (unsigned long long)extractableCalendarUnits;

/* instance methods */
- (double)rowHeight;
- (id)font;
- (_Bool)_shouldEnableValueForRow:(long long)row inComponent:(long long)component calendarUnit:(unsigned long long)unit;
- (_Bool)areValidDateComponents:(id)components comparingUnits:(long long)units;
- (id)dateComponentsByRestrictingSelectedComponents:(id)components withLastManipulatedColumn:(long long)column;
- (long long)hourForRow:(long long)row;
- (_Bool)isTimeIntervalMode;
- (id)localizedFormatString;
- (unsigned long long)nextUnitLargerThanUnit:(unsigned long long)unit;
- (unsigned long long)nextUnitSmallerThanUnit:(unsigned long long)unit;
- (long long)numberOfRowsForCalendarUnit:(unsigned long long)unit;
- (struct _NSRange { unsigned long long x0; unsigned long long x1; })rangeForCalendarUnit:(unsigned long long)unit;
- (void)resetComponentWidths;
- (id)titleForRow:(long long)row inComponent:(long long)component;
- (void)updateDateForNewDateRange;
- (long long)valueForDate:(id)date dateComponents:(id)components calendarUnit:(unsigned long long)unit;
- (double)widthForCalendarUnit:(unsigned long long)unit font:(id)font maxWidth:(double)width;

@end

#endif /* _UIDatePickerMode_TimeInterval_h */
