//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef _UIShadowProperties_h
#define _UIShadowProperties_h
@import Foundation;

#include "UIColor.h"

@interface _UIShadowProperties : NSObject <NSCopying>

@property (nonatomic) double opacity;
@property (retain, nonatomic) UIColor *color;
@property (nonatomic) struct CGSize { double x0; double x1; } offset;
@property (nonatomic) double radius;

/* class methods */
+ (id)propertiesFromView:(id)view;

/* instance methods */
- (void)scaleBy:(double)by;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (void)applyToView:(id)view;
- (id)updatedShadowWithIntensity:(double)intensity;

@end

#endif /* _UIShadowProperties_h */
