//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef _UITextViewAnimatedPlaceholderSupport_h
#define _UITextViewAnimatedPlaceholderSupport_h
@import Foundation;

#include "UITextView.h"
#include "_TtC5UIKit21UITextEffectTextChunk.h"
#include "_TtP5UIKit22UITextEffectViewSource_-Protocol.h"

@interface _UITextViewAnimatedPlaceholderSupport : NSObject <_TtP5UIKit22UITextEffectViewSource_> {
    /* instance variables */
     $__lazy_storage_$_containerView;
     $__lazy_storage_$_textEffectsView;
     completionBlocks;
     activeReplacementEffect;
     activePlaceholders;
}

@property (nonatomic, weak) UITextView *textView;

/* instance methods */
- (id)init;
- (id)initWithTextView:(id)view;
- (void)canGenerateTargetedPreviewForChunk:(_TtC5UIKit21UITextEffectTextChunk *)chunk completionHandler:(id /* block */)handler;
- (void)canGenerateTargetedPreviewsWithCompletionHandler:(id /* block */)handler;
- (void)insertAttributedTextUsingReplacementEffect:(id)effect completion:(id /* block */)completion;
- (id)insertLoadingPlaceholderAtLocation:(id)location lines:(double)lines completion:(id /* block */)completion;
- (void)layoutManagedSubviews;
- (void)removePlaceholder:(id)placeholder;
- (void)replacePlaceholder:(id)placeholder withText:(id)text completion:(id /* block */)completion;
- (void)replaceRangeUsingReplacementEffect:(id)effect withAttributedText:(id)text completion:(id /* block */)completion;
- (void)targetedPreviewFor:(_TtC5UIKit21UITextEffectTextChunk *)_for completionHandler:(id /* block */)handler;
- (void)updateTextChunkVisibilityForAnimation:(_TtC5UIKit21UITextEffectTextChunk *)animation visible:(_Bool)visible completionHandler:(id /* block */)handler;

@end

#endif /* _UITextViewAnimatedPlaceholderSupport_h */
