//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef UIBackgroundConfiguration_h
#define UIBackgroundConfiguration_h
@import Foundation;

#include "UIColor.h"
#include "UIImage.h"
#include "UIShadowProperties.h"
#include "UIView.h"
#include "UIVisualEffect.h"
#include "_UIBackgroundConfigurationInternal-Protocol.h"
#include "_UIViewMaterial-Protocol.h"

@interface UIBackgroundConfiguration : NSObject <_UIBackgroundConfigurationInternal, NSCopying, NSSecureCoding> {
    /* instance variables */
    struct { unsigned int hasCustomizedCustomView:1; unsigned int hasCustomizedCornerRadius:1; unsigned int hasCustomizedBackgroundInsets:1; unsigned int hasCustomizedEdgesAddingLayoutMarginsToBackgroundInsets:1; unsigned int hasCustomizedBackgroundColor:1; unsigned int hasCustomizedBackgroundColorTransformer:1; unsigned int hasCustomizedVisualEffect:1; unsigned int hasCustomizedVisualEffectGroupName:1; unsigned int hasCustomizedVisualEffectblurClippingMode:1; unsigned int hasCustomizedImage:1; unsigned int hasCustomizedImageContentMode:1; unsigned int hasCustomizedStrokeColor:1; unsigned int hasCustomizedStrokeColorTransformer:1; unsigned int hasCustomizedStrokeWidth:1; unsigned int hasCustomizedStrokeOutset:1; unsigned int hasCustomizedMaskedCorners:1; unsigned int hasCustomizedMaterial:1; } _configurationFlags;
    _Bool _contentViewIgnoresBackgroundInsets;
    NSString *_visualEffectGroupName;
    unsigned long long _maskedCorners;
    unsigned long long _visualEffectblurClippingMode;
    long long _defaultStyle;
    long long _backgroundColorTransformerIdentifier;
    long long _strokeColorTransformerIdentifier;
    UIView *_contentView;
    id <_UIViewMaterial> _material;
}

@property (retain, nonatomic) UIShadowProperties *_shadowProperties;
@property (nonatomic) unsigned long long _maskedCorners;
@property (copy, nonatomic) NSString *_visualEffectGroupName;
@property (nonatomic) _Bool _visualEffectAllowsTransparentBlurring;
@property (nonatomic) unsigned long long _visualEffectblurClippingMode;
@property (retain, nonatomic) UIView *customView;
@property (nonatomic) double cornerRadius;
@property (nonatomic) struct NSDirectionalEdgeInsets { double x0; double x1; double x2; double x3; } backgroundInsets;
@property (nonatomic) unsigned long long edgesAddingLayoutMarginsToBackgroundInsets;
@property (retain, nonatomic) UIColor *backgroundColor;
@property (copy, nonatomic) id /* block */ backgroundColorTransformer;
@property (copy, nonatomic) UIVisualEffect *visualEffect;
@property (retain, nonatomic) UIImage *image;
@property (nonatomic) long long imageContentMode;
@property (retain, nonatomic) UIColor *strokeColor;
@property (copy, nonatomic) id /* block */ strokeColorTransformer;
@property (nonatomic) double strokeWidth;
@property (nonatomic) double strokeOutset;
@property (readonly, nonatomic) UIShadowProperties *shadowProperties;
@property (readonly, nonatomic) _Bool isTintBackgroundColor;
@property (nonatomic) long long strokeLocation;
@property (nonatomic) unsigned long long __maskedCorners;
@property (copy, nonatomic) NSString *__visualEffectGroupName;
@property (nonatomic) double _cornerRadius;
@property (readonly, nonatomic) _Bool hasBackgroundColor;
@property (readonly, nonatomic) _Bool hasStroke;
@property (readonly, nonatomic) _Bool hasBackgroundFill;
@property (nonatomic) unsigned long long __visualEffectblurClippingMode;
@property (readonly, nonatomic) _Bool hasMaterial;
@property (retain, nonatomic) id <_UIViewMaterial> _material;
@property (readonly, nonatomic) _Bool hasContentView;
@property (retain, nonatomic) UIView *_contentView;
@property (nonatomic) _Bool _contentViewIgnoresBackgroundInsets;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)listSidebarHeaderConfiguration;
+ (id)listCellConfiguration;
+ (id)listHeaderConfiguration;
+ (_Bool)supportsSecureCoding;
+ (id)listFooterConfiguration;
+ (id)clearConfiguration;
+ (id)listAccompaniedSidebarCellConfiguration;
+ (id)listGroupedCellConfiguration;
+ (id)listPlainCellConfiguration;
+ (id)listGroupedHeaderFooterConfiguration;
+ (id)listPlainHeaderFooterConfiguration;
+ (id)listSidebarCellConfiguration;
+ (id)_listInsetGroupedCellConfiguration;
+ (id)_listInsetGroupedHeaderFooterConfiguration;

/* instance methods */
- (void)__setMaskedCorners:(unsigned long long)corners;
- (void)_setVisualEffectAllowsTransparentBlurring:(_Bool)blurring;
- (id)updatedConfigurationForState:(id)state;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)resolvedBackgroundColorForTintColor:(id)color;
- (id)resolvedStrokeColorForTintColor:(id)color;
- (_Bool)_hasBackgroundFill;
- (_Bool)_isEqualToInternalConfigurationLayoutOnly:(id)only;
- (_Bool)_hasMaterial;
- (void)__setVisualEffectblurClippingMode:(unsigned long long)mode;
- (_Bool)_hasBackgroundColor;
- (id)_updatedConfigurationForState:(id)state;
- (_Bool)_hasContentView;
- (long long)_strokeLocation;
- (void)_setCornerRadius:(double)radius;
- (void)_setMaskedCorners:(unsigned long long)corners;
- (id)initWithCoder:(id)coder;
- (void)_setVisualEffectblurClippingMode:(unsigned long long)mode;
- (void)_setShadowProperties:(id)properties;
- (_Bool)_hasStroke;
- (void)_setContentViewIgnoresBackgroundInsets:(_Bool)insets;
- (void)encodeWithCoder:(id)coder;
- (void)_setVisualEffectGroupName:(id)name;
- (void)_setMaterial:(id)material;
- (_Bool)_isEqualToInternalConfigurationQuick:(id)quick;
- (void)_setStrokeLocation:(long long)location;
- (_Bool)_backgroundFillIsEqual:(id)equal withTintColor:(id)color;
- (void)__setVisualEffectGroupName:(id)name;
- (void)_setContentView:(id)view;
- (_Bool)isEqual:(id)equal;

@end

#endif /* UIBackgroundConfiguration_h */
