//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef UIListContentView_h
#define UIListContentView_h
@import Foundation;

#include "UIContentView-Protocol.h"
#include "UILabel.h"
#include "UILayoutGuide.h"
#include "UIListContentConfiguration.h"
#include "UIView.h"
#include "_UIContentViewComponentDescribing-Protocol.h"
#include "_UIContentViewDefaultStylingObtaining-Protocol.h"
#include "_UIContentViewEditingController.h"
#include "_UIListContentImageView.h"

@class NSLayoutRect;

@interface UIListContentView : UIView <_UIContentViewComponentDescribing, _UIContentViewDefaultStylingObtaining, UIContentView> {
    /* instance variables */
    UIListContentConfiguration *_animatingFromConfiguration;
    UIListContentConfiguration *_animatingToConfiguration;
    double _preferredMaxLayoutWidth;
    _UIContentViewEditingController *_editingController;
    struct { unsigned int imageViewFrameInvalid:1; unsigned int textLabelFrameInvalid:1; unsigned int secondaryTextLabelFrameInvalid:1; } _contentViewFlags;
    _UIListContentImageView *_imageView;
    UILabel *_textLabel;
    UILabel *_secondaryTextLabel;
    id /* block */ _primaryTextFrameDidChangeHandler;
}

@property (copy, nonatomic) UIListContentConfiguration *configuration;
@property (readonly, nonatomic) UILayoutGuide *textLayoutGuide;
@property (readonly, nonatomic) UILayoutGuide *secondaryTextLayoutGuide;
@property (readonly, nonatomic) UILayoutGuide *imageLayoutGuide;
@property (readonly, nonatomic) NSLayoutRect *_primaryTextLayoutRect;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } _primaryTextLayoutFrame;
@property (copy, nonatomic) id /* block */ _primaryTextFrameDidChangeHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) id /* block */ _defaultListContentConfigurationProvider;
@property (readonly, nonatomic) long long _listCellStyle;
@property (readonly, nonatomic) long long _listCellProminence;

/* instance methods */
- (id)_encodableSubviews;
- (struct CGSize { double x0; double x1; })systemLayoutSizeFittingSize:(struct CGSize { double x0; double x1; })size withHorizontalFittingPriority:(float)priority verticalFittingPriority:(float)priority;
- (struct CGSize { double x0; double x1; })_intrinsicSizeWithinSize:(struct CGSize { double x0; double x1; })size;
- (_Bool)becomeFirstResponder;
- (void)_textLegibilityOrContentSizeTraitsChanged;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (_Bool)_shouldAnimatePropertyWithKey:(id)key;
- (double)_multilineContextWidth;
- (void)_setMultilineContextWidth:(double)width;
- (void)_layoutMarginsDidChangeFromOldMargins:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })margins;
- (_Bool)supportsConfiguration:(id)configuration;
- (id)initWithCoder:(id)coder;
- (void)layoutSubviews;
- (void)encodeWithCoder:(id)coder;
- (void)_prepareForSecondIntrinsicContentSizeCalculationWithLayoutEngineBounds:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds;
- (double)_preferredMaxLayoutWidth;
- (id)initWithConfiguration:(id)configuration;
- (_Bool)_needsDoubleUpdateConstraintsPass;
- (void)_prepareForFirstIntrinsicContentSizeCalculation;
- (void)_setPrimaryTextFrameDidChangeHandler:(id /* block */)handler;

@end

#endif /* UIListContentView_h */
