//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef UITable_Protocol_h
#define UITable_Protocol_h
@import Foundation;

#include "UIColor.h"
#include "UIEditable-Protocol.h"
#include "UIScrollView.h"
#include "UITableConstantsTableProviding-Protocol.h"

@protocol UITable <UIEditable, UITableConstantsTableProviding>

@required

@property (readonly, nonatomic) UIScrollView *scrollView;
@property (readonly, nonatomic) long long numberOfSections;
@property (readonly, nonatomic) _Bool allowsMultipleSelection;
@property (readonly, nonatomic) _Bool allowsMultipleSelectionDuringEditing;
@property (readonly, nonatomic) double rowHeight;
@property (readonly, nonatomic) double sectionHeaderHeight;
@property (readonly, nonatomic) double sectionFooterHeight;
@property (readonly, nonatomic) double estimatedRowHeight;
@property (readonly, nonatomic) double estimatedSectionHeaderHeight;
@property (readonly, nonatomic) double estimatedSectionFooterHeight;
@property (readonly, nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } separatorInset;
@property (readonly, nonatomic) _Bool separatorInsetIsRelativeToCellEdges;
@property (readonly, nonatomic) _Bool usesVariableMargins;
@property (readonly, nonatomic) _Bool overlapsSectionHeaderViews;
@property (readonly, nonatomic) double backgroundInset;
@property (readonly, nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } cellSafeAreaInsets;
@property (readonly, nonatomic) _Bool cellLayoutMarginsFollowReadableWidth;
@property (nonatomic) _Bool _sectionHeadersHugContent;
@property (readonly, nonatomic) double topPadding;
@property (readonly, nonatomic) double bottomPadding;
@property (readonly, nonatomic) _Bool showingIndex;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } indexFrame;
@property (readonly, nonatomic) double indexBarExtentFromEdge;
@property (readonly, nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } sectionContentInset;
@property (readonly, nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } rawSectionContentInset;
@property (readonly, nonatomic) double sectionCornerRadius;
@property (readonly, nonatomic) _Bool sectionContentInsetFollowsLayoutMargins;
@property (readonly, nonatomic) _Bool supplementarySectionHeadersHugContent;
@property (readonly, nonatomic) _Bool supplementariesFollowSectionContentInsets;
@property (readonly, nonatomic) UIColor *accessoryBaseColor;
@property (readonly, nonatomic) UIColor *multiselectCheckmarkColor;

/* required instance methods */
- (id)_scrollView;
- (_Bool)_isShowingIndex;
- (id)_accessoryBaseColor;
- (double)_backgroundInset;
- (double)_bottomPadding;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })_cellSafeAreaInsets;
- (void)_headerFooterDidInvalidateIntrinsicContentSize:(id)size;
- (double)_indexBarExtentFromEdge;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })_indexFrame;
- (id)_multiselectCheckmarkColor;
- (long long)_numberOfRowsInSection:(long long)section;
- (long long)_numberOfSections;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })_rawSectionContentInset;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })_sectionContentInset;
- (_Bool)_sectionContentInsetFollowsLayoutMargins;
- (double)_sectionCornerRadius;
- (_Bool)_separatorInsetIsRelativeToCellEdges;
- (void)_setHeadersHugContent:(_Bool)content;
- (_Bool)_shouldHaveFooterViewForSection:(long long)section;
- (_Bool)_shouldHaveHeaderViewForSection:(long long)section;
- (_Bool)_supplementariesFollowSectionContentInsets;
- (_Bool)_supplementarySectionHeadersHugContent;
- (double)_topPadding;

@optional

@end

#endif /* UITable_Protocol_h */
