//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef UIVectorLabel_h
#define UIVectorLabel_h
@import Foundation;

#include "UIColor.h"
#include "UIView.h"
#include "_UILabelContent.h"
#include "_UIVectorTextLayout.h"

@class UIFont;

@interface UIVectorLabel : UIView {
    /* instance variables */
    _UILabelContent *_content;
    NSMutableDictionary *_defaultAttributes;
    _UIVectorTextLayout *_sizingLayout;
    _UIVectorTextLayout *_visualLayout;
    struct { unsigned int usesExplicitPreferredMaxLayoutWidth:1; } _labelFlags;
    double _multilineContextWidth;
}

@property (retain, nonatomic) _UILabelContent *_content;
@property (copy, nonatomic) NSString *text;
@property (retain, nonatomic) UIColor *textColor;
@property (retain, nonatomic) UIFont *font;
@property (nonatomic) unsigned long long numberOfLines;
@property (nonatomic) double preferredMaxLayoutWidth;
@property (copy, nonatomic) NSAttributedString *_attributedText;

/* class methods */
+ (id)_defaultAttributes;
+ (id)_defaultFont;
+ (Class)layerClass;

/* instance methods */
- (void)setBounds:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds;
- (void)_setTextColor:(id)color;
- (double)_baselineOffsetFromBottom;
- (struct CGSize { double x0; double x1; })_intrinsicSizeWithinSize:(struct CGSize { double x0; double x1; })size;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (_Bool)_shouldAnimatePropertyWithKey:(id)key;
- (id)_defaultAttributes;
- (double)_multilineContextWidth;
- (void)_setMultilineContextWidth:(double)width;
- (void)setFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })intrinsicContentSize;
- (void)_generateDeferredAnimations:(id)animations;
- (void)_prepareForSecondIntrinsicContentSizeCalculationWithLayoutEngineBounds:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds;
- (double)_preferredMaxLayoutWidth;
- (_Bool)_needsDoubleUpdateConstraintsPass;
- (void)_prepareForFirstIntrinsicContentSizeCalculation;
- (id)_attributedTextCompatibleForSizing;
- (void)_ensureSizingLayout;
- (void)_ensureVisualLayout;
- (double)_firstBaselineOffsetFromTop;
- (double)_firstLineBaseline;
- (id)_labelLayer;
- (double)_lastLineBaseline;
- (id)_layoutParametersWithinSize:(struct CGSize { double x0; double x1; })size forSizing:(_Bool)sizing;
- (id)_materializedAttributedText;
- (void)_mergeDefaultAttributesForDowngradingContent:(id)content;
- (void)_setAttributedText:(id)text;
- (void)_setContent:(id)content;
- (void)_setNeedsUpdateLayerIfNeeded;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })textRectForBounds:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds limitedToNumberOfLines:(long long)lines;

@end

#endif /* UIVectorLabel_h */
