//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 401.0.0.0.0
//
#ifndef RCNetworkActivity_h
#define RCNetworkActivity_h
@import Foundation;

#include "RCUnfairLock.h"

@protocol OS_nw_activity;

@interface RCNetworkActivity : NSObject {
    /* instance variables */
    NSObject<OS_nw_activity> *_activity;
}

@property (retain, nonatomic) RCUnfairLock *accessLock;
@property (nonatomic) unsigned int domain;
@property (nonatomic) unsigned int label;
@property (retain, nonatomic) NSUUID *parentToken;

/* class methods */
+ (id)activityWithDomain:(unsigned int)domain label:(unsigned int)label parentToken:(id)token;

/* instance methods */
- (void)startActivity;
- (void)attachActivityToTask:(id)task;
- (void)completeActivityWithSuccess:(_Bool)success;
- (id)initWithDomain:(unsigned int)domain label:(unsigned int)label parentToken:(id)token;

@end

#endif /* RCNetworkActivity_h */
