//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 365.3.1.0.0
//
#ifndef NFCPaymentTagReaderSession_h
#define NFCPaymentTagReaderSession_h
@import Foundation;

#include "NFCTagReaderSession.h"

@interface NFCPaymentTagReaderSession : NFCTagReaderSession

/* class methods */
+ (_Bool)isPaymentSession;
+ (_Bool)readingAvailable;

/* instance methods */
- (id)initWithDelegate:(id)delegate queue:(id)queue;
- (id)initWithConfiguration:(id)configuration delegate:(id)delegate queue:(id)queue;
- (id)initWithDelegate:(id)delegate sessionDelegateType:(long long)type sessionType:(unsigned long long)type pollConfig:(id)config queue:(id)queue;
- (id)initWithPollConfig:(id)config swiftDelegate:(id)delegate sessionType:(unsigned long long)type queue:(id)queue;
- (id)initWithPollingOption:(long long)option delegate:(id)delegate queue:(id)queue;
- (id)initWithSwiftDelegate:(id)delegate queue:(id)queue;

@end

#endif /* NFCPaymentTagReaderSession_h */
