//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4610.0.0.0.0
//
#ifndef MWFeedParser_h
#define MWFeedParser_h
@import Foundation;

#include "MWFeedInfo.h"
#include "MWFeedItem.h"
#include "MWFeedParserDelegate-Protocol.h"
#include "NSXMLParserDelegate-Protocol.h"

@class NSURLRequest, NSURLSessionDataTask;

@interface MWFeedParser : NSObject <NSXMLParserDelegate> {
    /* instance variables */
    int feedType;
    NSDateFormatter *dateFormatterRFC822;
    NSDateFormatter *dateFormatterRFC3339;
    _Bool aborted;
    _Bool parsingComplete;
    _Bool hasEncounteredItems;
    _Bool parseStructureAsContent;
}

@property (copy, nonatomic) NSURL *url;
@property (retain, nonatomic) NSURLRequest *request;
@property (retain, nonatomic) NSURLSessionDataTask *urlTask;
@property (retain, nonatomic) NSXMLParser *feedParser;
@property (retain, nonatomic) NSString *currentPath;
@property (retain, nonatomic) NSMutableString *currentText;
@property (retain, nonatomic) NSDictionary *currentElementAttributes;
@property (retain, nonatomic) MWFeedItem *item;
@property (retain, nonatomic) MWFeedInfo *info;
@property (copy, nonatomic) NSString *pathOfElementWithXHTMLType;
@property (weak, nonatomic) id <MWFeedParserDelegate> delegate;
@property (nonatomic) int feedParseType;
@property (readonly, nonatomic) _Bool stopped;
@property (readonly, nonatomic) _Bool failed;
@property (readonly, nonatomic) _Bool parsing;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (_Bool)parse;
- (void)parser:(id)parser foundCharacters:(id)characters;
- (void)parser:(id)parser foundCDATA:(id)cdata;
- (_Bool)isStopped;
- (void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
- (void)parser:(id)parser validationErrorOccurred:(id)occurred;
- (void)parserDidEndDocument:(id)document;
- (void)reset;
- (id)init;
- (void)parser:(id)parser parseErrorOccurred:(id)occurred;
- (void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
- (void)parserDidStartDocument:(id)document;
- (_Bool)didFail;
- (void)parsingFinished;
- (void)abortParsingEarly;
- (_Bool)createEnclosureFromAttributes:(id)attributes andAddToItem:(id)item;
- (void)dispatchFeedInfoToDelegate;
- (void)dispatchFeedItemToDelegate;
- (id)initWithFeedRequest:(id)request;
- (id)initWithFeedURL:(id)url;
- (_Bool)isParsing;
- (void)parsingFailedWithErrorCode:(int)code andDescription:(id)description;
- (_Bool)processAtomLink:(id)link andAddToMWObject:(id)mwobject;
- (void)startParsingData:(id)data textEncodingName:(id)name;
- (void)stopParsing;

@end

#endif /* MWFeedParser_h */
