//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4610.0.0.0.0
//
#ifndef WFTakeScreenshotAction_h
#define WFTakeScreenshotAction_h
@import Foundation;

@class FBSDisplayLayoutMonitor, WFAction;

@interface WFTakeScreenshotAction : WFAction

@property (retain, nonatomic) FBSDisplayLayoutMonitor *displayLayoutMonitor;

/* class methods */
+ (_Bool)outputIsExemptFromTaintTrackingInheritance;

/* instance methods */
- (void)takeScreenshot;
- (void)cancel;
- (_Bool)skipsProcessingHiddenParameters;
- (id)contentDestinationWithError:(id *)error;
- (id)disabledOnPlatforms;
- (id)parameterSummary;
- (void)runAsynchronouslyWithInput:(id)input;
- (id)smartPromptWithContentDescription:(id)description contentDestination:(id)destination workflowName:(id)name;
- (void)notifyVisibleScenesOfScreenshot:(id /* block */)screenshot;
- (id)screenshotDisplay:(id)display error:(id *)error;

@end

#endif /* WFTakeScreenshotAction_h */
