//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1166.6.7.1.1
//
#ifndef HMPersonManager_HFAdditions_h
#define HMPersonManager_HFAdditions_h
@import Foundation;

@interface HMPersonManager (HFAdditions) <HFHomeKitObject>

/* instance methods */
- (id)uniqueIdentifier;
- (id)hf_associateFaceCropsWithUUIDs:(id)uuids toPersonWithUUID:(id)uuid;
- (id)hf_linkFromPerson:(id)person toPerson:(id)person toPersonManagerUUID:(id)uuid;
- (id)hf_namePerson:(id)person name:(id)name;
- (id)hf_reassociateFaceCropsFromPersonWithUUID:(id)uuid toPersonWithUUID:(id)uuid removePerson:(_Bool)person;
- (id)hf_removeFaceCropsWithUUIDs:(id)uuids;
- (id)hf_removePersonWithUUID:(id)uuid;
- (id)hf_faceCropsForPersonWithIdentifier:(id)identifier;
- (id)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:(id)identifier;
- (id)hf_personWithIdentifier:(id)identifier;

@end

#endif /* HMPersonManager_HFAdditions_h */
