//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 820.5.18.0.0
//
#ifndef GKHostedChallengeIssueController_h
#define GKHostedChallengeIssueController_h
@import Foundation;

#include "GKChallengeIssueHostViewController.h"
#include "GKExtensionParentViewControllerProtocol-Protocol.h"

@class GKChallenge, UIViewController;

@interface GKHostedChallengeIssueController : UIViewController <GKExtensionParentViewControllerProtocol>

@property (retain, nonatomic) NSArray *players;
@property (copy, nonatomic) NSString *defaultMessage;
@property (retain, nonatomic) GKChallenge *challenge;
@property (nonatomic) _Bool forcePicker;
@property (copy, nonatomic) id /* block */ completionHandler;
@property (retain, nonatomic) GKChallengeIssueHostViewController *remoteViewController;
@property (copy, nonatomic) id /* block */ receivedRemoteHandler;
@property (copy, nonatomic) id /* block */ dismissCompletionHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)_preventsAppearanceProxyCustomization;
+ (id)presentationQueue;
+ (id)hostedIssueControllerWithChallenge:(id)challenge players:(id)players defaultMessage:(id)message completionHandler:(id /* block */)handler;

/* instance methods */
- (_Bool)shouldAutomaticallyForwardRotationMethods;
- (void)dealloc;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
- (void)_setupChildViewController;
- (void)extensionDidFinishWithError:(id)error;
- (void)_setupRemoteViewController;
- (void)doneWithPlayers:(id)players message:(id)message;
- (id)initWithChallenge:(id)challenge players:(id)players defaultMessage:(id)message completionHandler:(id /* block */)handler;

@end

#endif /* GKHostedChallengeIssueController_h */
