//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1318.0.0.0.0
//
#ifndef _TtC11WeatherMaps5Field_h
#define _TtC11WeatherMaps5Field_h
@import Foundation;

@class WeatherMaps.WeatherMapTilePath, _$sSf, _$sSi, _TtCs12_SwiftObject;

@interface _TtC11WeatherMaps5Field : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    WeatherMaps.WeatherMapTilePath tilePath;
    _$sSi length;
    _$sSf gridResolution;
}

@end

#endif /* _TtC11WeatherMaps5Field_h */
