//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 296.11.0.0.0
//
#ifndef _TtC16LinkPresentation30DominantColorAnalysisProcessor_h
#define _TtC16LinkPresentation30DominantColorAnalysisProcessor_h
@import Foundation;

@class CoreGraphics.CGFloat, _$sSa -> CoreGraphics.CGFloat, _$sSaySo7UIColorCG, _$sSdSg, _$sSi, _$sSiSg, _$sSo7UIColorCSg, _TtCs12_SwiftObject, __C.CGContext;

@interface _TtC16LinkPresentation30DominantColorAnalysisProcessor : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSaySo7UIColorCG imageHSVMap;
    CoreGraphics.CGFloat averageLuminance;
    _$sSa -> CoreGraphics.CGFloat colorCounts;
    _$sSa -> CoreGraphics.CGFloat sortedColorCounts;
    __C.CGContext context;
    _$sSi numberOfSlicesForAnalysis;
    _$sSdSg $__lazy_storage_$_outerEdgeCutoff;
    _$sSiSg $__lazy_storage_$_slicesIterationCount;
    _$sSaySo7UIColorCG dominantColors;
    _$sSo7UIColorCSg backgroundColor;
}

@end

#endif /* _TtC16LinkPresentation30DominantColorAnalysisProcessor_h */
