//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 627.13.0.1.0
//
#ifndef ATXUserEducationSuggestionFeedback_h
#define ATXUserEducationSuggestionFeedback_h
@import Foundation;

#include "ATXUserEducationSuggestion-Protocol.h"

@interface ATXUserEducationSuggestionFeedback : NSObject <NSSecureCoding>

@property (readonly, nonatomic) id <ATXUserEducationSuggestion> userEducationSuggestion;
@property (readonly, nonatomic) unsigned long long feedbackType;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)suggestion;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)description;
- (id)initWithUserEducationSuggestion:(id)suggestion feedbackType:(unsigned long long)type;

@end

#endif /* ATXUserEducationSuggestionFeedback_h */
