//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2360.120.2.0.0
//
#ifndef CKDCodeFunctionInvokeURLRequest_h
#define CKDCodeFunctionInvokeURLRequest_h
@import Foundation;

#include "CKDTrustedTargetWrappedKey.h"
#include "CKDURLRequest.h"

@interface CKDCodeFunctionInvokeURLRequest : CKDURLRequest

@property (copy, nonatomic) NSString *serviceName;
@property (copy, nonatomic) NSString *functionName;
@property (retain, nonatomic) NSData *serializedParameters;
@property (retain, nonatomic) NSData *attestationEntropy;
@property (copy, nonatomic) NSArray *pccWrappedInvocationKeys;
@property (copy, nonatomic) CKDTrustedTargetWrappedKey *trustedTargetWrappedInvocationKey;
@property (copy, nonatomic) id /* block */ serializedResultsCallback;

/* instance methods */
- (id)requestOperationClasses;
- (id)generateRequestOperations;
- (void)requestDidParseNodeFailure:(id)failure;
- (id)requestDidParseProtobufObject:(id)object;
- (void)fillOutEquivalencyPropertiesBuilder:(id)builder;
- (_Bool)requestGETPreAuth;
- (_Bool)allowsAnonymousAccount;
- (long long)databaseScope;
- (id)additionalHeaderValues;
- (id)initWithOperation:(id)operation serviceName:(id)name functionName:(id)name serializedParameters:(id)parameters attestationEntropy:(id)entropy pccWrappedInvocationKeys:(id)keys trustedTargetWrappedInvocationKey:(id)key;

@end

#endif /* CKDCodeFunctionInvokeURLRequest_h */
