//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2360.120.2.0.0
//
#ifndef CKDPZoneEtagValidationInformation_h
#define CKDPZoneEtagValidationInformation_h
@import Foundation;

@class PBCodable;

@interface CKDPZoneEtagValidationInformation : PBCodable <NSCopying> {
    /* instance variables */
    struct { unsigned int validationType:1; } _has;
}

@property (retain, nonatomic) NSMutableArray *ancestorInformations;
@property (nonatomic) _Bool hasValidationType;
@property (nonatomic) int validationType;
@property (readonly, nonatomic) _Bool hasLocalZoneEtag;
@property (retain, nonatomic) NSString *localZoneEtag;

/* class methods */
+ (Class)ancestorInformationType;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (void)copyTo:(id)to;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)writeTo:(id)to;
- (id)dictionaryRepresentation;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (int)StringAsValidationType:(id)type;
- (void)addAncestorInformation:(id)information;
- (id)ancestorInformationAtIndex:(unsigned long long)index;
- (unsigned long long)ancestorInformationsCount;
- (void)clearAncestorInformations;
- (id)validationTypeAsString:(int)string;

@end

#endif /* CKDPZoneEtagValidationInformation_h */
