//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4610.0.0.0.0
//
#ifndef WFEvernoteTag_h
#define WFEvernoteTag_h
@import Foundation;

@interface WFEvernoteTag : NSObject <NSSecureCoding>

@property (retain, nonatomic) NSString *guid;
@property (retain, nonatomic) NSString *name;
@property (retain, nonatomic) NSString *parentGuid;
@property (retain, nonatomic) NSNumber *updateSequenceNum;

/* class methods */
+ (void)initialize;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)initWithTag:(id)tag;
- (id)initWithGUID:(id)guid name:(id)name parentGuid:(id)guid updateSequenceNum:(id)num;

@end

#endif /* WFEvernoteTag_h */
