//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 427.0.0.0.0
//
#ifndef SABootInfo_h
#define SABootInfo_h
@import Foundation;

#include "SAJSONSerialization-Protocol.h"
#include "SASerializable-Protocol.h"

@interface SABootInfo : NSObject <SAJSONSerialization, SASerializable>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) NSUUID *uuid;
@property (readonly) double wallTimeAtMachAbsZero;
@property (readonly) NSString *bootArgs;
@property (readonly) NSString *kernelVersion;
@property (readonly) NSString *osProductVersion;
@property (readonly) NSString *osProductVersionExtra;
@property (readonly) NSString *osBuildVersion;

/* class methods */
+ (id)newInstanceWithoutReferencesFromSerializedBuffer:(const void *)buffer bufferLength:(unsigned long long)length;
+ (id)classDictionaryKey;

/* instance methods */
- (unsigned long long)sizeInBytesForSerializedVersion;
- (void)writeJSONDictionaryEntriesToStream:(id)stream;
- (void)addSelfToSerializationDictionary:(id)dictionary;
- (void)populateReferencesUsingBuffer:(const void *)buffer bufferLength:(unsigned long long)length andDeserializationDictionary:(id)dictionary andDataBufferDictionary:(id)dictionary;
- (_Bool)addSelfToBuffer:(struct { unsigned char x0; unsigned char x1; unsigned long long x2; double x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; } *)buffer bufferLength:(unsigned long long)length withCompletedSerializationDictionary:(id)dictionary;

@end

#endif /* SABootInfo_h */
