//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 13.1.21.4.0
//
#ifndef _TtC5Hands11JpegDecoder_h
#define _TtC5Hands11JpegDecoder_h
@import Foundation;

@class _$sSD -> Hands.JpegDecoder.InputMetaKey __C.CVPixelBufferPool, _$sSD -> Hands.JpegDecoder.InputMetaKey __C.VTDecompressionSession, _$sSo21OS_dispatch_semaphoreC, __C.VTPixelTransferSession ?;

@interface _TtC5Hands11JpegDecoder : NSObject { // (Swift)
    /* instance variables */
    _$sSD -> Hands.JpegDecoder.InputMetaKey __C.VTDecompressionSession _decompressionSessions;
    _$sSo21OS_dispatch_semaphoreC _syncSemaphore;
    __C.VTPixelTransferSession ? _vtPixelTransferSession;
    _$sSD -> Hands.JpegDecoder.InputMetaKey __C.CVPixelBufferPool _pixelBufferPoolDict;
}

/* instance methods */
- (void)dealloc;
- (id)init;

@end

#endif /* _TtC5Hands11JpegDecoder_h */
