//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9.5.4.0.0
//
#ifndef VNDetectionprintInferenceNetworkDescriptor_h
#define VNDetectionprintInferenceNetworkDescriptor_h
@import Foundation;

@class VisionCoreEspressoNetworkDescriptor;

@interface VNDetectionprintInferenceNetworkDescriptor : VisionCoreEspressoNetworkDescriptor

@property (readonly, copy, nonatomic) NSDictionary *tensorKeyToPrintOutputName;

/* class methods */
+ (id)URLForEspressoModelNamed:(id)named error:(id *)error;
+ (id)_descriptorForNetworkFileName:(id)name networkSpecifier:(id)specifier imageInputName:(id)name tensorKeyToOutputNames:(id)names error:(id *)error;
+ (id)sceneNetV3BasedNetworkAndReturnError:(id *)error;

/* instance methods */

@end

#endif /* VNDetectionprintInferenceNetworkDescriptor_h */
