//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2.16.2.0.0
//
#ifndef _TtC8RoomPlan16FloorPlanManager_h
#define _TtC8RoomPlan16FloorPlanManager_h
@import Foundation;

@class Swift.Bool, _$sSD -> Foundation.UUID RoomPlan.HitPointAndState, _$sSD -> Foundation.UUID RoomPlan.ScanItem, _TtCs12_SwiftObject;

@interface _TtC8RoomPlan16FloorPlanManager : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    Swift.Bool wallHitPointsOnBorder;
    Swift.Bool objectHitPointsOnBorder;
    _$sSD -> Foundation.UUID RoomPlan.ScanItem scanItems;
    _$sSD -> Foundation.UUID RoomPlan.HitPointAndState hitPoints;
}

@end

#endif /* _TtC8RoomPlan16FloorPlanManager_h */
