//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 5883.0.0.0.0
//
#ifndef _TtC10NewsDaemonP33_57384A5BC146306734585127338E266D12BundleLoader_h
#define _TtC10NewsDaemonP33_57384A5BC146306734585127338E266D12BundleLoader_h
@import Foundation;

@class _TtCs12_SwiftObject;

@interface _TtC10NewsDaemonP33_57384A5BC146306734585127338E266D12BundleLoader : _TtCs12_SwiftObject // (Swift)

@end

#endif /* _TtC10NewsDaemonP33_57384A5BC146306734585127338E266D12BundleLoader_h */
