//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef _PXExplicitCuratedLibraryAssetsDataSourceManagerConfiguration_h
#define _PXExplicitCuratedLibraryAssetsDataSourceManagerConfiguration_h
@import Foundation;

#include "PXCuratedLibraryAssetsDataSourceManagerConfiguration.h"

@class PXAssetsDataSourceManager;

@interface _PXExplicitCuratedLibraryAssetsDataSourceManagerConfiguration : PXCuratedLibraryAssetsDataSourceManagerConfiguration {
    /* instance variables */
    PXAssetsDataSourceManager *_yearsAssetsDataSourceManager;
    PXAssetsDataSourceManager *_monthsAssetsDataSourceManager;
    PXAssetsDataSourceManager *_daysAssetsDataSourceManager;
    PXAssetsDataSourceManager *_allPhotosAssetsDataSourceManager;
}

/* instance methods */
- (id)configurationForZoomLevel:(long long)level;
- (id)initWithPhotoLibrary:(id)library yearsAssetsDataSourceManager:(id)manager monthsAssetsDataSourceManager:(id)manager daysAssetsDataSourceManager:(id)manager allPhotosAssetsDataSourceManager:(id)manager;

@end

#endif /* _PXExplicitCuratedLibraryAssetsDataSourceManagerConfiguration_h */
