//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef PXCPLUIStatusProvider_h
#define PXCPLUIStatusProvider_h
@import Foundation;

#include "PXCPLActionManager.h"
#include "PXCPLStatusProvider-Protocol.h"
#include "PXCPLStatusProviderMonitor.h"
#include "PXCPLUIStatus.h"
#include "PXChangeObserver-Protocol.h"

@class PXObservable;

@interface PXCPLUIStatusProvider : PXObservable <PXChangeObserver> {
    /* instance variables */
    PXCPLStatusProviderMonitor *_statusProviderMonitor;
    PXObservable<PXCPLStatusProvider> *_statusProvider;
}

@property (copy, nonatomic) NSDate *currentDateForTesting;
@property (readonly, nonatomic) PXCPLUIStatus *status;
@property (readonly, nonatomic) PXCPLActionManager *actionManager;
@property (readonly, nonatomic) unsigned long long presentationStyle;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithPhotoLibrary:(id)library presentationStyle:(unsigned long long)style;
- (id)initWithStatusProvider:(id)provider actionManager:(id)manager presentationStyle:(unsigned long long)style;
- (id)initWithPhotoLibrary:(id)library actionManager:(id)manager presentationStyle:(unsigned long long)style;
- (id)initWithPhotoLibrary:(id)library actionManager:(id)manager;
- (void)_statusDidChange:(id)change;
- (void)_updateStatus;
- (void)observable:(id)observable didChange:(unsigned long long)change context:(void *)context;
- (id)init;
- (void)_updateStatusProviderMonitor;
- (id)initWithPhotoLibrary:(id)library;

@end

#endif /* PXCPLUIStatusProvider_h */
