//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 418.1.0.0.0
//
#ifndef _PASSecureCodingHelper_h
#define _PASSecureCodingHelper_h
@import Foundation;

@interface _PASSecureCodingHelper : NSObject

/* class methods */
+ (id)robustDecodeObjectOfClass:(Class)_class forKey:(id)key withCoder:(id)coder expectNonNull:(_Bool)null errorDomain:(id)domain errorCode:(long long)code logHandle:(id)handle;
+ (id)robustDecodeObjectOfClasses:(id)classes forKey:(id)key withCoder:(id)coder expectNonNull:(_Bool)null errorDomain:(id)domain errorCode:(long long)code logHandle:(id)handle;

@end

#endif /* _PASSecureCodingHelper_h */
