//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2418.5.9.101.0
//
#ifndef SKGReferenceNode_h
#define SKGReferenceNode_h
@import Foundation;

#include "SKGNode.h"

@interface SKGReferenceNode : SKGNode

/* class methods */
+ (id)label;
+ (Class)edgeClass;
+ (id)referenceWithElementIdentifier:(unsigned long long)identifier inGraph:(id)graph;

/* instance methods */
- (id)initWithReference:(id)reference;

@end

#endif /* SKGReferenceNode_h */
