//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef PGYearChapterTitleGenerator_h
#define PGYearChapterTitleGenerator_h
@import Foundation;

#include "PGChapterTitleGeneratorProtocol-Protocol.h"

@class MABinaryAdjacency;

@interface PGYearChapterTitleGenerator : NSObject <PGChapterTitleGeneratorProtocol> {
    /* instance variables */
    MABinaryAdjacency *_momentNodesByChapterYearNode;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)generateChapterTitles;
- (id)initWithTriggeredMemory:(id)memory;
- (id)momentNodesByChapterYearNodeWithMomentNodes:(id)nodes;

@end

#endif /* PGYearChapterTitleGenerator_h */
