//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 624.2.5.10.4
//
#ifndef WebPDFView_h
#define WebPDFView_h
@import Foundation;

#include "WebPDFDocumentRepresentation-Protocol.h"
#include "WebPDFDocumentView-Protocol.h"

@class WAKView;

@interface WebPDFView : WAKView <WebPDFDocumentView, WebPDFDocumentRepresentation> {
    /* instance variables */
    _Bool dataSourceHasBeenSet;
    struct CGPDFDocument * _PDFDocument;
    struct RetainPtr<NSString> { NSString *m_ptr; } _title;
    struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } * _pageRects;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (struct CGColor *)shadowColor;
+ (struct CGColor *)backgroundColor;
+ (Class)_representationClassForWebFrame:(id)frame;
+ (id)supportedMIMETypes;

/* instance methods */
- (void)layout;
- (void)drawRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (struct CGPDFDocument *)doc;
- (void)setNeedsLayout:(_Bool)layout;
- (void)dealloc;
- (void)setDataSource:(id)source;
- (id)title;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rectForPageNumber:(unsigned int)number;
- (unsigned int)totalPages;
- (id)documentSource;
- (void)_checkPDFTitle;
- (void)_computePageRects;
- (id)_pagesInRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (_Bool)canProvideDocumentSource;
- (void)dataSourceUpdated:(id)updated;
- (void)drawPage:(struct CGPDFPage *)page;
- (void)finishedLoadingWithDataSource:(id)source;
- (unsigned int)pageNumberForRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)receivedData:(id)data withDataSource:(id)source;
- (void)receivedError:(id)error withDataSource:(id)source;
- (void)viewDidMoveToHostWindow;
- (void)viewWillMoveToHostWindow:(id)window;

@end

#endif /* WebPDFView_h */
