//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1311.7.0.0.0
//
#ifndef PSGInternalClient_h
#define PSGInternalClient_h
@import Foundation;

@class _PASXPCClientHelper;

@interface PSGInternalClient : NSObject {
    /* instance variables */
    _PASXPCClientHelper *_clientHelper;
}

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)_remoteObjectProxy;
- (id)init;
- (id)sysdiagnoseInformationWithError:(id *)error;

@end

#endif /* PSGInternalClient_h */
