//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.3.0.0
//
#ifndef _TtC9SnippetUI17RFPatternExecuted_h
#define _TtC9SnippetUI17RFPatternExecuted_h
@import Foundation;

#include "VRXTurnBasedInstrumentationEvent.h"

@class SnippetUI.SELFInstrumentationClient, _$sSSSg;

@interface _TtC9SnippetUI17RFPatternExecuted : VRXTurnBasedInstrumentationEvent { // (Swift)
    /* instance variables */
    SnippetUI.SELFInstrumentationClient instrumentationClient;
}

@property (nonatomic, readonly) NSString *patternId;
@property (nonatomic, readonly) NSString *patternType;
@property (nonatomic, readonly) NSString *responseViewId;
@property (nonatomic, readonly) NSString *responseMode;

/* instance methods */
- (id)init;
- (void)emitWithTurnIdentifier:(id)identifier;
- (void)emitWithTurnIdentifier:(id)identifier aceViewId:(id)id;
- (id)initWithPatternId:(id)id patternType:(id)type responseMode:(id)mode;
- (id)initWithPatternId:(id)id patternType:(id)type responseViewId:(id)id responseMode:(id)mode;

@end

#endif /* _TtC9SnippetUI17RFPatternExecuted_h */
