//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4025.610.1.0.0
//
#ifndef _PFPodcastsPlaybackSettingsHelper_h
#define _PFPodcastsPlaybackSettingsHelper_h
@import Foundation;

@interface _PFPodcastsPlaybackSettingsHelper : NSObject // (Swift)

/* class methods */
+ (void)saveSettings:(id)settings podcastUUID:(id)uuid defaultsProvider:(id)provider;
+ (id)settingsFor:(id)_for defaultsProvider:(id)provider;

/* instance methods */
- (id)init;

@end

#endif /* _PFPodcastsPlaybackSettingsHelper_h */
