//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1380.0.0.0.0
//
#ifndef NSManagedObjectModel_NewObjectModel_h
#define NSManagedObjectModel_NewObjectModel_h
@import Foundation;

@interface NSManagedObjectModel (NewObjectModel)

/* class methods */
+ (id)modelCandidatesForCloudRecordings;
+ (id)modelCompatibleWithStoreMetadata:(id)metadata forStoreURL:(id)url;
+ (id)mutableModelForModelFileName:(id)name;
+ (id)rc_currentObjectModel;
+ (id)rc_newObjectModel;
+ (id)rc_v10ObjectModel;
+ (id)rc_v11ObjectModel;
+ (id)rc_v12ObjectModel;
+ (id)rc_v13ObjectModel;
+ (id)rc_v14ObjectModel;
+ (id)rc_v6ObjectModel;
+ (id)rc_v7ObjectModel;
+ (id)rc_v7bObjectModel;
+ (id)rc_v8ObjectModel;
+ (id)rc_v9ObjectModel;
+ (void)updateAllowsCloudEncryptionAttributes:(id)attributes;
+ (void)updateAudioFutureAttribute:(id)attribute;

@end

#endif /* NSManagedObjectModel_NewObjectModel_h */
