//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2094.60.51.0.0
//
#ifndef SFCircleProgressView_h
#define SFCircleProgressView_h
@import Foundation;

@class UIColor, UIView;

@interface SFCircleProgressView : UIView

@property (nonatomic) long long progressStartPoint;
@property (retain, nonatomic) UIColor *progressColor;
@property (retain, nonatomic) UIColor *progressBackgroundColor;
@property (nonatomic) double progressLineWidth;
@property (nonatomic) _Bool usesRoundedLineCap;
@property (nonatomic) _Bool showProgressTray;
@property (nonatomic) double progress;

/* class methods */
+ (Class)layerClass;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (void)animateProgressCompletedWithCompletion:(id /* block */)completion;
- (double)progressPresentationValue;
- (void)setProgress:(double)progress animated:(_Bool)animated completion:(id /* block */)completion;
- (void)setProgress:(double)progress animated:(_Bool)animated forced:(_Bool)forced completion:(id /* block */)completion;

@end

#endif /* SFCircleProgressView_h */
