//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1016.206.3.0.0
//
#ifndef WKWebViewConfiguration_QLUtilities_h
#define WKWebViewConfiguration_QLUtilities_h
@import Foundation;

@interface WKWebViewConfiguration (QLUtilities)

/* instance methods */
- (id)_sharedDataStoreForBundleIdentifier:(id)identifier;
- (id)ql_initWithForegroundPriorityAndSourceBundleIdentifier:(id)identifier;

@end

#endif /* WKWebViewConfiguration_QLUtilities_h */
