//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 7.4.25.0.0
//
#ifndef RBAnimationThread_h
#define RBAnimationThread_h
@import Foundation;

@class CADisplayLink;

@interface RBAnimationThread : NSObject {
    /* instance variables */
    struct objc_ptr<NSThread *> { NSThread *_p; } _thread;
    struct objc_ptr<CADisplayLink *> { CADisplayLink *_p; } _link;
    unsigned int _empty_ttl;
    int _frame_rate;
    int _pending_frame_rate;
}

/* instance methods */
- (void)thread:(id)thread;
- (void)dispatchHandlers:(id)handlers;

@end

#endif /* RBAnimationThread_h */
