//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 515.29.0.0.0
//
#ifndef _TtC10CAFCombine30CAFCurrentUserStatusObservable_h
#define _TtC10CAFCombine30CAFCurrentUserStatusObservable_h
@import Foundation;

#include "CAFCurrentUserStatusObserver-Protocol.h"

@class CAFCombine.SafeReadOnlyPublished CAFCombine.CAFCurrentUserStatusObservable Foundation.Data ?, CAFCombine.SafeReadOnlyPublished CAFCombine.CAFCurrentUserStatusObservable _$sSSSg ->, CAFCombine.SafeReadOnlyPublished CAFCombine.CAFCurrentUserStatusObservable _$sSbSg ->, _$sSSSg, _$sSo20CAFCurrentUserStatusC, s.OSAllocatedUnfairLock _$syt;

@interface _TtC10CAFCombine30CAFCurrentUserStatusObservable : NSObject <CAFCurrentUserStatusObserver> { // (Swift)
    /* instance variables */
    _$sSo20CAFCurrentUserStatusC observed;
    _$sSSSg cachedDescription;
    out s.OSAllocatedUnfairLock _$syt cachedDescriptionLock;
    CAFCombine.SafeReadOnlyPublished CAFCombine.CAFCurrentUserStatusObservable Foundation.Data ? _image;
    CAFCombine.SafeReadOnlyPublished CAFCombine.CAFCurrentUserStatusObservable _$sSSSg -> _userVisibleLabel;
    CAFCombine.SafeReadOnlyPublished CAFCombine.CAFCurrentUserStatusObservable _$sSSSg -> _contentURLAction;
    CAFCombine.SafeReadOnlyPublished CAFCombine.CAFCurrentUserStatusObservable _$sSbSg -> _hidden;
}

@property (nonatomic, readonly) NSString *description;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)currentUserStatusService:(id)service didUpdateContentURLAction:(id)urlaction;
- (void)currentUserStatusService:(id)service didUpdateHidden:(_Bool)hidden;
- (void)currentUserStatusService:(id)service didUpdateImage:(id)image;
- (void)currentUserStatusService:(id)service didUpdateUserVisibleLabel:(id)label;
- (void)serviceDidFinishGroupUpdate:(id)update;
- (void)serviceDidUpdate:(id)update characteristic:(id)characteristic fromGroupUpdate:(_Bool)update;
- (void)serviceDidUpdate:(id)update receivedAllValues:(_Bool)values;

@end

#endif /* _TtC10CAFCombine30CAFCurrentUserStatusObservable_h */
