//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 515.29.0.0.0
//
#ifndef _TtC10CAFCombine32CAFBatteryConditioningObservable_h
#define _TtC10CAFCombine32CAFBatteryConditioningObservable_h
@import Foundation;

#include "CAFBatteryConditioningObserver-Protocol.h"

@class CAFCombine.SafeReadOnlyPublished CAFCombine.CAFBatteryConditioningObservable __C.CAFBatteryConditioningState, _$sSSSg, _$sSo22CAFBatteryConditioningC, s.OSAllocatedUnfairLock _$syt;

@interface _TtC10CAFCombine32CAFBatteryConditioningObservable : NSObject <CAFBatteryConditioningObserver> { // (Swift)
    /* instance variables */
    _$sSo22CAFBatteryConditioningC observed;
    _$sSSSg cachedDescription;
    out s.OSAllocatedUnfairLock _$syt cachedDescriptionLock;
    CAFCombine.SafeReadOnlyPublished CAFCombine.CAFBatteryConditioningObservable __C.CAFBatteryConditioningState _batteryConditioningState;
}

@property (nonatomic, readonly) NSString *description;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)batteryConditioningService:(id)service didUpdateBatteryConditioningState:(unsigned char)state;
- (void)serviceDidFinishGroupUpdate:(id)update;
- (void)serviceDidUpdate:(id)update characteristic:(id)characteristic fromGroupUpdate:(_Bool)update;
- (void)serviceDidUpdate:(id)update receivedAllValues:(_Bool)values;

@end

#endif /* _TtC10CAFCombine32CAFBatteryConditioningObservable_h */
