//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 295.600.21.0.0
//
#ifndef BlastDoorTranslationCommandMessage_h
#define BlastDoorTranslationCommandMessage_h
@import Foundation;

@class v24@?0@"NSArray"8@"NSError"16;

@interface BlastDoorTranslationCommandMessage : NSObject { // (Swift)
    /* instance variables */
    v24@?0@"NSArray"8@"NSError"16 translationCommandMessage;
}

@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSString *guid;
@property (nonatomic, readonly) NSArray *parts;

/* instance methods */
- (id)init;

@end

#endif /* BlastDoorTranslationCommandMessage_h */
