//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 103.4.4.0.0
//
#ifndef _TtC10StickerKit23AvatarPickerCoordinator_h
#define _TtC10StickerKit23AvatarPickerCoordinator_h
@import Foundation;

#include "AVTSimpleAvatarPickerSwiftProviderDelegate-Protocol.h"

@class StickerKit.AvatarPickerView;

@interface _TtC10StickerKit23AvatarPickerCoordinator : NSObject <AVTSimpleAvatarPickerSwiftProviderDelegate> { // (Swift)
    /* instance variables */
    StickerKit.AvatarPickerView parent;
}

/* instance methods */
- (id)init;
- (void)avatarPicker:(id)picker didSelectAvatarRecord:(id)record;
- (void)dismissAvatarUIControllerWithIdentifier:(id)identifier animated:(_Bool)animated;
- (void)presentAvatarUIController:(id)uicontroller animated:(_Bool)animated;

@end

#endif /* _TtC10StickerKit23AvatarPickerCoordinator_h */
