//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 145.2.0.0.0
//
#ifndef _TtC19ContactlessReaderUI18VoiceSynthAnnounce_h
#define _TtC19ContactlessReaderUI18VoiceSynthAnnounce_h
@import Foundation;

@class ContactlessReaderUI.VocalMessageType, ContactlessReaderUI.VoiceSynthAnnounce.SpeakingState, ContactlessReaderUI.VoiceSynthListener ?, Foundation.Locale, _$sSS, _$sScCyyt Swift.Never ?, _$sScTyyt Swift.Never ?, _$sSd, _$sSo19AVSpeechSynthesizerC, _$sSo22AVSpeechSynthesisVoiceCSg;

@interface _TtC19ContactlessReaderUI18VoiceSynthAnnounce : NSObject { // (Swift)
    /* instance variables */
    ContactlessReaderUI.VocalMessageType id;
    _$sSS text;
    _$sSd delay;
    Foundation.Locale locale;
    _$sSo19AVSpeechSynthesizerC voiceSynthesizer;
    _$sSo22AVSpeechSynthesisVoiceCSg synthesizerVoice;
    ContactlessReaderUI.VoiceSynthListener ? synthesizerDelegate;
    _$sScCyyt Swift.Never ? announcementContinuation;
    _$sScTyyt Swift.Never ? safeguardTask;
    _$sScTyyt Swift.Never ? speakingTask;
    ContactlessReaderUI.VoiceSynthAnnounce.SpeakingState speakingState;
}

@property (nonatomic, readonly) NSString *description;

/* instance methods */
- (id)init;

@end

#endif /* _TtC19ContactlessReaderUI18VoiceSynthAnnounce_h */
