//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef PUImportViewController_h
#define PUImportViewController_h
@import Foundation;

#include "PUCameraImportItemCellDelegate-Protocol.h"
#include "PUImportActionCoordinator.h"
#include "PUImportActionCoordinatorDelegate-Protocol.h"
#include "PUImportChangeDetailsCollectionViewHelper.h"
#include "PUImportFakePhotosDataSource.h"
#include "PUImportSectionedGridLayoutDelegate-Protocol.h"
#include "PUPhotosGridViewController.h"
#include "PUPhotosGridViewControllerSpec.h"
#include "PUSectionedGridLayoutDelegate-Protocol.h"
#include "PXActionableSectionHeaderViewDelegate-Protocol.h"
#include "PXChangeObserver-Protocol.h"
#include "PXImportAssetsDataSourceManagerObserver-Protocol.h"
#include "PXImportControllerTopLevelCompletionDelegate-Protocol.h"
#include "PXSettingsKeyObserver-Protocol.h"
#include "PXSwipeSelectionManagerDelegate-Protocol.h"
#include "UIGestureRecognizerDelegate-Protocol.h"

@class PHImportSource, PLRoundProgressView, PXActionableSectionHeaderView, PXImportAssetsDataSource, PXImportAssetsDataSourceManager, PXImportController, PXImportSessionInfo, PXProgrammaticNavigationDestination, PXSelectionSnapshot, PXSwipeSelectionManager, UIBarButtonItem, UITapGestureRecognizer;

@interface PUImportViewController : PUPhotosGridViewController <PUSectionedGridLayoutDelegate, PUImportActionCoordinatorDelegate, PXImportAssetsDataSourceManagerObserver, PXImportControllerTopLevelCompletionDelegate, PXActionableSectionHeaderViewDelegate, PUImportSectionedGridLayoutDelegate, PXSettingsKeyObserver, PUCameraImportItemCellDelegate, PXChangeObserver, PXSwipeSelectionManagerDelegate, UIGestureRecognizerDelegate> {
    /* instance variables */
    _Bool _completedAnImport;
    PXImportSessionInfo *_completedImportSessionInfo;
    struct __CFUserNotification * _importCompleteNotification;
    UIBarButtonItem *_importButtonItem;
    UIBarButtonItem *_deleteButtonItemIcon;
    UIBarButtonItem *_deleteButtonItem;
    UIBarButtonItem *_stopBarItem;
    UIBarButtonItem *_progressButtonItem;
    unsigned long long _busyCount;
    _Bool _allowsSelection;
    id _mstreamd_pause_context;
    _Bool _acceptsLongPress;
    _Bool _compactLayoutMode;
    UITapGestureRecognizer *_tapGestureRecognizer;
    PXProgrammaticNavigationDestination *_px_navigationDestination;
}

@property (retain, nonatomic) PUPhotosGridViewControllerSpec *_spec;
@property (nonatomic) double _collectionViewLayoutReferenceWidth;
@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } collectionViewSafeAreaInsets;
@property (retain, nonatomic) id _pendingViewSizeTransitionContext;
@property (retain, nonatomic) id _cachedViewSizeTransitionContext;
@property (nonatomic) struct CGSize { double x0; double x1; } _cachedViewSizeTransitionContextSize;
@property (retain, nonatomic) NSProgress *importProgress;
@property (retain, nonatomic) PXImportController *importController;
@property (retain, nonatomic) PXImportAssetsDataSourceManager *importDataSourceManager;
@property (retain, nonatomic) PXImportAssetsDataSource *importDataSource;
@property (retain, nonatomic) PXImportAssetsDataSourceManager *unfilteredImportDataSourceManager;
@property (nonatomic) _Bool performingDataSourceChange;
@property (nonatomic) _Bool needsDataReloadAfterAnimatingDataSourceChange;
@property (retain, nonatomic) PXImportAssetsDataSource *pendingDataSource;
@property (retain, nonatomic) PUImportChangeDetailsCollectionViewHelper *changeDetailsHelper;
@property (nonatomic) _Bool transitioningToNewSize;
@property (nonatomic) _Bool viewAppearing;
@property (retain, nonatomic) PUImportFakePhotosDataSource *fakePhotosDataSource;
@property (retain, nonatomic) PUImportActionCoordinator *actionCoordinator;
@property (retain, nonatomic) PXSwipeSelectionManager *swipeSelectionManager;
@property (retain, nonatomic) PXSelectionSnapshot *currentSelectionSnapshot;
@property (nonatomic) _Bool userWantsAlreadyImportedSectionCollapsedIfPossible;
@property (nonatomic) _Bool shouldCollapseAlreadyImportedSection;
@property (nonatomic) _Bool userHasScrolled;
@property (nonatomic) _Bool shouldStayScrolledToBottom;
@property (retain, nonatomic) PLRoundProgressView *roundProgressView;
@property (nonatomic) long long numItemsCompleted;
@property (nonatomic) long long numTotalItemsToComplete;
@property (retain, nonatomic) NSMutableSet *itemsBeingTransitioned;
@property (nonatomic) _Bool animateHeaderActionButtonChanges;
@property (retain, nonatomic) NSNumber *cachedHeaderHeight;
@property (retain, nonatomic) PXActionableSectionHeaderView *referenceHeaderView;
@property (nonatomic) _Bool isPeeking;
@property (nonatomic) double referenceWidth;
@property (retain, nonatomic) UITapGestureRecognizer *doubleTapGestureRecognizer;
@property (retain, nonatomic) PHImportSource *importSource;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (unsigned short)defaultThumbnailImageFormat;
+ (id)totalSizeStringForItems:(id)items;

/* instance methods */
- (void)viewSafeAreaInsetsDidChange;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)kind atIndexPath:(id)path;
- (_Bool)collectionView:(id)view shouldSelectItemAtIndexPath:(id)path;
- (long long)collectionView:(id)view numberOfItemsInSection:(long long)section;
- (_Bool)gestureRecognizerShouldBegin:(id)begin;
- (long long)numberOfSectionsInCollectionView:(id)view;
- (void)collectionView:(id)view didEndDisplayingCell:(id)cell forItemAtIndexPath:(id)path;
- (void)uninstallGestureRecognizers;
- (void)scrollViewWillBeginDragging:(id)dragging;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)orientation;
- (struct PXSimpleIndexPath { long long x0; long long x1; long long x2; long long x3; })swipeSelectionManager:(id)manager itemIndexPathClosestAboveLocation:(struct CGPoint { double x0; double x1; })location;
- (id)collectionView:(id)view viewForSupplementaryElementOfKind:(id)kind atIndexPath:(id)path;
- (void)installGestureRecognizers;
- (unsigned long long)routingOptionsForDestination:(id)destination;
- (void)settings:(id)settings changedValueForKey:(id)key;
- (void)reloadData;
- (void)viewWillAppear:(_Bool)appear;
- (id)collectionView:(id)view cellForItemAtIndexPath:(id)path;
- (struct PXSimpleIndexPath { long long x0; long long x1; long long x2; long long x3; })swipeSelectionManager:(id)manager itemIndexPathAtLocation:(struct CGPoint { double x0; double x1; })location;
- (void)viewWillLayoutSubviews;
- (void)paste:(id)paste;
- (_Bool)isEmpty;
- (void)collectionView:(id)view willDisplayCell:(id)cell forItemAtIndexPath:(id)path;
- (void)headerViewDidPressActionButton:(id)button inHeaderView:(id)view;
- (void)navigateToDestination:(id)destination options:(unsigned long long)options completionHandler:(id /* block */)handler;
- (_Bool)canDragOut;
- (void)dealloc;
- (_Bool)canPerformAction:(SEL)action withSender:(id)sender;
- (_Bool)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)recognizer;
- (void)_contentSizeCategoryDidChangeNotification:(id)notification;
- (_Bool)swipeSelectionManagerIsInMultiSelectMode:(id)mode;
- (struct CGSize { double x0; double x1; })collectionView:(id)view layout:(id)layout referenceSizeForHeaderInSection:(long long)section;
- (_Bool)scrollViewShouldScrollToTop:(id)top;
- (void)scrollViewDidEndScrollingAnimation:(id)animation;
- (id)contextMenuInteraction:(id)interaction configurationForMenuAtLocation:(struct CGPoint { double x0; double x1; })location;
- (_Bool)isBusy;
- (void)observable:(id)observable didChange:(unsigned long long)change context:(void *)context;
- (void)viewDidLayoutSubviews;
- (void)delete:(id)_delete;
- (void)viewDidAppear:(_Bool)appear;
- (void)scrollViewDidScroll:(id)scroll;
- (struct PXSimpleIndexPath { long long x0; long long x1; long long x2; long long x3; })swipeSelectionManager:(id)manager itemIndexPathClosestLeadingLocation:(struct CGPoint { double x0; double x1; })location;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })size withTransitionCoordinator:(id)coordinator;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)handleLongPressGesture:(id)gesture;
- (void)_updateLayoutMetrics;
- (id)_gridLayout;
- (void)_setSpec:(id)spec;
- (long long)_titleViewVerticalSizeClassForExtendedTraitCollection:(id)collection;
- (struct CGSize { double x0; double x1; })gridItemSize;
- (void)handleNewDataSource:(id)source;
- (void)importController:(id)controller didCompleteImportWithImportSession:(id)session results:(id)results completion:(id /* block */)completion;
- (void)importController:(id)controller didLoadAssets:(id)assets exceptions:(id)exceptions;
- (id)px_navigationDestination;
- (_Bool)swipeSelectionManager:(id)manager shouldBeginSelectionAtLocation:(struct CGPoint { double x0; double x1; })location;
- (_Bool)isViewAppearing;
- (void)_beginImport;
- (void)_beginUninterruptibleOperation;
- (id)_bestReferenceItemIndexPath;
- (void)_cancelAlerts;
- (id)_createSubtitleText;
- (void)_deleteItems:(id)items;
- (void)_deselectCell:(id)cell;
- (void)_dismissPopupsAnimated:(_Bool)animated;
- (void)_endImport;
- (void)_endUninterruptibleOperation;
- (void)_getDataForVisualSection:(long long)section hasActionButton:(_Bool *)button title:(id *)title startDate:(id *)date endDate:(id *)date;
- (void)_importControllerDidEndAction;
- (void)_importControllerWillBeginAction;
- (void)_invalidateCachedViewSizeTransitionContext;
- (_Bool)_isItemVisibleAtIndex:(id)index;
- (void)_navigateToPhotoAtIndexPath:(id)path animated:(_Bool)animated interactive:(_Bool)interactive;
- (id)_newGridLayoutFromSpec:(id)spec;
- (void)_selectCell:(id)cell;
- (void)_setCachedViewSizeTransitionContext:(id)context;
- (void)_setCachedViewSizeTransitionContextSize:(struct CGSize { double x0; double x1; })size;
- (void)_setCollectionViewLayoutReferenceWidth:(double)width;
- (void)_setCollectionViewSafeAreaInsets:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })insets;
- (void)_setPendingViewSizeTransitionContext:(id)context;
- (void)_updateBackdropGroupNameForHeaderView:(id)view;
- (void)_updateCell:(id)cell atIndex:(id)index;
- (void)_updateContentOffsetForPendingViewSizeTransition;
- (void)_updateItemViewAtIndex:(id)index;
- (void)_updateToolbarAnimated:(_Bool)animated;
- (void)actionCoordinator:(id)coordinator didCompleteWithImportSession:(id)session results:(id)results;
- (void)actionCoordinatorDidBeginDelete:(id)_delete;
- (void)actionCoordinatorDidBeginImport:(id)import;
- (void)actionCoordinatorDidCancelImport:(id)import;
- (void)actionCoordinatorDidEndDelete:(id)_delete;
- (void)actionCoordinatorWillBeginDelete:(id)_delete;
- (void)actionCoordinatorWillBeginImport:(id)import;
- (_Bool)anyAlreadyImportedItemsAreSelected;
- (_Bool)areAllItemsSelectedInAssetCollection:(id)collection;
- (_Bool)canBeginDoubleTapGesture:(id)gesture;
- (_Bool)canBeginSwipeSelectionAtScrollViewLocation:(struct CGPoint { double x0; double x1; })location;
- (_Bool)compactLayoutMode;
- (void)configureCollectionViewGridLayout:(id)layout;
- (void)configureSupplementaryView:(id)view ofKind:(id)kind forIndexPath:(id)path;
- (long long)contentFillModeForImportCell:(id)cell;
- (id)deleteButtonItem;
- (void)disableSwipeSelection;
- (void)enableSwipeSelection;
- (void)getEmptyPlaceholderViewTitle:(id *)title message:(id *)message buttonTitle:(id *)title buttonAction:(id /* block */ *)action;
- (void)handleDoubleTapGesture:(id)gesture;
- (void)handleImportCompleteAlertResponse:(struct __CFUserNotification *)response flags:(unsigned long long)flags;
- (void)handleTapGesture:(id)gesture;
- (void)handleTouchEvent:(long long)event forCell:(id)cell;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })imageRectFromPhotoView:(id)view;
- (void)importCell:(id)cell didRequestCancellationOfThumbnailRequestWithID:(long long)id;
- (long long)importCell:(id)cell requestImageForImportItem:(id)item ofSize:(unsigned long long)size completion:(id /* block */)completion;
- (void)importControllerProgressDidChange:(id)change;
- (id)importDestinationForActionCoordinator:(id)coordinator;
- (_Bool)importSectionedGridLayout:(id)layout shouldEmphasizeSection:(unsigned long long)section;
- (_Bool)importSourceIsAppleDevice;
- (id)initWithSpec:(id)spec photoLibrary:(id)library;
- (unsigned int)initialEdge;
- (_Bool)isContentViewInSyncWithModel;
- (_Bool)isImporting;
- (_Bool)isPreheatingEnabled;
- (_Bool)isTransitioningToNewSize;
- (void)navigateToRectEdge:(unsigned int)edge animated:(_Bool)animated;
- (id)newGridLayout;
- (void)notifyUserOfImportCompletionIfNeededWithImportSession:(id)session results:(id)results;
- (id)oneUpViewControllerForItemAtIndexPath:(id)path;
- (void)presentOneUpViewController:(id)controller animated:(_Bool)animated interactive:(_Bool)interactive;
- (_Bool)sectionHeadersCoverLocation:(struct CGPoint { double x0; double x1; })location;
- (double)sectionedGridLayout:(id)layout accessibilitySectionHeaderHeightForVisualSection:(long long)section;
- (double)sectionedGridLayout:(id)layout aspectRatioForItemAtIndexPath:(id)path;
- (double)sectionedGridLayout:(id)layout sectionHeaderHeightForVisualSection:(long long)section;
- (id)sectionedGridLayoutAnchorItemForAdjustingContentOffset:(id)offset;
- (void)selectAllSelectableItems;
- (struct PXSimpleIndexPath { long long x0; long long x1; long long x2; long long x3; })selectionIndexPathForItem:(id)item;
- (void)setAllItemsSelected:(_Bool)selected inAssetCollection:(id)collection;
- (void)stayScrolledToBottomIfAtBottomAfterDrag:(id)drag;
- (void)stopImport:(id)import;
- (void)toggleAlreadyImportedExpansion;
- (void)transitionFromDataSource:(id)source toDataSource:(id)source animated:(_Bool)animated completionHandler:(id /* block */)handler;
- (void)updateAlreadyImportedCollapseStatus;
- (void)updateAlreadyImportedHeaderIfVisible;
- (void)updateDataSourceManagerFilters;
- (void)updateHeaderView:(id)view forAlreadyImportedAssetCollection:(id)collection;
- (void)updateHeaderView:(id)view forAssetCollection:(id)collection;
- (void)updateInterfaceForModelReloadAnimated:(_Bool)animated;
- (void)updateNavigationBarAnimated:(_Bool)animated;
- (_Bool)updateSpec;
- (_Bool)wantsPlaceholderView;

@end

#endif /* PUImportViewController_h */
