//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 349.502.0.0.0
//
#ifndef PHASESharedRoot_h
#define PHASESharedRoot_h
@import Foundation;

#include "PHASEObject.h"

@class AVAudioSession;

@interface PHASESharedRoot : PHASEObject {
    /* instance variables */
    struct UniqueObjectId { unsigned long long mStorage[2]; } _sessionUUID;
}

@property (readonly) AVAudioSession *session;

/* instance methods */
- (id)initWithEngine:(id)engine;
- (void)dealloc;
- (void)setTransform:(struct { x0[4]; })transform;
- (id)initWithEngine:(id)engine entityType:(unsigned int)type shapes:(id)shapes;
- (id)initWithEngine:(id)engine session:(id)session sessionUUID:(id)uuid;
- (id)initWithEngine:(id)engine sessionUUID:(id)uuid;

@end

#endif /* PHASESharedRoot_h */
