//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4025.610.1.0.0
//
#ifndef _TtC7MusicUI23ConcertsLocationManager_h
#define _TtC7MusicUI23ConcertsLocationManager_h
@import Foundation;

@class JetEngine.AsyncEvent _$syt, MusicUI.ConcertsLocation ?, Swift.Bool, _$sSa -> MusicUI.ConcertsLocation, _$sScTyyt Swift.Never ?, _$sSo17CLLocationManagerCSg, _$sSo25NSUbiquitousKeyValueStoreCSg, _TtCs12_SwiftObject, s.Logger;

@interface _TtC7MusicUI23ConcertsLocationManager : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    JetEngine.AsyncEvent _$syt concertsLocationDidChange;
    MusicUI.ConcertsLocation ? _preferredLocation;
    MusicUI.ConcertsLocation ? _deviceLocation;
    _$sSa -> MusicUI.ConcertsLocation _recents;
    _$sSo17CLLocationManagerCSg $__lazy_storage_$_coreLocationManager;
    _$sScTyyt Swift.Never ? coreLocationTask;
    _$sSo25NSUbiquitousKeyValueStoreCSg $__lazy_storage_$_cloudKitStore;
    _$sScTyyt Swift.Never ? cloudKitTask;
    Swift.Bool skipCloudKitSync;
    out s.Logger logger;
    bycopy unsigned int _$observationRegistrar:0;
}

@end

#endif /* _TtC7MusicUI23ConcertsLocationManager_h */
