//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 20.9.0.0.0
//
#ifndef RSGeometryMeta_h
#define RSGeometryMeta_h
@import Foundation;

@interface RSGeometryMeta : NSObject <NSCopying> {
    /* instance variables */
    _Bool _isCenterScaleUpdated;
    float _pixelSize;
    float _floorHeight;
    float _ceilingHeight;
    float _supportHeight;
    int _imageSize;
    int _zSlice;
    float _visualFloorHeight;
    float _visualCeilingHeight;
     _floorCeilingCount;
     _center;
     _scale;
     _shift;
}

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (_Bool)isEqual:(id)equal;

@end

#endif /* RSGeometryMeta_h */
