//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 6200.6.8.2.1
//
#ifndef HKIngredientSearchResult_h
#define HKIngredientSearchResult_h
@import Foundation;

@interface HKIngredientSearchResult : NSObject

@property (readonly, copy, nonatomic) NSString *ingredientId;
@property (readonly, copy, nonatomic) NSString *ingredientName;
@property (readonly, copy, nonatomic) NSString *strengthQuantity;
@property (readonly, copy, nonatomic) NSString *strengthUnit;

/* instance methods */
- (id)dictionaryRepresentation;
- (id)initWithIngredientId:(id)id ingredientName:(id)name strengthQuantity:(id)quantity strengthUnit:(id)unit;

@end

#endif /* HKIngredientSearchResult_h */
