//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 156.0.0.0.0
//
#ifndef _BNPanGestureServiceProxy_h
#define _BNPanGestureServiceProxy_h
@import Foundation;

#include "BNPanGestureProxyAction.h"
#include "BNPanGestureProxyDelegate-Protocol.h"
#include "BNPanGestureProxyPrivate-Protocol.h"

@interface _BNPanGestureServiceProxy : NSObject <BNPanGestureProxyPrivate>

@property (retain, nonatomic) BNPanGestureProxyAction *activePanGestureProxyAction;
@property (weak, nonatomic) id <BNPanGestureProxyDelegate> delegate;
@property (readonly, nonatomic) long long state;
@property (copy, nonatomic) id /* block */ actionHandler;
@property (readonly, nonatomic) _Bool didCrossDefaultThreshold;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (struct CGPoint { double x0; double x1; })locationInCoordinateSpace:(id)space;
- (void)sendAction;
- (struct CGPoint { double x0; double x1; })translationInCoordinateSpace:(id)space;
- (struct CGPoint { double x0; double x1; })velocityInCoordinateSpace:(id)space;
- (struct CGPoint { double x0; double x1; })visualTranslationInCoordinateSpace:(id)space;
- (id)_activePanGestureProxyAction;
- (void)_setActivePanGestureProxyAction:(id)action;

@end

#endif /* _BNPanGestureServiceProxy_h */
