//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 308.0.3.0.0
//
#ifndef MODefaultOnboardingManagerDelegate_h
#define MODefaultOnboardingManagerDelegate_h
@import Foundation;

#include "MOOnboardingManagerDelegate-Protocol.h"

@interface MODefaultOnboardingManagerDelegate : NSObject <MOOnboardingManagerDelegate>

/* instance methods */
- (void)onOnboardingFlowCompletionChange:(unsigned long long)change isComplete:(_Bool)complete;

@end

#endif /* MODefaultOnboardingManagerDelegate_h */
