//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 665.120.8.0.0
//
#ifndef CSPlayerResponseItemWrapper_h
#define CSPlayerResponseItemWrapper_h
@import Foundation;

@class MPCPlayerResponseItem;

@interface CSPlayerResponseItemWrapper : NSObject

@property (readonly, nonatomic) MPCPlayerResponseItem *responseItem;
@property (readonly, nonatomic) _Bool addSongsItem;

/* instance methods */
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)initWithResponseItem:(id)item;
- (id)initAddSongsItem;
- (_Bool)isAddSongsItem;

@end

#endif /* CSPlayerResponseItemWrapper_h */
