//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 251.35.2.9.11
//
#ifndef UIViewController_MapsUILayoutMargins_h
#define UIViewController_MapsUILayoutMargins_h
@import Foundation;

@interface UIViewController (MapsUILayoutMargins)

/* instance methods */
- (void)_mapsui_resetViewLayoutMargins;
- (void)_mapsui_resetViewLayoutMarginsWithPreservesSuperview:(_Bool)superview;
- (void)_mapsui_resetViewLayoutMarginsWithPreservesSuperview:(_Bool)superview insetsFromSafeArea:(_Bool)area;
- (void)_mapsui_resetViewLayoutMarginsWithPreservesSuperview:(_Bool)superview insetsFromSafeArea:(_Bool)area respectsSystemMinimum:(_Bool)minimum;
- (id)_mapsui_viewLayoutMarginsDescription;

@end

#endif /* UIViewController_MapsUILayoutMargins_h */
