//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1418.6.20.0.0
//
#ifndef HMDDefaultOPACKTransformer_h
#define HMDDefaultOPACKTransformer_h
@import Foundation;

#include "HMDOPACKTransformer.h"

@interface HMDDefaultOPACKTransformer : HMDOPACKTransformer

/* class methods */
+ (Class)valueClass;
+ (id)OPACKFromValue:(id)value error:(id *)error;
+ (id)valueFromOPACK:(id)opack error:(id *)error;
+ (id)description;

@end

#endif /* HMDDefaultOPACKTransformer_h */
