//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 664.5.28.100.0
//
#ifndef CHSMutableControlConfigurationItem_h
#define CHSMutableControlConfigurationItem_h
@import Foundation;

#include "CHSControlConfigurationItem.h"

@interface CHSMutableControlConfigurationItem : CHSControlConfigurationItem

@property (nonatomic) unsigned long long pushPolicy;
@property (nonatomic) _Bool canAppearInSecureEnvironment;
@property (nonatomic) _Bool supportsLowLuminance;
@property (nonatomic) unsigned long long supportedColorSchemes;
@property (nonatomic) long long location;

/* instance methods */
- (id)copyWithZone:(void *)zone;
- (id)init;
- (id)initWithUniqueIdentifier:(id)identifier controlIdentity:(id)identity;
- (id)initWithUniqueIdentifier:(id)identifier controlIdentity:(id)identity location:(long long)location;

@end

#endif /* CHSMutableControlConfigurationItem_h */
