//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1969.600.51.2.5
//
#ifndef IDSMPPublicDeviceIdentityContainer_h
#define IDSMPPublicDeviceIdentityContainer_h
@import Foundation;

#include "IDSMPPublicLegacyIdentity.h"
#include "IDSNGMPublicDeviceIdentity.h"

@protocol IDSSyncQueue;

@interface IDSMPPublicDeviceIdentityContainer : NSObject

@property (retain, nonatomic) id <IDSSyncQueue> queue;
@property (readonly, nonatomic) IDSNGMPublicDeviceIdentity *ngmPublicDeviceIdentity;
@property (readonly, nonatomic) IDSMPPublicLegacyIdentity *legacyPublicIdentity;
@property (readonly, nonatomic) NSNumber *ngmVersion;

/* class methods */
+ (id)identityWithLegacyPublicIdentity:(id)identity ngmPublicDeviceIdentity:(id)identity ngmVersion:(id)version error:(id *)error;
+ (id)identityWithDataRepresentation:(id)representation error:(id *)error;

/* instance methods */
- (id)dataRepresentationWithError:(id *)error;
- (unsigned long long)hash;
- (id)legacySealMessage:(id)message withEncryptedAttributes:(id)attributes signedByFullIdentity:(id)identity usingIdentitiesWithIdentifier:(id)identifier error:(id *)error;
- (id)_ngmSealMessage:(id)message authenticatedData:(id)data messageType:(long long)type guid:(id)guid sendingURI:(id)uri sendingPushToken:(id)token receivingURI:(id)uri receivingPushToken:(id)token forceSizeOptimizations:(_Bool)optimizations resetState:(_Bool)state withEncryptedAttributes:(id)attributes signedWithFullIdentity:(id)identity usedIdentityWithIdentifier:(id *)identifier error:(id *)error additionalResult:(id *)result;
- (id)sealMessage:(id)message authenticatedData:(id)data messageType:(long long)type guid:(id)guid sendingURI:(id)uri sendingPushToken:(id)token receivingURI:(id)uri receivingPushToken:(id)token forceSizeOptimizations:(_Bool)optimizations resetState:(_Bool)state withEncryptedAttributes:(id)attributes signedByFullIdentity:(id)identity usedIdentityWithIdentifier:(id *)identifier error:(id *)error additionalResult:(id *)result;
- (_Bool)isValidNGMSignature:(id)ngmsignature forMessage:(id)message forType:(long long)type error:(id *)error;
- (void)accessNGMIdentityOnQueue:(id /* block */)queue;
- (id)debugDescription;
- (_Bool)markForStateResetWithOurURI:(id)uri ourPushToken:(id)token ourSigningIdentity:(id)identity theirURI:(id)uri theirPushToken:(id)token;
- (id)description;
- (id)_legacySealMessage:(id)message signedWithFullIdentity:(id)identity error:(id *)error;
- (id)initWithLegacyPublicIdentity:(id)identity ngmPublicDeviceIdentity:(id)identity ngmVersion:(id)version;
- (id)sealPaddyMessage:(id)message sendingURI:(id)uri sendingPushToken:(id)token receivingURI:(id)uri receivingPushToken:(id)token signedByFullIdentity:(id)identity error:(id *)error;
- (_Bool)isEqual:(id)equal;

@end

#endif /* IDSMPPublicDeviceIdentityContainer_h */
