//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef PLDisambiguation_h
#define PLDisambiguation_h
@import Foundation;

@interface PLDisambiguation : NSObject

@property (readonly, nonatomic) NSString *queryTerm;
@property (readonly, nonatomic) NSIndexSet *indexingCategories;
@property (readonly, nonatomic) unsigned long long disambiguationType;
@property (readonly, nonatomic) unsigned long long maxNumberOfResults;
@property (readonly, nonatomic) unsigned long long matchOptions;

/* instance methods */
- (id)description;
- (id)initWithQueryTerm:(id)term disambiguationType:(unsigned long long)type indexingCategories:(id)categories maxNumberOfResults:(unsigned long long)results matchOptions:(unsigned long long)options;

@end

#endif /* PLDisambiguation_h */
