//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3860.600.12.0.0
//
#ifndef __NSURLSessionStatistics_h
#define __NSURLSessionStatistics_h
@import Foundation;

@interface __NSURLSessionStatistics : NSObject {
    /* instance variables */
    void * report;
}

@property (readonly, nonatomic) NSMutableDictionary *dictionaryReport;
@property (readonly, nonatomic) NSUUID *nwActivity;
@property (readonly, nonatomic) NSUUID *taskUUID;
@property (readonly, nonatomic) NSArray *connectionUUIDS;
@property (retain) NSUUID *externallyVisibleNwActivity;
@property (retain) NSArray *externallyVisibleConnectionUUIDs;

/* class methods */
+ (struct { unsigned char x0[16]; unsigned char x1[16]; unsigned long long x2; unsigned long long x3; long long x4; long long x5; long long x6; unsigned int x7; unsigned short x8; unsigned short x9; unsigned short x10; unsigned int x11:4; unsigned int x12:1; unsigned int x13:1; unsigned int x14:1; unsigned int x15:1; unsigned long long x16:40; struct { unsigned char x170[16]; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned short x8; unsigned int x9:4; unsigned int x10:4; unsigned int x11:4; unsigned int x12:4; unsigned int x13:4; unsigned int x14:4; unsigned int x15:1; unsigned int x16:1; unsigned int x17:1; unsigned int x18:1; unsigned int x19:1; unsigned int x20:1; unsigned int x21:1; unsigned int x22:1; unsigned int x23:1; unsigned int x24:15; } x[0]; } *)createCFNetworkTaskMetrics_s:(id)metrics_s;
+ (void)reportMetricsToSymptoms:(id)symptoms;

/* instance methods */
- (void)dealloc;
- (id)initWithJSONData:(id)jsondata;
- (id)initWithCFNetworkReport:(void *)report length:(long long)length;

@end

#endif /* __NSURLSessionStatistics_h */
