//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3191.35.0.0.0
//
#ifndef AXTwiceCompanionAirplayReceiverDelegate_Protocol_h
#define AXTwiceCompanionAirplayReceiverDelegate_Protocol_h
@import Foundation;

@protocol AXTwiceCompanionAirplayReceiverDelegate <NSObject>

@required

/* required instance methods */
- (void)airplayDidStartStreamingWithMirroringLayer:(id)layer;
- (void)airplayDidStopStreaming;

@optional

@end

#endif /* AXTwiceCompanionAirplayReceiverDelegate_Protocol_h */
