//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3520.28.1.0.0
//
#ifndef SVXSpeechInstrumentationUtilities_h
#define SVXSpeechInstrumentationUtilities_h
@import Foundation;

@interface SVXSpeechInstrumentationUtilities : NSObject

/* instance methods */
- (void)emitTextToSpeechRequestReceived:(id)received instrumentMetrics:(id)metrics;

@end

#endif /* SVXSpeechInstrumentationUtilities_h */
