//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1015.100.16.0.0
//
#ifndef RBSAppNapPreventLowPriorityCPUGrant_RBProcessState_h
#define RBSAppNapPreventLowPriorityCPUGrant_RBProcessState_h
@import Foundation;

#include "RBInheritanceCollection.h"

@class RBSProcessIdentity;

@interface RBSAppNapPreventLowPriorityCPUGrant (RBProcessState)

/* instance methods */
- (void)applyToProcessState:(id)state attributePath:(unsigned long long)path context:(id)context;

@end

#endif /* RBSAppNapPreventLowPriorityCPUGrant_RBProcessState_h */
