//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2005.120.18.0.0
//
#ifndef LACPreboardAMFIHelper_h
#define LACPreboardAMFIHelper_h
@import Foundation;

@interface LACPreboardAMFIHelper : NSObject

/* class methods */
+ (long long)useCase;
+ (unsigned int)_armedSecurityBootMode;
+ (unsigned int)_securityBootMode;
+ (long long)_useCaseFromBootMode:(unsigned int)mode;
+ (long long)armedUseCase;
+ (void)completeCurrentBootModeWithSuccess:(_Bool)success;
+ (id)getUPPProfile;
+ (_Bool)installProfileWithUUID:(id)uuid signature:(id)signature error:(id *)error;

@end

#endif /* LACPreboardAMFIHelper_h */
