//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 486.0.0.0.0
//
#ifndef TSTCellUIDList_h
#define TSTCellUIDList_h
@import Foundation;

#include "TSTCellUIDLookupListWrapper.h"

@class TSKUIDStruct;
@protocol OS_dispatch_queue;

@interface TSTCellUIDList : NSObject <NSCopying> {
    /* instance variables */
    struct TSKUIDStructVectorTemplate<TSKUIDStruct> { struct TSKUIDStruct *__begin_; struct TSKUIDStruct *__end_; struct { struct TSKUIDStruct *__cap_; } x2; } _rowIdList;
    struct TSKUIDStructVectorTemplate<TSKUIDStruct> { struct TSKUIDStruct *__begin_; struct TSKUIDStruct *__end_; struct { struct TSKUIDStruct *__cap_; } x2; } _columnIdList;
    struct vector<int, std::allocator<int>> { int *__begin_; int *__end_; struct { int *__cap_; } x2; } _rowUIDIndexList;
    struct vector<int, std::allocator<int>> { int *__begin_; int *__end_; struct { int *__cap_; } x2; } _columnUIDIndexList;
    TSTCellUIDLookupListWrapper *_uncompressedCellUIDs;
}

@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (readonly, nonatomic) unsigned long long compressedSize;

/* class methods */
+ (id)cellUIDList;
+ (id)cellUIDListFromRange:(const void *)range;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)count;
- (id)iterator;
- (id)init;
- (void)compress;
- (const void *)rowUIDs;
- (void)addCellRegion:(id)region withColumnUIDs:(const void *)uids rowUIDs:(const void *)uids;
- (void)addCellUID:(const struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } *)uid;
- (void)addCellUIDRanges:(const void *)uidranges;
- (void)addCellUIDs:(void *)uids;
- (const void *)columnUIDs;
- (void)compressUIDIndexListFrom:(const void *)from withUIDCount:(unsigned long long)uidcount to:(void *)to;
- (const void *)compressedColumnIndexes;
- (const void *)compressedColumnUIDs;
- (const void *)compressedRowIndexes;
- (const void *)compressedRowUIDs;
- (unsigned long long)computeValidCount;
- (void)enumerateCellUIDsUsingBlock:(id /* block */)block;
- (id)initFromMessage:(const void *)message unarchiver:(id)unarchiver;
- (void)p_compressUID:(const struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } *)uid index:(unsigned long long)index UIDtoIndexMap:(void *)map UIDs:(void *)uids compressedIndexes:(void *)indexes lastSameUIDIndex:(void *)uidindex;
- (id)pruneCellUIDListAgainstTable:(id)table behavior:(unsigned long long)behavior;
- (id)pruneCellUIDListAgainstTable:(id)table behavior:(unsigned long long)behavior usingBlock:(id /* block */)block;
- (void)reserve:(unsigned long long)reserve;
- (void)saveToMessage:(void *)message archiver:(id)archiver;
- (void)setCompressedColumnIndexes:(const void *)indexes;
- (id)uncompressedCellUIDs;

@end

#endif /* TSTCellUIDList_h */
