//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 5812.122.1.0.0
//
#ifndef NWConcrete_nw_resolver_config_h
#define NWConcrete_nw_resolver_config_h
@import Foundation;

#include "OS_nw_fd_wrapper-Protocol.h"
#include "OS_nw_resolver_config-Protocol.h"
#include "OS_xpc_object-Protocol.h"

@protocol OS_dispatch_source;

@interface NWConcrete_nw_resolver_config : NSObject <OS_nw_resolver_config> {
    /* instance variables */
    struct retained_ptr<NSObject<OS_xpc_object> *> { NSObject<OS_xpc_object> *m_obj; unsigned int m_should_release:1; unsigned int __pad_bits:7; unsigned char __pad_bytes[7]; } dictionary;
    unsigned char identifier[16];
    struct retained_ptr<NSObject<OS_dispatch_source> *> { NSObject<OS_dispatch_source> *m_obj; unsigned int m_should_release:1; unsigned int __pad_bits:7; unsigned char __pad_bytes[7]; } kernel_event_source;
    struct retained_ptr<NSObject<OS_nw_fd_wrapper> *> { NSObject<OS_nw_fd_wrapper> *m_obj; unsigned int m_should_release:1; unsigned int __pad_bits:7; unsigned char __pad_bytes[7]; } kernel_event_wrapper;
    struct retained_ptr<NSObject<OS_nw_fd_wrapper> *> { NSObject<OS_nw_fd_wrapper> *m_obj; unsigned int m_should_release:1; unsigned int __pad_bits:7; unsigned char __pad_bytes[7]; } agent_fd;
    struct unfair_mutex { struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } m_mutex; } lock;
    unsigned int generation;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (id)init;

@end

#endif /* NWConcrete_nw_resolver_config_h */
