//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4015.5.11.0.0
//
#ifndef _INCodableScalarAttributeRelationshipStringValueTransformer_h
#define _INCodableScalarAttributeRelationshipStringValueTransformer_h
@import Foundation;

#include "_INCodableAttributeRelationshipValueTransformer.h"

@interface _INCodableScalarAttributeRelationshipStringValueTransformer : _INCodableAttributeRelationshipValueTransformer

/* class methods */
+ (Class)transformedValueClass;

/* instance methods */
- (id)transformedValue:(id)value;

@end

#endif /* _INCodableScalarAttributeRelationshipStringValueTransformer_h */
