//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4015.5.11.0.0
//
#ifndef _INPBCancelWorkoutIntent_h
#define _INPBCancelWorkoutIntent_h
@import Foundation;

#include "_INPBCancelWorkoutIntent-Protocol.h"
#include "_INPBDataString.h"
#include "_INPBIntentMetadata.h"

@class PBCodable;

@interface _INPBCancelWorkoutIntent : PBCodable <_INPBCancelWorkoutIntent, NSSecureCoding, NSCopying> {
    /* instance variables */
    struct  _has;
}

@property (retain, nonatomic) _INPBIntentMetadata *intentMetadata;
@property (readonly, nonatomic) _Bool hasIntentMetadata;
@property (retain, nonatomic) _INPBDataString *workoutName;
@property (readonly, nonatomic) _Bool hasWorkoutName;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)writeTo:(id)to;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;

@end

#endif /* _INPBCancelWorkoutIntent_h */
