//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 6200.6.8.2.1
//
#ifndef HKHorizontalTimePeriodDataSource_h
#define HKHorizontalTimePeriodDataSource_h
@import Foundation;

#include "HKHealthQueryChartCacheDataSource.h"

@class HKSampleType;

@interface HKHorizontalTimePeriodDataSource : HKHealthQueryChartCacheDataSource

@property (retain, nonatomic) HKSampleType *sampleType;
@property (copy, nonatomic) id /* block */ userInfoCreationBlock;
@property (retain, nonatomic) NSArray *valueOrder;

/* instance methods */
- (id)queryDescription;
- (id)_chartPointsWithDateIntervalsByValue:(id)value sourceTimeZone:(id)zone;
- (id)_codableQueryDataWithSamples:(id)samples;
- (id)_dateIntervalsByValueWithCodableQueryData:(id)data;
- (id)_organizeSamplesByValueAndDateInterval:(id)interval;
- (id)chartPointsFromQueryData:(id)data dataIsFromRemoteSource:(_Bool)source;
- (id /* block */)generateSharableQueryDataForRequest:(id)request healthStore:(id)store completionHandler:(id /* block */)handler;
- (id)queriesForRequest:(id)request completionHandler:(id /* block */)handler;
- (_Bool)supportsChartQueryDataGeneration;

@end

#endif /* HKHorizontalTimePeriodDataSource_h */
