//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 6200.6.8.2.1
//
#ifndef HKOnboardingSetupView_h
#define HKOnboardingSetupView_h
@import Foundation;

@class UIButton, UILabel, UIView;
@protocol HKOnboardingSetupViewDelegate;

@interface HKOnboardingSetupView : UIView

@property (retain, nonatomic) UIView *heroView;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UILabel *bodyLabel;
@property (retain, nonatomic) UIButton *onboardingButton;
@property (weak, nonatomic) id <HKOnboardingSetupViewDelegate> delegate;
@property (readonly, nonatomic) NSString *titleString;
@property (readonly, nonatomic) NSString *bodyString;
@property (readonly, nonatomic) NSString *buttonTitleString;
@property (readonly, nonatomic) long long accessibilityGroupID;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)_setUpConstraints;
- (void)_didTapOnboardingButton;
- (id)createHeroView;

@end

#endif /* HKOnboardingSetupView_h */
