//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1576.600.51.2.2
//
#ifndef FTStoredMessage_h
#define FTStoredMessage_h
@import Foundation;

@class NSManagedObject;

@interface FTStoredMessage : NSManagedObject // (Swift)

@property (nonatomic, readonly) NSString *description;
@property (nonatomic, copy) NSUUID *callUUID;
@property (nonatomic, copy) NSUUID *conversationID;
@property (nonatomic, copy) NSDate *dateCreated;
@property (nonatomic, copy) NSDate *dateDeleted;
@property (nonatomic, copy) NSDate *dateModified;
@property (nonatomic) double duration;
@property (nonatomic, copy) NSString *fileType;
@property (nonatomic, copy) NSString *from;
@property (nonatomic) _Bool isRead;
@property (nonatomic) _Bool isRTT;
@property (nonatomic) _Bool isSensitive;
@property (nonatomic) short mailboxType;
@property (nonatomic, copy) NSData *messageFile;
@property (nonatomic, copy) NSData *messageThumbnail;
@property (nonatomic) short messageType;
@property (nonatomic, copy) NSString *provider;
@property (nonatomic, copy) NSString *quality;
@property (nonatomic, copy) NSString *recipient;
@property (nonatomic, copy) NSUUID *recordUUID;
@property (nonatomic, copy) NSUUID *reminderUUID;
@property (nonatomic, copy) NSString *simID;
@property (nonatomic, copy) NSData *summaryData;
@property (nonatomic, copy) NSString *thumbnailType;
@property (nonatomic, copy) NSData *transcript;
@property (nonatomic, copy) NSData *transcriptData;
@property (nonatomic) short transcriptionStatus;
@property (nonatomic, copy) NSString *transcriptType;

/* instance methods */
- (id)initWithEntity:(id)entity insertIntoManagedObjectContext:(id)context;

@end

#endif /* FTStoredMessage_h */
