//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3864.600.51.2.1
//
#ifndef EDDonateGenericAttributesForAppIntentsUpgradeStep_h
#define EDDonateGenericAttributesForAppIntentsUpgradeStep_h
@import Foundation;

#include "EDTableUpgradeStep-Protocol.h"

@interface EDDonateGenericAttributesForAppIntentsUpgradeStep : NSObject <EDTableUpgradeStep>

/* class methods */
+ (_Bool)runWithConnection:(id)connection error:(id *)error;

/* instance methods */
- (id)init;

@end

#endif /* EDDonateGenericAttributesForAppIntentsUpgradeStep_h */
