//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.1.0.0
//
#ifndef PLUSSchemaPLUSSuggestion_h
#define PLUSSchemaPLUSSuggestion_h
@import Foundation;

#include "PLUSSchemaPLUSSuggestionMetadata.h"
#include "PLUSSchemaPLUSSuggestionValue.h"
#include "SISchemaInstrumentationMessage.h"

@interface PLUSSchemaPLUSSuggestion : SISchemaInstrumentationMessage

@property (retain, nonatomic) PLUSSchemaPLUSSuggestionMetadata *suggestionMetadata;
@property (nonatomic) _Bool hasSuggestionMetadata;
@property (retain, nonatomic) PLUSSchemaPLUSSuggestionValue *suggestionValue;
@property (nonatomic) _Bool hasSuggestionValue;
@property (readonly, nonatomic) NSData *jsonData;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (unsigned long long)hash;
- (id)applySensitiveConditionsPolicy:(id)policy;
- (void)writeTo:(id)to;
- (id)initWithJSON:(id)json;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:(id)dictionary;
- (id)dictionaryRepresentation;
- (_Bool)isEqual:(id)equal;
- (void)deleteSuggestionMetadata;
- (void)deleteSuggestionValue;

@end

#endif /* PLUSSchemaPLUSSuggestion_h */
