//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.1.0.0
//
#ifndef PSESchemaPSEMediaUserFollowupAction_h
#define PSESchemaPSEMediaUserFollowupAction_h
@import Foundation;

#include "PSESchemaPSEMediaEntitySimilarity.h"
#include "SISchemaInstrumentationMessage.h"

@interface PSESchemaPSEMediaUserFollowupAction : SISchemaInstrumentationMessage {
    /* instance variables */
    struct { unsigned int state:1; unsigned int mediaContentDurationBucket:1; unsigned int isSameAppUsed:1; unsigned int isFirstPartyAppUsedForFollowup:1; unsigned int isAirPlay:1; unsigned int mediaType:1; unsigned int isSubscriber:1; } _has;
}

@property (nonatomic) int state;
@property (nonatomic) _Bool hasState;
@property (nonatomic) int mediaContentDurationBucket;
@property (nonatomic) _Bool hasMediaContentDurationBucket;
@property (nonatomic) _Bool isSameAppUsed;
@property (nonatomic) _Bool hasIsSameAppUsed;
@property (nonatomic) _Bool isFirstPartyAppUsedForFollowup;
@property (nonatomic) _Bool hasIsFirstPartyAppUsedForFollowup;
@property (retain, nonatomic) PSESchemaPSEMediaEntitySimilarity *mediaEntitySimilarity;
@property (nonatomic) _Bool hasMediaEntitySimilarity;
@property (nonatomic) _Bool isAirPlay;
@property (nonatomic) _Bool hasIsAirPlay;
@property (nonatomic) int mediaType;
@property (nonatomic) _Bool hasMediaType;
@property (nonatomic) _Bool isSubscriber;
@property (nonatomic) _Bool hasIsSubscriber;
@property (readonly, nonatomic) NSData *jsonData;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (unsigned long long)hash;
- (id)applySensitiveConditionsPolicy:(id)policy;
- (void)writeTo:(id)to;
- (id)initWithJSON:(id)json;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:(id)dictionary;
- (id)dictionaryRepresentation;
- (_Bool)isEqual:(id)equal;
- (void)deleteIsAirPlay;
- (void)deleteMediaType;
- (void)deleteIsFirstPartyAppUsedForFollowup;
- (void)deleteIsSameAppUsed;
- (void)deleteIsSubscriber;
- (void)deleteMediaContentDurationBucket;
- (void)deleteMediaEntitySimilarity;
- (void)deleteState;

@end

#endif /* PSESchemaPSEMediaUserFollowupAction_h */
