//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 244.5.1.0.0
//
#ifndef TCSCallLog_h
#define TCSCallLog_h
@import Foundation;

@interface TCSCallLog : NSObject {
    /* instance variables */
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (retain, nonatomic) NSMutableDictionary *calls;
@property (retain, nonatomic) NSMutableOrderedSet *identifiers;

/* instance methods */
- (id)callWithUniqueProxyIdentifier:(id)identifier;
- (id)init;
- (void)_trimCache;
- (void)addCall:(id)call;

@end

#endif /* TCSCallLog_h */
