//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3864.600.51.2.1
//
#ifndef _TtC6MailUI14CSQueryBuilder_h
#define _TtC6MailUI14CSQueryBuilder_h
@import Foundation;

@class _$sSaySo11NSPredicateCG, _TtCs12_SwiftObject;

@interface _TtC6MailUI14CSQueryBuilder : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSaySo11NSPredicateCG predicates;
}

@end

#endif /* _TtC6MailUI14CSQueryBuilder_h */
