//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1418.6.20.0.0
//
#ifndef HMBLocalZoneProcessTuple_h
#define HMBLocalZoneProcessTuple_h
@import Foundation;

#include "HMBLocalSQLQueryTable.h"
#include "HMBLocalZoneProcessModelContext.h"
#include "HMBModel.h"

@class HMFObject;

@interface HMBLocalZoneProcessTuple : HMFObject

@property (readonly, nonatomic) HMBLocalZoneProcessModelContext *previousContext;
@property (readonly, nonatomic) HMBLocalZoneProcessModelContext *mergedContext;
@property (readonly, copy, nonatomic) HMBModel *updateModel;
@property (readonly, copy, nonatomic) HMBModel *outputModel;
@property (readonly, copy, nonatomic) NSNumber *outputBlockRow;
@property (readonly, nonatomic) unsigned long long recordRow;
@property (readonly, nonatomic) unsigned long long itemRow;
@property (readonly, nonatomic) NSData *externalID;
@property (readonly, nonatomic) NSUUID *modelSchema;
@property (readonly, nonatomic) NSString *modelType;
@property (readonly, nonatomic) HMBLocalSQLQueryTable *queryTable;
@property (readonly, nonatomic) NSArray *encodedQueryableColumns;

/* instance methods */
- (id)initWithPreviousContext:(id)context mergedContext:(id)context updateModel:(id)model outputModel:(id)model outputBlockRow:(id)row recordRow:(unsigned long long)row itemRow:(unsigned long long)row modelSchema:(id)schema modelType:(id)type externalID:(id)id queryTable:(id)table;

@end

#endif /* HMBLocalZoneProcessTuple_h */
