//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 212.120.3.0.0
//
#ifndef ASTConnectionRetrieveSelfServiceSuites_h
#define ASTConnectionRetrieveSelfServiceSuites_h
@import Foundation;

#include "ASTMaterializedConnection.h"

@interface ASTConnectionRetrieveSelfServiceSuites : ASTMaterializedConnection

@property (retain, nonatomic) NSString *configCode;

/* instance methods */
- (id)method;
- (id)endpoint;
- (id)parameters;
- (id)initWithConfigCode:(id)code;

@end

#endif /* ASTConnectionRetrieveSelfServiceSuites_h */
