//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 62.0.3.0.0
//
#ifndef ULMapItemGenerator_h
#define ULMapItemGenerator_h
@import Foundation;

@interface ULMapItemGenerator : NSObject

/* class methods */
+ (void)_generateParkingMapItemsWithBiomeEventStreamCarPlayConnected:(id)connected biomeEventStreamLocationSemantic:(id)semantic dbStore:(struct ULDatabaseStoreInterface { void * /* function */ *x0; } *)store task:(id)task startDate:(id)date;
+ (void)generateMapItemsWithEnvironment:(id)environment dbStore:(struct ULDatabaseStoreInterface { void * /* function */ *x0; } *)store task:(id)task;

@end

#endif /* ULMapItemGenerator_h */
