//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 585.120.2.0.0
//
#ifndef RMModelStatusServicesBackgroundTask_h
#define RMModelStatusServicesBackgroundTask_h
@import Foundation;

#include "RMModelStatusBase.h"
#include "RMModelStatusServicesBackgroundTask_Launchd.h"

@interface RMModelStatusServicesBackgroundTask : RMModelStatusBase

@property (copy, nonatomic) NSString *statusIdentifier;
@property (copy, nonatomic) NSNumber *statusRemoved;
@property (copy, nonatomic) NSString *statusCodeSignature;
@property (copy, nonatomic) NSNumber *statusUid;
@property (copy, nonatomic) NSString *statusPath;
@property (copy, nonatomic) NSString *statusState;
@property (copy, nonatomic) NSString *statusType;
@property (copy, nonatomic) RMModelStatusServicesBackgroundTask_Launchd *statusLaunchd;

/* class methods */
+ (id)allowedStatusKeys;
+ (id)buildRequiredOnlyWithIdentifier:(id)identifier uid:(id)uid path:(id)path state:(id)state type:(id)type;
+ (id)buildWithIdentifier:(id)identifier removed:(id)removed codeSignature:(id)signature uid:(id)uid path:(id)path state:(id)state type:(id)type launchd:(id)launchd;
+ (id)statusItemType;
+ (id)supportedOS;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isArrayValue;
- (_Bool)loadPayloadFromDictionary:(id)dictionary serializationType:(short)type error:(id *)error;
- (id)serializePayloadWithType:(short)type;

@end

#endif /* RMModelStatusServicesBackgroundTask_h */
