//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2952.120.8.0.0
//
#ifndef ICAttachmentBrickView_h
#define ICAttachmentBrickView_h
@import Foundation;

#include "ICAddAttachmentsManagerAttachmentInfo.h"
#include "ICSearchResultRegexMatchFinder.h"
#include "LPAudioPlayer-Protocol.h"
#include "LPLinkViewDelegate-Protocol.h"

@class ICAttachment, LPLinkView, NSLayoutConstraint, UIColor, UIView;

@interface ICAttachmentBrickView : UIView <LPLinkViewDelegate, LPAudioPlayer>

@property (retain, nonatomic) NSHashTable *audioPlayerClients;
@property (nonatomic) unsigned long long playerState;
@property (nonatomic) float playbackProgress;
@property (retain, nonatomic) LPLinkView *linkView;
@property (readonly, nonatomic) unsigned long long type;
@property (retain, nonatomic) NSLayoutConstraint *widthConstraint;
@property (retain, nonatomic) NSLayoutConstraint *heightConstraint;
@property (nonatomic) _Bool waitingForMetadata;
@property (readonly, nonatomic) _Bool isMetadataComplete;
@property (nonatomic) _Bool hasPerformedInitialLayout;
@property (nonatomic) _Bool inDidFailFetchingMetadataNotification;
@property (retain, nonatomic) ICSearchResultRegexMatchFinder *highlightPatternRegexFinder;
@property (weak, nonatomic) ICAttachment *attachment;
@property (weak, nonatomic) ICAddAttachmentsManagerAttachmentInfo *shareExtensionAttachmentInfo;
@property (nonatomic) _Bool selected;
@property (nonatomic) _Bool insideSystemPaper;
@property (copy, nonatomic) UIColor *highlightColor;
@property (readonly, nonatomic) double effectiveLayoutCornerRadius;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } computedSize;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) float progress;
@property (readonly, nonatomic) unsigned long long state;

/* class methods */
+ (_Bool)usesSmallSizeForAttachment:(id)attachment withMetadata:(id)metadata type:(unsigned long long)type insideSystemPaper:(_Bool)paper;
+ (struct CGSize { double x0; double x1; })defaultBrickSize;
+ (struct CGSize { double x0; double x1; })sizeForAttachment:(id)attachment usesSmallSize:(_Bool)size;
+ (id)standardBackgroundColor;

/* instance methods */
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (void)applicationDidBecomeActive;
- (void)reloadData;
- (id)accessibilityElements;
- (id)initWithType:(unsigned long long)type;
- (void)removeClient:(id)client;
- (void)reset;
- (void)pause;
- (void)addClient:(id)client;
- (void)layoutSubviews;
- (void)play;
- (void)prepareForReuse;
- (_Bool)isAccessibilityElement;
- (id)_linkView:(id)view contextMenuConfigurationForSuggestedConfiguration:(id)configuration;
- (id)_linkView:(id)view playerForAudio:(id)audio;
- (void)linkView:(id)view didFetchMetadata:(id)metadata;
- (void)linkViewNeedsResize:(id)resize;
- (void)updateTitle;
- (void)registerForTraitChanges;
- (void)displaySynapseAttachmentPreview;
- (id)typeDescriptionForAccessibility;
- (void)adjustSizeIfNecessary;
- (void)attachmentDidLoadNotification:(id)notification;
- (void)attachmentPreviewImagesDidUpdateNotification:(id)notification;
- (void)constrainViews;
- (void)didFailFetchingMetadataNotification:(id)notification;
- (void)displayFilePreview;
- (void)displayGenericURLPreview;
- (void)displayRemoteAttachmentPreview;
- (void)displayScannedDocumentsPreview;
- (void)displayUnsupportedAttachmentPreview;
- (void)initialAttachmentPreviewDidLoad:(id)load;
- (_Bool)isInsideSystemPaper;
- (void)mediaDidLoadNotification:(id)notification;
- (void)notifyClientsAboutSizeChangesIfNecessary;
- (void)playbackPausedNotification:(id)notification;
- (void)playbackStartedNotification:(id)notification;
- (void)playbackStoppedNotification:(id)notification;
- (void)progressChangedNotification:(id)notification;
- (id)quickLookTransitionView;
- (void)resetPlaybackProgressAndState;
- (void)updateAttachmentBackgroundColorIfNecessary;
- (void)updateAudioClientsProgress:(float)progress;
- (void)updateAudioClientsState:(unsigned long long)state;
- (void)updateSearchResultBackgroundColorIfNecessary;
- (void)updateUIWithMetadata:(id)metadata;

@end

#endif /* ICAttachmentBrickView_h */
