//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1827.5.1.0.0
//
#ifndef FINodeTask_h
#define FINodeTask_h
@import Foundation;

@class TNodeTask;

@interface FINodeTask : NSObject {
    /* instance variables */
    struct shared_ptr<TNodeTask> { struct TNodeTask *__ptr_; struct __shared_weak_count *__cntrl_; } _nodeTask;
}

/* instance methods */
- (id)init:(const void *)init;

@end

#endif /* FINodeTask_h */
