//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3804.600.21.0.0
//
#ifndef CNContainerAccountIdentifierDescription_h
#define CNContainerAccountIdentifierDescription_h
@import Foundation;

#include "CNContainerPropertyDescription.h"

@interface CNContainerAccountIdentifierDescription : CNContainerPropertyDescription

/* instance methods */
- (Class)valueClass;
- (_Bool)isWritable;
- (void *)ABValueFromCNValue:(id)cnvalue;
- (id)CNValueFromABValue:(void *)abvalue;
- (id)key;
- (void *)ABValueForABSource:(void *)absource;
- (id)CNValueForContainer:(id)container;
- (int)abPropertyID;
- (_Bool)setABValue:(void *)abvalue onABSource:(void *)absource error:(struct __CFError * *)error;
- (void)setCNValue:(id)cnvalue onContainer:(id)container;

@end

#endif /* CNContainerAccountIdentifierDescription_h */
