//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3804.600.21.0.0
//
#ifndef CNTCC_h
#define CNTCC_h
@import Foundation;

@protocol CNTCC;

@interface CNTCC : NSObject

@property (retain, nonatomic) id <CNTCC> tccServices;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (int)accessPreflight;
- (void)simulate:(long long)simulate;

@end

#endif /* CNTCC_h */
