//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1005.6.0.0.0
//
#ifndef CWFPowerTableElectionTelemetry_h
#define CWFPowerTableElectionTelemetry_h
@import Foundation;

@interface CWFPowerTableElectionTelemetry : NSObject {
    /* instance variables */
    NSDateFormatter *_dateFormatter;
    NSDate *_handoffAvailableDate;
    NSString *_handoffWiFiAssetVersionInfo;
    NSString *_handoffBTAssetVersionInfo;
    NSString *_initialAssetFilename;
    NSString *_initialAssetVersionInfoVersion;
    NSDate *_initialAssetVersionInfoDate;
    unsigned char _readinessReply;
    NSDate *_readinessReplyDeliveredDate;
    NSDate *_electionStartNotificationDate;
    unsigned char _voteResult;
    NSDate *_voteDeliveredDate;
    NSString *_finalAssetVersionInfoVersion;
    NSDate *_finalAssetVersionInfoDate;
    unsigned char _wifiInitiatedPTUpdate;
    unsigned char _btInitiatedPTUpdate;
    NSString *_finalResultString;
}

/* class methods */
+ (id)sharedObj;

/* instance methods */
- (id)init;
- (void)setFinalResultAndSendTelemetry:(id)telemetry;
- (id)getElectionSummaryStringForABC;
- (id)getNSDateFromString:(id)string;
- (void)sendTelemetryAndClear;
- (void)setCandidatePowerTableVersionBluetooth:(id)bluetooth;
- (void)setCandidatePowerTableVersionWiFi:(id)fi;
- (void)setCurrentPowerTableVersionAtReadiness:(id)readiness fileName:(id)name;
- (void)setFinalPowerTableVersion:(id)version;
- (void)setPowerTableReadiness:(_Bool)readiness;
- (void)setPowerTableVote:(_Bool)vote;

@end

#endif /* CWFPowerTableElectionTelemetry_h */
