//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 6200.6.8.2.1
//
#ifndef _TtC16HealthTopicsCore14MockTopicStore_h
#define _TtC16HealthTopicsCore14MockTopicStore_h
@import Foundation;

@class HealthTopicsCore.RequestRegistry, _TtCs12_SwiftObject;

@interface _TtC16HealthTopicsCore14MockTopicStore : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    union accessor function sub_259de882c protectedState;
    HealthTopicsCore.RequestRegistry requestRegistry;
}

@end

#endif /* _TtC16HealthTopicsCore14MockTopicStore_h */
