//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1016.206.3.0.0
//
#ifndef QLCustomItemViewController_h
#define QLCustomItemViewController_h
@import Foundation;

#include "QLAppearance.h"
#include "QLRemotePopoverTracker-Protocol.h"

@class UIView, UIViewController;
@protocol QLCustomItemViewControllerHost;

@interface QLCustomItemViewController : UIViewController <QLRemotePopoverTracker> {
    /* instance variables */
    QLAppearance *_lastAppearance;
}

@property (weak, nonatomic) UIView *shareSheetPresentationView;
@property (retain) id <QLCustomItemViewControllerHost> hostViewControllerProxy;
@property (copy, nonatomic) NSDictionary *previewOptions;
@property (nonatomic) _Bool isShareEnabled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)setFullScreen:(_Bool)screen;
- (void)getFrameWithCompletionBlock:(id /* block */)block;
- (void)setAppearance:(id)appearance animated:(_Bool)animated;
- (void)didDismissActivityViewController;
- (void)dismissPreviewController;
- (void)forwardMessageToHost:(id)host completionHandler:(id /* block */)handler;
- (void)presentationModeDidChange:(unsigned long long)change animated:(_Bool)animated;
- (void)presentActivityViewControllerFromView:(id)view;
- (void)presentActivityViewControllerFromView:(id)view withURL:(id)url;

@end

#endif /* QLCustomItemViewController_h */
