//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.2.11.1
//
#ifndef _TtC10PegasusKit35FeedbackReportingURLSessionDelegate_h
#define _TtC10PegasusKit35FeedbackReportingURLSessionDelegate_h
@import Foundation;

@class PegasusAPI.Apple_Parsec_Feedback_V2_FeedbackPayload _$sYbc ->, _$sSaySSG;

@interface _TtC10PegasusKit35FeedbackReportingURLSessionDelegate : NSObject <NSURLSessionTaskDelegate> { // (Swift)
    /* instance variables */
    union accessor function sub_1c2a05904 requestContextMap;
    PegasusAPI.Apple_Parsec_Feedback_V2_FeedbackPayload _$sYbc -> eventHandler;
    _$sSaySSG allowedServices;
}

/* instance methods */
- (void)URLSession:(id)urlsession didCreateTask:(id)task;
- (void)URLSession:(id)urlsession task:(id)task didCompleteWithError:(id)error;
- (void)URLSession:(id)urlsession task:(id)task didFinishCollectingMetrics:(id)metrics;
- (id)init;

@end

#endif /* _TtC10PegasusKit35FeedbackReportingURLSessionDelegate_h */
