//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 301.23.4.7.0
//
#ifndef ICQBannerView_h
#define ICQBannerView_h
@import Foundation;

#include "ICQLegacyBannerView.h"
#include "ICQLegacyBannerViewDelegate-Protocol.h"
#include "ICQPurchase.h"
#include "ICQUpgradeFlowManager.h"
#include "ICQUpgradeFlowManagerDelegate-Protocol.h"
#include "ICQUpgradeFlowOptions.h"
#include "_TtC13iCloudQuotaUI19ICQBubbleBannerView.h"
#include "_TtP13iCloudQuotaUI27ICQBubbleBannerViewDelegate_-Protocol.h"

@class ICQOffer, UIColor, UIFont, UIView;
@protocol ICQBannerViewDelegate;

@interface ICQBannerView : UIView <_TtP13iCloudQuotaUI27ICQBubbleBannerViewDelegate_, ICQLegacyBannerViewDelegate, ICQUpgradeFlowManagerDelegate>

@property (retain, nonatomic) ICQLegacyBannerView *legacyBanner;
@property (retain, nonatomic) _TtC13iCloudQuotaUI19ICQBubbleBannerView *bubbleBanner;
@property (retain, nonatomic) _TtC13iCloudQuotaUI19ICQBubbleBannerView *dismissibleBubbleBanner;
@property (nonatomic) _Bool isLegacy;
@property (nonatomic) _Bool isDismissible;
@property (retain, nonatomic) ICQUpgradeFlowManager *localFlowManager;
@property (retain, nonatomic) ICQPurchase *purchase;
@property (retain, nonatomic) ICQOffer *offer;
@property (weak, nonatomic) id <ICQBannerViewDelegate> delegate;
@property (retain, nonatomic) UIFont *font;
@property (retain, nonatomic) UIFont *titleFont;
@property (retain, nonatomic) UIFont *detailMessageFont;
@property (retain, nonatomic) UIFont *linkMessageFont;
@property (retain, nonatomic) UIColor *titleColor;
@property (retain, nonatomic) UIColor *detailMessageColor;
@property (retain, nonatomic) UIColor *linkMessageColor;
@property (retain, nonatomic) UIColor *textColor;
@property (nonatomic) struct NSDirectionalEdgeInsets { double x0; double x1; double x2; double x3; } textMargins;
@property (nonatomic) long long textAlignment;
@property (nonatomic) double textLineSpacing;
@property (copy, nonatomic) UIFont *linkTextFont;
@property (copy, nonatomic) UIColor *linkTextColor;
@property (copy, nonatomic) ICQUpgradeFlowOptions *flowOptions;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)shouldShowForDismissibleOffer:(id)offer;
+ (_Bool)shouldShowForOffer:(id)offer;
+ (id)debugBannerOffer;

/* instance methods */
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)_registerForDarwinNotifications;
- (id)initWithDismissibleOffer:(id)offer;
- (id)initWithOffer:(id)offer;
- (void)upgradeFlowManagerDidCancel:(id)cancel;
- (void)upgradeFlowManagerDidComplete:(id)complete;
- (void)_handlePushReceivedDarwinNotification;
- (id)_initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame offer:(id)offer dismissibility:(_Bool)dismissibility;
- (_Bool)_launchFlowManagerWithLink:(id)link;
- (void)handleBannerDismiss:(id)dismiss;
- (_Bool)performActionWith:(id)with;
- (void)updateBannerView;

@end

#endif /* ICQBannerView_h */
