//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1933.11.0.0.0
//
#ifndef VisionSignalGradingVisionGradeEvent_h
#define VisionSignalGradingVisionGradeEvent_h
@import Foundation;

@class PBCodable;

@interface VisionSignalGradingVisionGradeEvent : PBCodable <NSCopying>

@property (retain, nonatomic) NSMutableArray *visionGrades;
@property (retain, nonatomic) NSMutableArray *popularityEntries;

/* class methods */
+ (Class)popularityEntriesType;
+ (Class)visionGradesType;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (void)copyTo:(id)to;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)writeTo:(id)to;
- (id)dictionaryRepresentation;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (void)addPopularityEntries:(id)entries;
- (void)addVisionGrades:(id)grades;
- (void)clearPopularityEntries;
- (void)clearVisionGrades;
- (id)popularityEntriesAtIndex:(unsigned long long)index;
- (unsigned long long)popularityEntriesCount;
- (id)visionGradesAtIndex:(unsigned long long)index;
- (unsigned long long)visionGradesCount;

@end

#endif /* VisionSignalGradingVisionGradeEvent_h */
