//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 649.40.2.0.0
//
#ifndef RWIProtocolDOMNode_IKJSInspector_h
#define RWIProtocolDOMNode_IKJSInspector_h
@import Foundation;

@interface RWIProtocolDOMNode (IKJSInspector)

/* class methods */
+ (id)ik_nodeFromDOMNode:(id)domnode;
+ (id)ik_nodeFromDOMNode:(id)domnode depth:(int)depth;
+ (id)safe_initWithNodeId:(int)id nodeType:(int)type nodeName:(id)name localName:(id)name nodeValue:(id)value;

/* instance methods */
- (id)ik_attributesDictionary;
- (id)ik_description;
- (void)ik_insertChild:(id)child before:(id)before;
- (id)ik_nodeWithNodeId:(int)id;
- (void)ik_removeAttributeNamed:(id)named;
- (void)ik_removeChildWithId:(int)id;
- (void)ik_setAttributeValue:(id)value name:(id)name;
- (void)ik_updateWithDOMNode:(id)domnode dispatcher:(id)dispatcher;
- (void)ik_updateWithDOMNode:(id)domnode fullfillChildren:(_Bool)children dispatcher:(id)dispatcher;

@end

#endif /* RWIProtocolDOMNode_IKJSInspector_h */
