//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.2.2.0.0
//
#ifndef DEExecutor_h
#define DEExecutor_h
@import Foundation;

#include "DEDistribution.h"
#include "DEExecutionContext.h"
#include "DEPatternContext.h"

@interface DEExecutor : NSObject

@property (retain, nonatomic) NSString *templateDir;
@property (retain, nonatomic) NSString *catId;
@property (retain, nonatomic) NSString *locale;
@property (retain, nonatomic) NSDictionary *dialogMetadata;
@property (retain, nonatomic) NSString *interactionId;
@property (retain, nonatomic) NSString *executionRequestId;
@property (retain, nonatomic) NSString *patternId;
@property (retain, nonatomic) NSString *responseMode;
@property (retain, nonatomic) NSDictionary *parameters;
@property (retain, nonatomic) NSDictionary *globalParameters;
@property (retain, nonatomic) NSDictionary *userSettings;
@property (retain, nonatomic) NSString *pluginName;
@property (retain, nonatomic) DEExecutionContext *context;
@property (copy, nonatomic) id /* block */ callback;
@property (nonatomic) _Bool visual;
@property (nonatomic) _Bool debug;
@property (nonatomic) _Bool test;
@property (nonatomic) _Bool resetState;
@property (nonatomic) _Bool multiuser;
@property (nonatomic) _Bool grounding;
@property (nonatomic) _Bool enableUpdates;
@property (nonatomic) _Bool createTrace;
@property (nonatomic) _Bool switchFallthrough;
@property (nonatomic) _Bool includeKeywords;
@property (retain, nonatomic) NSString *voiceGender;
@property (nonatomic) unsigned int randomSeed;
@property (nonatomic) long long currentTime;
@property (retain, nonatomic) DEDistribution *distribution;
@property (retain, nonatomic) NSDictionary *customPronunciations;
@property (nonatomic) _Bool deterministic;
@property (retain, nonatomic) DEPatternContext *patternContext;
@property (nonatomic) _Bool isSpotlight;
@property (nonatomic) _Bool isLabelMode;
@property (nonatomic) _Bool disableLogging;

/* class methods */
+ (void)preload;
+ (void)initialize;
+ (void)executeWithJson:(id)json callback:(id /* block */)callback completionBlock:(id /* block */)block;
+ (id)bundleTemplateDir:(id)dir;
+ (void)executeWithJson:(id)json completionBlock:(id /* block */)block;
+ (id /* block */)prepareCallback:(id /* block */)callback forContext:(void *)context;
+ (void)executeWithJson:(id)json paramsString:(id)string localeString:(id)string callback:(id /* block */)callback completionBlock:(id /* block */)block;

/* instance methods */
- (id)execute;
- (id)init;
- (struct shared_ptr<siri::dialogengine::Context> { struct Context *x0; struct __shared_weak_count *x1; })getContext:(struct ElapsedTimer { unsigned long long x0; struct TimeStamp { double x0; double x1; } x1; struct optional<siri::dialogengine::ElapsedTimer::TimeStamp> { union { signed char x0; struct TimeStamp { double x0; double x1; } x1; } x0; _Bool x1; } x2; })context;
- (void)LogCurareCATExecution:(const void *)catexecution;
- (id)consumeContext:(struct shared_ptr<siri::dialogengine::Context> { struct Context *x0; struct __shared_weak_count *x1; })context paramsPath:(struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct { union __rep { struct __short { signed char x0[23]; unsigned int x1:7; unsigned int x2:1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long long x2:63; unsigned int x3:1; } x1; } x0; } x0; })path localePath:(struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct { union __rep { struct __short { signed char x0[23]; unsigned int x1:7; unsigned int x2:1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long long x2:63; unsigned int x3:1; } x1; } x0; } x0; })path visualPath:(struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct { union __rep { struct __short { signed char x0[23]; unsigned int x1:7; unsigned int x2:1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long long x2:63; unsigned int x3:1; } x1; } x0; } x0; })path;
- (struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct { union __rep { struct __short { signed char x0[23]; unsigned int x1:7; unsigned int x2:1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long long x2:63; unsigned int x3:1; } x1; } x0; } x0; })consumeContextForJson:(struct shared_ptr<siri::dialogengine::Context> { struct Context *x0; struct __shared_weak_count *x1; })json;
- (id)executeVisual:(id)visual;
- (void)executeVisual:(id)visual completionBlock:(id /* block */)block;
- (void)executeWithCompletionBlock:(id /* block */)block;
- (id)executeWithParams:(id)params locale:(id)locale;
- (void)executeWithParams:(id)params locale:(id)locale completionBlock:(id /* block */)block;
- (id)executeWithParams:(id)params locale:(id)locale visual:(id)visual;
- (id)getRequestJSON;
- (void)updateContext:(void *)context paramsPath:(struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct { union __rep { struct __short { signed char x0[23]; unsigned int x1:7; unsigned int x2:1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long long x2:63; unsigned int x3:1; } x1; } x0; } x0; })path localePath:(struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct { union __rep { struct __short { signed char x0[23]; unsigned int x1:7; unsigned int x2:1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long long x2:63; unsigned int x3:1; } x1; } x0; } x0; })path visualPath:(struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct { union __rep { struct __short { signed char x0[23]; unsigned int x1:7; unsigned int x2:1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long long x2:63; unsigned int x3:1; } x1; } x0; } x0; })path;

@end

#endif /* DEExecutor_h */
