//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2.5.11.2.2
//
#ifndef _TtC25UnifiedMessagingKitJSCore5JSAMS_h
#define _TtC25UnifiedMessagingKitJSCore5JSAMS_h
@import Foundation;

#include "_TtP25UnifiedMessagingKitJSCore12JSAppExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore12JSLogExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore15JSClientExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore15JSDeviceExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore15JSFamilyExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore16JSBacklogExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore16JSContentExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore16JSMetricsExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore16JSPrivacyExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore17JSFollowUpExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore17JSLocalizeExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore17JSLocationExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore17JSMediaAPIExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore18JSExtensionExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore18JSMarketingExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore18JSTelephonyExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore20JSFeatureFlagExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore21JSAccountStoreExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore22JSDatabaseStoreExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore23JSAccountServiceExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore23JSTreatmentStoreExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore24JSServerDataCacheExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore25JSMediaCatalogSyncExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore26JSUserNotificationsExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore27JSSubscriptionStatusExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore28JSOnDeviceDataServiceExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCore29JSRunningBoardServicesExports_-Protocol.h"
#include "_TtP25UnifiedMessagingKitJSCoreP33_09CD063935F8C8474053450E88333F2012JSAMSExports_-Protocol.h"

@class UnifiedMessagingKitJSCore.AppReference Foundation.UUID, _$sSDySSypG;

@interface _TtC25UnifiedMessagingKitJSCore5JSAMS : NSObject <_TtP25UnifiedMessagingKitJSCoreP33_09CD063935F8C8474053450E88333F2012JSAMSExports_> { // (Swift)
    /* instance variables */
    UnifiedMessagingKitJSCore.AppReference Foundation.UUID uuid;
}

@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore21JSAccountStoreExports_> accounts;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore23JSAccountServiceExports_> accountService;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore12JSAppExports_> app;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore16JSBacklogExports_> backlog;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore15JSClientExports_> client;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore16JSContentExports_> content;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore22JSDatabaseStoreExports_> database;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore15JSDeviceExports_> device;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore17JSLocalizeExports_> localize;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore17JSLocationExports_> location;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore12JSLogExports_> log;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore17JSMediaAPIExports_> media;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore16JSMetricsExports_> metrics;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore16JSPrivacyExports_> privacy;
@property (nonatomic, readonly) NSDictionary *props;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore18JSExtensionExports_> plugin;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore27JSSubscriptionStatusExports_> subscription;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore26JSUserNotificationsExports_> userNotifications;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore15JSFamilyExports_> family;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore20JSFeatureFlagExports_> featureFlag;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore17JSFollowUpExports_> followUp;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore18JSMarketingExports_> marketing;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore25JSMediaCatalogSyncExports_> mediaCatalogSync;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore28JSOnDeviceDataServiceExports_> onDeviceDataService;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore29JSRunningBoardServicesExports_> runningBoardServices;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore24JSServerDataCacheExports_> serverDataCache;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore18JSTelephonyExports_> telephony;
@property (nonatomic, readonly) id <_TtP25UnifiedMessagingKitJSCore23JSTreatmentStoreExports_> treatmentStore;

/* instance methods */
- (id)init;

@end

#endif /* _TtC25UnifiedMessagingKitJSCore5JSAMS_h */
