//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2031.35.2.9.20
//
#ifndef GEOActiveResourceFilter_h
#define GEOActiveResourceFilter_h
@import Foundation;

@class PBCodable, PBUnknownFields;

@interface GEOActiveResourceFilter : PBCodable <NSCopying> {
    /* instance variables */
    struct { unsigned int has_lastTimestamp:1; } _flags;
}

@property (readonly, nonatomic) _Bool _filterStaleThresholdExpired;
@property (nonatomic) _Bool hasLastTimestamp;
@property (nonatomic) double lastTimestamp;
@property (nonatomic) int scale;
@property (nonatomic) int scenario;
@property (retain, nonatomic) NSString *name;
@property (readonly, nonatomic) unsigned long long whichFilter;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;

/* class methods */
+ (_Bool)isValid:(id)valid;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (void)copyTo:(id)to;
- (unsigned long long)hash;
- (void)resetFilter;
- (void)mergeFrom:(id)from;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)scaleAsString:(int)string;
- (id)jsonRepresentation;
- (void)writeTo:(id)to;
- (id)initWithJSON:(id)json;
- (id)initWithDictionary:(id)dictionary;
- (void)readAll:(_Bool)all;
- (id)dictionaryRepresentation;
- (int)StringAsScale:(id)scale;
- (id)description;
- (void)clearUnknownFields:(_Bool)fields;
- (_Bool)isEqual:(id)equal;
- (int)StringAsScenario:(id)scenario;
- (_Bool)_isFilterStaleThresholdExpired;
- (id)scenarioAsString:(int)string;

@end

#endif /* GEOActiveResourceFilter_h */
