//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2031.35.2.9.20
//
#ifndef GEOETAResultByType_h
#define GEOETAResultByType_h
@import Foundation;

#include "GEORouteTrafficDetail.h"
#include "GEOShortTrafficSummary.h"

@class PBCodable, PBDataReader, PBUnknownFields;

@interface GEOETAResultByType : PBCodable <NSCopying> {
    /* instance variables */
    PBDataReader *_reader;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _readerLock;
    struct { unsigned int has_expectedTimeOfDeparture:1; unsigned int has_distance:1; unsigned int has_historicTravelTime:1; unsigned int has_licensePlateRestrictionImpact:1; unsigned int has_staticTravelTime:1; unsigned int has_status:1; unsigned int has_transportType:1; unsigned int has_travelTimeBestEstimate:1; unsigned int has_travelTimeAggressiveEstimate:1; unsigned int has_travelTimeConservativeEstimate:1; unsigned int read_unknownFields:1; unsigned int read_routeTrafficDetail:1; unsigned int read_shortTrafficSummary:1; unsigned int read_summaryForPredictedDestinations:1; unsigned int wrote_anyField:1; } _flags;
}

@property (nonatomic) _Bool hasTransportType;
@property (nonatomic) int transportType;
@property (nonatomic) _Bool hasStatus;
@property (nonatomic) int status;
@property (nonatomic) _Bool hasTravelTimeBestEstimate;
@property (nonatomic) unsigned int travelTimeBestEstimate;
@property (nonatomic) _Bool hasHistoricTravelTime;
@property (nonatomic) unsigned int historicTravelTime;
@property (nonatomic) _Bool hasDistance;
@property (nonatomic) unsigned int distance;
@property (nonatomic) _Bool hasExpectedTimeOfDeparture;
@property (nonatomic) double expectedTimeOfDeparture;
@property (nonatomic) _Bool hasTravelTimeConservativeEstimate;
@property (nonatomic) unsigned int travelTimeConservativeEstimate;
@property (nonatomic) _Bool hasTravelTimeAggressiveEstimate;
@property (nonatomic) unsigned int travelTimeAggressiveEstimate;
@property (nonatomic) _Bool hasStaticTravelTime;
@property (nonatomic) unsigned int staticTravelTime;
@property (retain, nonatomic) NSMutableArray *summaryForPredictedDestinations;
@property (readonly, nonatomic) _Bool hasRouteTrafficDetail;
@property (retain, nonatomic) GEORouteTrafficDetail *routeTrafficDetail;
@property (readonly, nonatomic) _Bool hasShortTrafficSummary;
@property (retain, nonatomic) GEOShortTrafficSummary *shortTrafficSummary;
@property (nonatomic) _Bool hasLicensePlateRestrictionImpact;
@property (nonatomic) int licensePlateRestrictionImpact;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;

/* class methods */
+ (_Bool)isValid:(id)valid;
+ (Class)summaryForPredictedDestinationType;

/* instance methods */
- (int)StringAsStatus:(id)status;
- (_Bool)readFrom:(id)from;
- (id)initWithData:(id)data;
- (void)copyTo:(id)to;
- (unsigned long long)hash;
- (int)StringAsTransportType:(id)type;
- (void)mergeFrom:(id)from;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)transportTypeAsString:(int)string;
- (id)statusAsString:(int)string;
- (id)jsonRepresentation;
- (void)writeTo:(id)to;
- (id)initWithJSON:(id)json;
- (id)init;
- (id)initWithDictionary:(id)dictionary;
- (void)readAll:(_Bool)all;
- (id)dictionaryRepresentation;
- (id)description;
- (void)clearUnknownFields:(_Bool)fields;
- (_Bool)isEqual:(id)equal;
- (int)StringAsLicensePlateRestrictionImpact:(id)impact;
- (void)addSummaryForPredictedDestination:(id)destination;
- (void)clearSummaryForPredictedDestinations;
- (id)licensePlateRestrictionImpactAsString:(int)string;
- (id)summaryForPredictedDestinationAtIndex:(unsigned long long)index;
- (unsigned long long)summaryForPredictedDestinationsCount;

@end

#endif /* GEOETAResultByType_h */
