//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 324.1.0.0.0
//
#ifndef VKAnalyticsQuickActionEvent_h
#define VKAnalyticsQuickActionEvent_h
@import Foundation;

#include "VKAnalyticsEvent.h"

@interface VKAnalyticsQuickActionEvent : VKAnalyticsEvent

@property (nonatomic) long long eventType;
@property (nonatomic) long long quickActionsCount;
@property (retain, nonatomic) NSString *quickActionType;
@property (nonatomic) long long textLength;

/* instance methods */
- (long long)type;
- (id)coreAnalyticsDictionary;
- (id)eventKey;
- (id)description;
- (id)initWithQuickActionType:(id)type quickActionsCount:(long long)count textLength:(long long)length eventType:(long long)type customIdentifier:(id)identifier;

@end

#endif /* VKAnalyticsQuickActionEvent_h */
