//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef _UIContentUnavailableView_h
#define _UIContentUnavailableView_h
@import Foundation;

#include "UIButton.h"
#include "UILabel.h"
#include "UIScrollView.h"
#include "UIView.h"
#include "_UIBackdropView.h"

@class NSLayoutConstraint;

@interface _UIContentUnavailableView : UIView {
    /* instance variables */
    unsigned long long _style;
    _UIBackdropView *_backdrop;
    UIView *_containerView;
    UIScrollView *_scrollView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIButton *_actionButton;
    NSLayoutConstraint *titleToMessageConstraint;
    NSLayoutConstraint *messageToButtonConstraint;
    UIView *_fromSnapshot;
    UIView *_toSnapshot;
    struct CGSize { double width; double height; } _fromSnapshotSize;
    NSMutableArray *_containerViewContraints;
}

@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSString *message;
@property (copy, nonatomic) NSString *buttonTitle;
@property (copy, nonatomic) id /* block */ buttonAction;
@property (nonatomic) unsigned long long vibrantOptions;

/* class methods */
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (void)updateConstraints;
- (void)didMoveToWindow;
- (id)preferredFocusedView;
- (id)_titleFont;
- (void)dealloc;
- (void)_actionButtonPressed:(id)pressed;
- (id)_titleLabel;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (_Bool)_hasVibrantText;
- (id)_actionButton;
- (double)_buttonAlpha;
- (id)_buttonBackgroundImageForStyle:(unsigned long long)style controlState:(unsigned long long)state;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })_buttonContentEdgeInsets;
- (id)_buttonFont;
- (struct CGSize { double x0; double x1; })_buttonSize;
- (id)_buttonTextStyle;
- (double)_buttonVerticalSpacing;
- (struct CGColor *)_colorForButtonForStyle:(unsigned long long)style controlState:(unsigned long long)state;
- (id)_flatTextColor;
- (_Bool)_hasVibrantButton;
- (double)_labelAlpha;
- (double)_labelVerticalSpacing;
- (id)_messageLabel;
- (id)_messageTextStyle;
- (void)_rebuildConstraints;
- (void)_updateForCurrentContentSizeCategory;
- (void)_updateViewHierarchy;
- (id)_vibrantBaseColor;
- (void)cleanupLingeringRotationState;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame title:(id)title style:(unsigned long long)style;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame title:(id)title style:(unsigned long long)style includeBackdrop:(_Bool)backdrop;
- (void)windowDidRotateNotification:(id)notification;
- (void)windowWillAnimateRotateNotification:(id)notification;
- (void)windowWillRotateNotification:(id)notification;

@end

#endif /* _UIContentUnavailableView_h */
