//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef UIAssistantBarRoundedButtonViewButton_h
#define UIAssistantBarRoundedButtonViewButton_h
@import Foundation;

#include "UIButton.h"
#include "UIColor.h"

@interface UIAssistantBarRoundedButtonViewButton : UIButton

@property (retain, nonatomic) UIColor *normalBackgroundColor;
@property (retain, nonatomic) UIColor *highlightedBackgroundColor;
@property (retain, nonatomic) UIColor *normalTitleColor;
@property (retain, nonatomic) UIColor *highlightedTitleColor;

/* instance methods */
- (void)setHighlighted:(_Bool)highlighted;
- (id)_currentTitleColor;
- (id)_titleColorForState:(unsigned long long)state;
- (void)_updateBackgroundAndTitleColor;

@end

#endif /* UIAssistantBarRoundedButtonViewButton_h */
