//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef UIKeyboardEmojiWellView_h
#define UIKeyboardEmojiWellView_h
@import Foundation;

#include "UIColor.h"
#include "UIKeyboardEmojiDraggableViewDelegate-Protocol.h"
#include "UILabel.h"
#include "UIView.h"

@class UIFont;

@interface UIKeyboardEmojiWellView : UIView <UIKeyboardEmojiDraggableViewDelegate>

@property (retain, nonatomic) UILabel *unreleasedBanner;
@property (retain, nonatomic) UIView *wellContentView;
@property (retain, nonatomic) UIView *backgroundView;
@property (nonatomic) struct CGSize { double x0; double x1; } compositeImageSize;
@property (retain, nonatomic) NSArray *compositeImageRepresentation;
@property (retain, nonatomic) UIFont *labelFont;
@property (retain, nonatomic) NSString *stringRepresentation;
@property (nonatomic) _Bool selected;
@property (nonatomic) _Bool activeSelection;
@property (retain, nonatomic) UIColor *selectionBackgroundColor;
@property (retain, nonatomic) NSIndexPath *associatedIndexPath;
@property (nonatomic) _Bool unreleasedHighlight;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (_Bool)isSelected;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (void)dragWillBegin:(id)begin;
- (id)fontUsingSilhouette:(unsigned long long)silhouette size:(double)size;
- (_Bool)isActiveSelection;
- (void)setStringRepresentation:(id)representation silhouette:(unsigned long long)silhouette;

@end

#endif /* UIKeyboardEmojiWellView_h */
