//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 203.100.3.0.0
//
#ifndef VFXTextureSource_h
#define VFXTextureSource_h
@import Foundation;

@class 1;

@interface VFXTextureSource : NSObject {
    /* instance variables */
    id _mtlTextureCache;
     _size;
}

/* instance methods */
- (void)setSize:;
- (void)dealloc;
- (double)nextFrameTime;
- (id)MTLTextureCache;
- (id)metalTextureWithEngineContext:(struct __CFXEngineContext *)context textureSampler:(struct { unsigned int x0:8; unsigned int x1:8; unsigned int x2:8; unsigned int x3:8; unsigned int x4:8; unsigned int x5:8; unsigned int x6:8; unsigned int x7:7; unsigned int x8:1; })sampler nextFrameTime:(double *)time status:(struct { _Bool x0; _Bool x1; } *)status;
- (void)renderWithEngineContext:(struct __CFXEngineContext *)context textureSampler:(struct { unsigned int x0:8; unsigned int x1:8; unsigned int x2:8; unsigned int x3:8; unsigned int x4:8; unsigned int x5:8; unsigned int x6:8; unsigned int x7:7; unsigned int x8:1; })sampler nextFrameTime:(double *)time;
- (void)setMTLTextureCache:(id)cache;
- (_Bool)shouldFlip;
- (_Bool)supportsMetal;
- (1)textureSize;

@end

#endif /* VFXTextureSource_h */
