//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2.5.15.2.1
//
#ifndef _TtC12GameStoreKit36GamesThreeDimensionalRealityRenderer_h
#define _TtC12GameStoreKit36GamesThreeDimensionalRealityRenderer_h
@import Foundation;

@class GameStoreKit.GamesThreeDimensionalRealityRenderer.RendererComponents ?, GameStoreKit.IconCollectionStyle, _TtCs12_SwiftObject, s.OSAllocatedUnfairLock GameStoreKit.GamesThreeDimensionalRealityRenderer.RendererComponents ?;

@interface _TtC12GameStoreKit36GamesThreeDimensionalRealityRenderer : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    GameStoreKit.GamesThreeDimensionalRealityRenderer.RendererComponents ? rendererComponents;
    out s.OSAllocatedUnfairLock GameStoreKit.GamesThreeDimensionalRealityRenderer.RendererComponents ? componentsLock;
    GameStoreKit.IconCollectionStyle placementStyle;
}

@end

#endif /* _TtC12GameStoreKit36GamesThreeDimensionalRealityRenderer_h */
