//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.2.11.1
//
#ifndef _TtC9SwiftAvro13SchemaEncoder_h
#define _TtC9SwiftAvro13SchemaEncoder_h
@import Foundation;

@class _$sSD -> Swift.CodingUserInfoKey Any, _$sSDySS SwiftAvro.AvroRecordSchema, _$sSa -> Swift.CodingKey, _$sSa -> SwiftAvro.SchemaEncoder.ContainerKind, _$sSa -> SwiftAvro.SchemaEncoder.Token, _TtCs12_SwiftObject;

@interface _TtC9SwiftAvro13SchemaEncoder : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSa -> Swift.CodingKey codingPath;
    _$sSD -> Swift.CodingUserInfoKey Any userInfo;
    _$sSDySS SwiftAvro.AvroRecordSchema records;
    _$sSa -> SwiftAvro.SchemaEncoder.Token tokens;
    _$sSa -> SwiftAvro.SchemaEncoder.ContainerKind containerStack;
}

@end

#endif /* _TtC9SwiftAvro13SchemaEncoder_h */
