//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef NUAuxiliaryPropertiesResult_Protocol_h
#define NUAuxiliaryPropertiesResult_Protocol_h
@import Foundation;

#include "NUImageProperties-Protocol.h"
#include "NURenderResult-Protocol.h"

@protocol NUAuxiliaryPropertiesResult <NURenderResult>

@required

@property (readonly) _Bool canPropagateOriginalAuxiliaryData;
@property (readonly) id <NUImageProperties> properties;

@optional

@end

#endif /* NUAuxiliaryPropertiesResult_Protocol_h */
