//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2026.5.10.0.0
//
#ifndef NLLocationRequestManager_h
#define NLLocationRequestManager_h
@import Foundation;

#include "CLLocationManagerDelegate-Protocol.h"

@class v24@?0@"NSData"8@"NSError"16;

@interface NLLocationRequestManager : NSObject <CLLocationManagerDelegate> { // (Swift)
    /* instance variables */
    v24@?0@"NSData"8@"NSError"16 queue;
    v24@?0@"NSData"8@"NSError"16 locationManager;
    v24@?0@"NSData"8@"NSError"16 authorizationCompletionBlocks;
}

/* instance methods */
- (id)init;
- (void)locationManagerDidChangeAuthorization:(id)authorization;
- (void)requestLocationAuthorizationWithCompletion:(id /* block */)completion;

@end

#endif /* NLLocationRequestManager_h */
