//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 679.21.0.0.0
//
#ifndef TTSPhonemeSupport_h
#define TTSPhonemeSupport_h
@import Foundation;

@interface TTSPhonemeSupport : NSObject

/* class methods */
+ (id)supportedIPAPhonemeLanguages;
+ (id)_getPhonemeMapForSynth:(id)synth language:(id)language;
+ (id)_ipaVectorFromString:(id)string;
+ (id)_phonemesFromIPA:(id)ipa language:(id)language synth:(id)synth;
+ (id)applebetPhonemesFromIPA:(id)ipa;
+ (id)applebetPhonemesFromLH:(id)lh;
+ (id)eloquencePhonemesFromIPA:(id)ipa language:(id)language;
+ (id)lhPhonemesFromIPA:(id)ipa language:(id)language;
+ (id)phonemesFromIPA:(id)ipa language:(id)language;

@end

#endif /* TTSPhonemeSupport_h */
