//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 166.5.0.0.0
//
#ifndef AXMPixelBufferWrapper_h
#define AXMPixelBufferWrapper_h
@import Foundation;

@interface AXMPixelBufferWrapper : NSObject

@property (readonly, nonatomic) struct __CVBuffer * pixelBuffer;
@property (readonly, nonatomic) unsigned int orientation;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } unorientedSize;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } orientedSize;

/* class methods */
+ (id)new;
+ (id)wrapperWithPixelBuffer:(struct __CVBuffer *)buffer orientation:(unsigned int)orientation;

/* instance methods */
- (void)dealloc;
- (id)init;
- (id)_initWithPixelBuffer:(struct __CVBuffer *)buffer orientation:(unsigned int)orientation;

@end

#endif /* AXMPixelBufferWrapper_h */
