//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1969.600.51.2.5
//
#ifndef FTSelectedPNRSubscriptionCache_h
#define FTSelectedPNRSubscriptionCache_h
@import Foundation;

@class CTXPCContexts, CTXPCServiceSubscriptionContext, CTXPCServiceSubscriptionInfo;

@interface FTSelectedPNRSubscriptionCache : NSObject

@property (retain, nonatomic) CTXPCServiceSubscriptionInfo *subscriptionInfo;
@property (retain, nonatomic) CTXPCContexts *activeSubscriptionInfo;
@property (retain, nonatomic) CTXPCServiceSubscriptionContext *selectedContext;
@property (retain, nonatomic) NSString *phoneNumber;
@property (nonatomic) long long dualSIMCapability;

/* instance methods */
- (id)debugDescription;

@end

#endif /* FTSelectedPNRSubscriptionCache_h */
