//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 616.2.0.0.0
//
#ifndef DSReadOnlyResourceSharingDetailDelegate_Protocol_h
#define DSReadOnlyResourceSharingDetailDelegate_Protocol_h
@import Foundation;

@protocol DSReadOnlyResourceSharingDetailDelegate <NSObject>

@required

/* required instance methods */
- (void)learnMorePressedForSharingType:(id)type;
- (void)reviewReadOnlySharingCompleted;

@optional

@end

#endif /* DSReadOnlyResourceSharingDetailDelegate_Protocol_h */
