//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 950.120.3.0.0
//
#ifndef SUPolicy_h
#define SUPolicy_h
@import Foundation;

@interface SUPolicy : NSObject

@property (readonly, nonatomic) _Bool discretionary;
@property (readonly, nonatomic) _Bool allowsCellular;
@property (readonly, nonatomic) _Bool allowExpensiveNetwork;
@property (readonly, nonatomic) _Bool requiresPowerPluggedIn;
@property (readonly, nonatomic) _Bool skipPhase;
@property (readonly, nonatomic) int downloadTimeoutSecs;
@property (readonly, retain, nonatomic) NSDictionary *additionalOptions;

/* instance methods */
- (id)description;
- (id)_stringForBool:(_Bool)_bool;

@end

#endif /* SUPolicy_h */
