//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2001.35.2.9.9
//
#ifndef VKGesturingCameraController_Protocol_h
#define VKGesturingCameraController_Protocol_h
@import Foundation;

@protocol VKGesturingCameraController <NSObject>

@required

/* required instance methods */
- (void)updateRotationWithFocusPoint:(struct CGPoint { double x0; double x1; })point newValue:(double)value;
- (void)startPinchingWithFocusPoint:(struct CGPoint { double x0; double x1; })point;
- (void)stopPitchingWithFocusPoint:(struct CGPoint { double x0; double x1; })point;
- (void)startPanningAtPoint:(struct CGPoint { double x0; double x1; })point panAtStartPoint:(_Bool)point;
- (void)stopRotatingWithFocusPoint:(struct CGPoint { double x0; double x1; })point;
- (_Bool)tapAtPoint:(struct CGPoint { double x0; double x1; })point;
- (void)stopPanningAtPoint:(struct CGPoint { double x0; double x1; })point;
- (void)startPitchingWithFocusPoint:(struct CGPoint { double x0; double x1; })point;
- (void)zoom:(double)zoom withFocusPoint:(struct CGPoint { double x0; double x1; })point completionHandler:(id /* block */)handler;
- (void)updatePitchWithFocusPoint:(struct CGPoint { double x0; double x1; })point translation:(double)translation;
- (void)updatePanWithTranslation:(struct CGPoint { double x0; double x1; })translation;
- (void)updatePitchWithFocusPoint:(struct CGPoint { double x0; double x1; })point degrees:(double)degrees;
- (void)updatePinchWithFocusPoint:(struct CGPoint { double x0; double x1; })point oldFactor:(double)factor newFactor:(double)factor;
- (void)startRotatingWithFocusPoint:(struct CGPoint { double x0; double x1; })point;
- (void)stopPinchingWithFocusPoint:(struct CGPoint { double x0; double x1; })point;
- (void)transferGestureState:(id)state;
- (void)resetGestureState;

@optional

/* optional instance methods */
- (void)willStopPanningAtPoint:(struct CGPoint { double x0; double x1; })point withVelocity:(struct CGPoint { double x0; double x1; })velocity;
- (void)zoomToLevel:(double)level withFocusPoint:(struct CGPoint { double x0; double x1; })point;

@end

#endif /* VKGesturingCameraController_Protocol_h */
