//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1450.600.61.2.7
//
#ifndef PRUISPosterMotionEventsGenerating_Protocol_h
#define PRUISPosterMotionEventsGenerating_Protocol_h
@import Foundation;

@protocol PRUISPosterMotionEventsDelegate;

@protocol PRUISPosterMotionEventsGenerating

@required

@property (nonatomic) double deviceMotionUpdateInterval;
@property (weak, nonatomic) id <PRUISPosterMotionEventsDelegate> motionEventsDelegate;

/* required instance methods */
- (void)startSendingMotionEvents;
- (void)stopSendingMotionEvents;

@optional

@end

#endif /* PRUISPosterMotionEventsGenerating_Protocol_h */
