//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 282.5.5.0.0
//
#ifndef MTRAwaitedAttributeState_h
#define MTRAwaitedAttributeState_h
@import Foundation;

@interface MTRAwaitedAttributeState : NSObject {
    /* instance variables */
    _Bool _valueSatisfied;
    NSDictionary *_value;
}

/* instance methods */

@end

#endif /* MTRAwaitedAttributeState_h */
