//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 81.0.0.0.0
//
#ifndef FedStatsDataCohort_h
#define FedStatsDataCohort_h
@import Foundation;

@interface FedStatsDataCohort : NSObject

@property (readonly, nonatomic) NSDictionary *namespaceMap;
@property (readonly, nonatomic) NSDictionary *valueAllowList;
@property (readonly, nonatomic) NSDictionary *valueBlockList;

/* class methods */
+ (id)sharedInstance;
+ (_Bool)checkCohortField:(id)field forNamespaceID:(id)id;
+ (id)keysForCohorts:(id)cohorts namespaceID:(id)id parameters:(id)parameters possibleError:(id *)error;

/* instance methods */
- (id)init;
- (_Bool)checkCohortValue:(id)value forCohortName:(id)name namespaceIdentifier:(id)identifier;

@end

#endif /* FedStatsDataCohort_h */
