//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 340.16.0.0.0
//
#ifndef ASDTIOServiceDependency_h
#define ASDTIOServiceDependency_h
@import Foundation;

#include "ASDTIOService.h"
#include "ASDTIOServiceID.h"
#include "ASDTIOServiceManager.h"

@interface ASDTIOServiceDependency : NSObject

@property (retain, nonatomic) NSString *ioServiceClassName;
@property (retain, nonatomic) ASDTIOServiceID *ioServiceID;
@property (weak, nonatomic) ASDTIOServiceManager *ioServiceManager;
@property (retain) ASDTIOService *ioService;
@property (retain, nonatomic) NSDictionary *configuration;

/* class methods */
+ (id)forAnyInstanceOfClassName:(id)name andConfiguration:(id)configuration;
+ (id)forClassName:(id)name idValue:(id)value andConfiguration:(id)configuration;
+ (_Bool)ioServiceMatched:(id)matched withClassName:(id)name andIdentifier:(id)identifier;

/* instance methods */
- (id)description;
- (_Bool)ioServiceAvailable:(id)available withManager:(id)manager;
- (void)addManagerDelegate:(id)delegate;
- (id)initForAnyInstanceOfClassName:(id)name andConfiguration:(id)configuration;
- (id)initForClassName:(id)name idValue:(id)value andConfiguration:(id)configuration;
- (_Bool)ioServiceIdentifierMatches:(id)matches;
- (_Bool)ioServiceMatches:(id)matches withManager:(id)manager;

@end

#endif /* ASDTIOServiceDependency_h */
