//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 7624.2.1.1.0
//
#ifndef BETextDocumentRequest_h
#define BETextDocumentRequest_h
@import Foundation;

@class UIWKDocumentRequest;

@interface BETextDocumentRequest : NSObject

@property (readonly, nonatomic) UIWKDocumentRequest *backingDocumentRequest;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } _documentRect;
@property (retain, nonatomic) id <NSCopying> inputElementIdentifier;
@property (nonatomic) long long options;
@property (nonatomic) long long surroundingGranularity;
@property (nonatomic) long long granularityCount;

/* instance methods */
- (id)_initWithUIKitDocumentRequest:(id)request;
- (id)_uikitDocumentRequest;

@end

#endif /* BETextDocumentRequest_h */
