//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 486.0.0.0.0
//
#ifndef TSCHChartSeriesStyle_h
#define TSCHChartSeriesStyle_h
@import Foundation;

#include "TSCHBaseStyle.h"

@interface TSCHChartSeriesStyle : TSCHBaseStyle

/* class methods */
+ (id)properties;
+ (id)defaultStyleWithContext:(id)context;
+ (int)defaultIntValueForProperty:(int)property;
+ (id)defaultValueForProperty:(int)property;
+ (float)defaultFloatValueForProperty:(int)property;
+ (id)getURLForImage:(id)image;
+ (id)identifierForRoleIndex:(unsigned long long)index ordinal:(unsigned long long)ordinal;
+ (id)bootstrappedSeriesStyleWithContext:(id)context seriesIndex:(unsigned long long)index presetIndex:(unsigned long long)index;
+ (id)imageFillProperties;
+ (int)muxDefaultPropertyForSpecificProperty:(int)property;
+ (id)presetStyleDescriptorForOrdinal:(unsigned long long)ordinal;

/* instance methods */
- (void)saveToArchiver:(id)archiver;
- (id)initWithContext:(id)context name:(id)name overridePropertyMap:(id)map isVariation:(_Bool)variation;
- (void)loadFromUnarchiver:(id)unarchiver;
- (id)mixedObjectWithFraction:(double)fraction ofObject:(id)object;
- (long long)mixingTypeWithObject:(id)object context:(id)context;
- (void)p_upgrade3DFillSubclassTSDFill:(id)tsdfill;
- (void)p_upgradeBubbleChartProperties:(id)properties;
- (void)handlePreUFFUpgradesForOverridePropertyMapWithUnarchiver:(id)unarchiver;
- (void)loadFromPreUFFArchiveWithUnarchiver:(id)unarchiver;
- (void)p_upgrade3DChartProperties:(id)properties;
- (void)p_upgradeMixedChartProperties:(id)properties;
- (void)p_upgradeRadarChartProperties:(id)properties;
- (void)p_upgradeRemoveShadowEnabledPropertyUsage:(id)usage;
- (void)p_upgradeSeparateVisibilityProperties:(id)properties;

@end

#endif /* TSCHChartSeriesStyle_h */
