//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 208.6.1.0.0
//
#ifndef QLTCacheSizeEvent_h
#define QLTCacheSizeEvent_h
@import Foundation;

#include "QLTAnalyticsEventProtocol-Protocol.h"

@interface QLTCacheSizeEvent : NSObject <QLTAnalyticsEventProtocol>

@property (readonly) unsigned long long cacheSize;
@property (readonly) NSString *name;
@property (readonly) id /* block */ propertiesBuilder;

/* instance methods */
- (id)build;
- (id)initWithCacheSize:(unsigned long long)size;

@end

#endif /* QLTCacheSizeEvent_h */
