//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2360.120.2.0.0
//
#ifndef CKFetchRecordsOperation_h
#define CKFetchRecordsOperation_h
@import Foundation;

#include "CKDatabaseOperation.h"
#include "CKFetchRecordsOperationCallbacks-Protocol.h"
#include "CKFetchRecordsOperationInfo.h"
#include "CKOperationInMemoryAssets-Protocol.h"

@interface CKFetchRecordsOperation : CKDatabaseOperation <CKFetchRecordsOperationCallbacks, CKOperationInMemoryAssets> {
    /* instance variables */
    unsigned long long _mergeableValueCount;
    unsigned long long _mergeableDeltaCount;
    unsigned long long _assetBackedMergeableDeltaCount;
    NSMutableDictionary *_recordErrors;
}

@property (readonly, nonatomic) id <CKFetchRecordsOperationCallbacks> clientOperationCallbackProxy;
@property (readonly, nonatomic) CKFetchRecordsOperationInfo *operationInfo;
@property (copy, nonatomic) id /* block */ perRecordProgressBlock_wrapper;
@property (copy, nonatomic) id /* block */ perRecordCompletionBlock_wrapper;
@property (copy, nonatomic) id /* block */ perRecordETagMatchedBlock_wrapper;
@property (copy, nonatomic) id /* block */ fetchRecordsCompletionBlock_wrapper;
@property (nonatomic) _Bool isFetchCurrentUserOperation;
@property (nonatomic) _Bool shouldRequestEncryptedAssetOwnerIdentifier;
@property (retain, nonatomic) NSDictionary *webSharingIdentityDataByRecordID;
@property (nonatomic) _Bool shouldFetchAssetContent;
@property (nonatomic) _Bool shouldFetchAssetContentInMemory;
@property (nonatomic) _Bool dropInMemoryAssetContentASAP;
@property (nonatomic) _Bool shouldCloneFileInAssetCache;
@property (copy, nonatomic) NSDictionary *assetTransferOptionsByRecordTypeAndKey;
@property (retain, nonatomic) NSMutableDictionary *recordIDsToRecords;
@property (copy, nonatomic) NSDictionary *desiredPackageFileIndices;
@property (copy, nonatomic) NSDictionary *recordIDsToETags;
@property (copy, nonatomic) id /* block */ perRecordETagMatchedBlock;
@property (copy, nonatomic) NSDictionary *recordIDsToVersionETags;
@property (copy, nonatomic) NSArray *recordIDs;
@property (copy, nonatomic) NSArray *desiredKeys;
@property (copy, nonatomic) id /* block */ perRecordProgressBlock;
@property (copy, nonatomic) id /* block */ perRecordCompletionBlock;
@property (copy, nonatomic) id /* block */ fetchRecordsCompletionBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSMutableDictionary *assetInfoByArrayIndexByRecordKeyByRecordID;

/* class methods */
+ (id)fetchCurrentUserRecordOperation;
+ (SEL)daemonInvocationSelector;
+ (void)applyDaemonCallbackInterfaceTweaks:(id)tweaks;

/* instance methods */
- (void)ckSignpostEndWithError:(id)error;
- (void)ckSignpostBegin;
- (_Bool)hasCKOperationCallbacksSet;
- (void)fillOutOperationInfo:(id)info;
- (void)fillFromOperationInfo:(id)info;
- (_Bool)CKOperationShouldRun:(id *)run;
- (void)performCKOperation;
- (void)handleAssetDataForRecordID:(id)id recordKey:(id)key arrayIndex:(long long)index data:(id)data offset:(unsigned long long)offset;
- (void)_finishOnCallbackQueueWithError:(id)error;
- (void)setFetchRecordsCompletionBlockIVar:(id /* block */)ivar;
- (id)activityCreate;
- (void)handleFetchForRecordID:(id)id didProgress:(double)progress;
- (void)handleFetchForRecordID:(id)id record:(id)record error:(id)error;
- (id)init;
- (id)initWithRecordIDs:(id)ids;

@end

#endif /* CKFetchRecordsOperation_h */
