//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2360.120.2.0.0
//
#ifndef CKFlipFlopPredicateValidator_h
#define CKFlipFlopPredicateValidator_h
@import Foundation;

#include "CKObjectValidating-Protocol.h"
#include "CKPredicateValidatorInstance.h"

@interface CKFlipFlopPredicateValidator : CKPredicateValidatorInstance

@property (retain, nonatomic) id <CKObjectValidating> validator;

/* instance methods */
- (_Bool)validate:(id)validate error:(id *)error;
- (id)CKPropertiesDescription;
- (id)initWithValidator:(id)validator;

@end

#endif /* CKFlipFlopPredicateValidator_h */
