//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 496.22.0.0.0
//
#ifndef AIAudiogramFrequencyInputCell_h
#define AIAudiogramFrequencyInputCell_h
@import Foundation;

@class UIImageView, UILabel, UIStackView, UITableViewCell;

@interface AIAudiogramFrequencyInputCell : UITableViewCell

@property (retain, nonatomic) UILabel *frequencyLabel;
@property (retain, nonatomic) UIStackView *containerStackView;
@property (retain, nonatomic) UIImageView *leftEarSymbolImageView;
@property (retain, nonatomic) UIImageView *rightEarSymbolImageView;
@property (retain, nonatomic) UILabel *leftEarSensitivity;
@property (retain, nonatomic) UILabel *rightEarSensitivity;
@property (retain, nonatomic) UIStackView *leftEarStackView;
@property (retain, nonatomic) UIStackView *rightEarStackView;
@property (nonatomic) long long ear;
@property (retain, nonatomic) NSNumber *frequency;
@property (retain, nonatomic) NSNumber *hearingLevel;
@property (retain, nonatomic) NSNumber *leftHearingLevel;
@property (retain, nonatomic) NSNumber *rightHearingLevel;
@property (nonatomic) _Bool leftEarMasked;
@property (nonatomic) _Bool rightEarMasked;

/* class methods */
+ (id)reuseIdentifier;

/* instance methods */
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (id)initWithStyle:(long long)style reuseIdentifier:(id)identifier;
- (_Bool)isAccessibilityElement;
- (void)configureLayout;
- (void)_setWidth:(id)width forEar:(long long)ear;
- (id)_symbolConfigurationForSymbolType:(long long)type;
- (id)createImageViewWithImage:(id)image symbolType:(long long)type;
- (id)createLabelWithText:(id)text textColor:(id)color font:(id)font;
- (void)setLeftEarLabelWidth:(id)width;
- (void)setRightEarLabelWidth:(id)width;

@end

#endif /* AIAudiogramFrequencyInputCell_h */
