//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 534.0.0.0.0
//
#ifndef AAUserStartDateStorageType_Protocol_h
#define AAUserStartDateStorageType_Protocol_h
@import Foundation;

@protocol AAUserStartDateStorageType

@required

/* required instance methods */
- (_Bool)storeUserStartDate:(id)date isDiagnosticSubmissionAllowed:(_Bool)allowed error:(id *)error;
- (_Bool)storeUserStartDate:(id)date isDiagnosticSubmissionAllowed:(_Bool)allowed isTrackingConsentAllowed:(_Bool)allowed error:(id *)error;
- (id)userStartDateWithIsDiagnosticSubmissionAllowed:(_Bool)allowed;
- (id)userStartDateWithIsDiagnosticSubmissionAllowed:(_Bool)allowed isTrackingConsentAllowed:(_Bool)allowed;

@optional

@end

#endif /* AAUserStartDateStorageType_Protocol_h */
