//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 395.500.1.0.0
//
#ifndef AVTObservableAvatarStore_h
#define AVTObservableAvatarStore_h
@import Foundation;

#include "AVTAvatarStoreDelegate-Protocol.h"
#include "AVTAvatarStoreInternal-Protocol.h"

@protocol AVTStickerBackendDelegate, OS_dispatch_queue;

@interface AVTObservableAvatarStore : NSObject <AVTAvatarStoreInternal>

@property (readonly, nonatomic) id <AVTAvatarStoreInternal> store;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *callbackQueue;
@property (weak, nonatomic) id <AVTAvatarStoreDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <AVTStickerBackendDelegate> stickerBackendDelegate;

/* class methods */
+ (unsigned long long)maximumNumberOfFetchableAvatars;
+ (unsigned long long)maximumNumberOfSavableAvatars;

/* instance methods */
- (void)fetchAvatarsForFetchRequest:(id)request completionHandler:(id /* block */)handler;
- (id)avatarsForFetchRequest:(id)request error:(id *)error;
- (_Bool)canCreateAvatar;
- (void)deleteAvatar:(id)avatar completionHandler:(id /* block */)handler;
- (_Bool)canCreateAvatarWithError:(id *)error;
- (void)deleteAvatarWithIdentifier:(id)identifier completionBlock:(id /* block */)block;
- (void)deleteRecentStickersForChangeTracker:(id)tracker completionHandler:(id /* block */)handler;
- (void)deleteRecentStickersWithAvatarIdentifier:(id)identifier stickerIdentifier:(id)identifier completionHandler:(id /* block */)handler;
- (void)didUseStickerWithAvatarIdentifier:(id)identifier stickerIdentifier:(id)identifier completionHandler:(id /* block */)handler;
- (void)duplicateAvatar:(id)avatar completionBlock:(id /* block */)block;
- (id)recentStickersForFetchRequest:(id)request error:(id *)error;
- (void)saveAvatarRecord:(id)record thumbnailAvatar:(id)avatar completionBlock:(id /* block */)block thumbnailGenerationCompletionBlock:(id /* block */)block;
- (id)initWithStore:(id)store callbackQueue:(id)queue;

@end

#endif /* AVTObservableAvatarStore_h */
