//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3520.51.1.0.0
//
#ifndef NSSafeMutableDictionary_h
#define NSSafeMutableDictionary_h
@import Foundation;

@interface NSSafeMutableDictionary : NSMutableDictionary {
    /* instance variables */
    NSMutableDictionary *_storage;
    NSLock *_lock;
}

/* instance methods */
- (void)setObject:(id)object forKey:(id)key;
- (void)removeObjectForKey:(id)key;
- (unsigned long long)count;
- (void)removeAllObjects;
- (id)init;
- (id)keyEnumerator;
- (id)objectForKey:(id)key;

@end

#endif /* NSSafeMutableDictionary_h */
