//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 486.0.0.0.0
//
#ifndef TSDImageProvider_h
#define TSDImageProvider_h
@import Foundation;

@class TSPData, TSPObjectContext, TSUWeakReference;

@interface TSDImageProvider : NSObject {
    /* instance variables */
    int mLoadState;
    TSPData *mImageData;
    TSUWeakReference *mObjectContextReference;
    _Atomic int mRetainCount;
    _Atomic int mInterest;
}

@property (nonatomic) int i_loadState;
@property (readonly, nonatomic) _Bool i_hasFlushableContent;
@property (readonly, nonatomic) unsigned long long i_flushableMemoryEstimate;
@property (readonly, retain, nonatomic) TSPData *imageData;
@property (readonly, weak, nonatomic) TSPObjectContext *objectContext;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } naturalSize;
@property (readonly, nonatomic) unsigned long long imageGamut;
@property (readonly, nonatomic) _Bool prefersHDRRendering;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } dpiAdjustedNaturalSize;
@property (readonly, nonatomic) _Bool isValid;
@property (readonly, nonatomic) _Bool isError;

/* class methods */
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (void)flush;
- (id)retain;
- (id)initWithImageData:(id)data;
- (void)dealloc;
- (oneway void)release;
- (int)interest;
- (void)addInterest;
- (void)drawImageInContext:(struct CGContext *)context rect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)i_commonInit;
- (void)removeInterest;
- (void)i_flushIfNoOneUsing;

@end

#endif /* TSDImageProvider_h */
