//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 972.0.21.0.0
//
#ifndef SRSleepSession_h
#define SRSleepSession_h
@import Foundation;

#include "SRSampling-Protocol.h"

@interface SRSleepSession : NSObject <SRSampling, NSCopying, NSSecureCoding>

@property (retain, nonatomic) NSDate *startDate;
@property (copy, nonatomic) NSString *identifier;
@property (nonatomic) double duration;
@property (readonly, nonatomic) long long startReason;
@property (readonly, nonatomic) long long endReason;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)dealloc;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (id)binarySampleRepresentation;
- (id)initWithBinarySampleRepresentation:(id)representation metadata:(id)metadata timestamp:(double)timestamp;
- (id)initWithStartDate:(id)date identifier:(id)identifier duration:(double)duration;
- (id)initWithStartDate:(id)date startReason:(long long)reason endReason:(long long)reason identifier:(id)identifier duration:(double)duration;

@end

#endif /* SRSleepSession_h */
