//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4557.5.7.101.0
//
#ifndef _SBMainScreenActiveInterfaceOrientationWindowRootViewController_h
#define _SBMainScreenActiveInterfaceOrientationWindowRootViewController_h
@import Foundation;

@class SBFTouchPassThroughViewController, UIViewController;

@interface _SBMainScreenActiveInterfaceOrientationWindowRootViewController : SBFTouchPassThroughViewController

@property (nonatomic) unsigned long long supportedInterfaceOrientations;
@property (weak, nonatomic) UIViewController *contentViewController;

/* instance methods */
- (_Bool)shouldAutorotate;
- (_Bool)_canShowWhileLocked;
- (id)_viewControllerForSupportedInterfaceOrientationsWithDismissCheck:(_Bool)check;

@end

#endif /* _SBMainScreenActiveInterfaceOrientationWindowRootViewController_h */
