//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 455.6.0.0.0
//
#ifndef HPSSpatialProfileVideoCaptureSession_h
#define HPSSpatialProfileVideoCaptureSession_h
@import Foundation;

#include "BKUIPearlVideoCaptureSessionType-Protocol.h"

@class AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoPreviewLayer;
@protocol BKUIVideoCaptureSesssionDelegate, OS_dispatch_queue;

@interface HPSSpatialProfileVideoCaptureSession : NSObject <BKUIPearlVideoCaptureSessionType> {
    /* instance variables */
    AVCaptureSession *_captureSession;
    AVCaptureDeviceInput *_deviceInput;
    NSObject<OS_dispatch_queue> *_captureQueue;
}

@property (weak, nonatomic) id <BKUIVideoCaptureSesssionDelegate> delegate;
@property (retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer;
@property (readonly, nonatomic) double additionalPreviewScalingAllowedByCameraFormat;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)startCapture;
- (id)_frontCamera;
- (void)endCapture;

@end

#endif /* HPSSpatialProfileVideoCaptureSession_h */
