//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1166.6.7.1.1
//
#ifndef _TtP6HomeUI17WiFiPickerContext__Protocol_h
#define _TtP6HomeUI17WiFiPickerContext__Protocol_h
@import Foundation;

@protocol _TtP6HomeUI17WiFiPickerContext_

@required

/* required instance methods */
- (void)associateTo:(id)to completionHandler:(id /* block */)handler;
- (void)networkStatusWithCompletionHandler:(id /* block */)handler;
- (void)performScanWithCompletionHandler:(id /* block */)handler;
- (void)wifiPickerViewDidAppear;
- (void)wifiPickerViewDidDisappear;

@optional

@end

#endif /* _TtP6HomeUI17WiFiPickerContext__Protocol_h */
