//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1166.6.7.1.1
//
#ifndef AXUISettingsEditableTableCellWithStepperDelegate_Protocol_h
#define AXUISettingsEditableTableCellWithStepperDelegate_Protocol_h
@import Foundation;

@protocol AXUISettingsEditableTableCellWithStepperDelegate <NSObject>

@required

/* required instance methods */
- (double)valueForSpecifier:(id)specifier;
- (double)maximumValueForSpecifier:(id)specifier;
- (double)minimumValueForSpecifier:(id)specifier;
- (void)specifier:(id)specifier setValue:(double)value;
- (double)stepValueForSpecifier:(id)specifier;
- (id)stringValueForSpecifier:(id)specifier;

@optional

/* optional instance methods */
- (long long)keyboardTypeForSpecifier:(id)specifier;
- (id)unitsStringForSpecifier:(id)specifier;

@end

#endif /* AXUISettingsEditableTableCellWithStepperDelegate_Protocol_h */
