//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1166.6.7.1.1
//
#ifndef HUAnimationSettings_h
#define HUAnimationSettings_h
@import Foundation;

#include "_UIBasicAnimationFactory-Protocol.h"

@class CAMediaTimingFunction;

@interface HUAnimationSettings : NSObject <NSCopying, _UIBasicAnimationFactory>

@property (nonatomic) double duration;
@property (nonatomic) double delay;
@property (nonatomic) double speed;
@property (nonatomic) float repeatCount;
@property (readonly, nonatomic) double durationWithSpeed;
@property (retain, nonatomic) CAMediaTimingFunction *timingFunction;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)settingsWithDuration:(double)duration;
+ (id)settingsWithDuration:(double)duration curve:(long long)curve;

/* instance methods */
- (id)_basicAnimationForView:(id)view withKeyPath:(id)path;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)_timingFunctionForAnimation;
- (id)init;
- (double)interpolatedProgressForProgress:(double)progress;
- (double)interpolatedProgressForTime:(double)time;
- (id)settingsSpedUpByFactor:(double)factor;

@end

#endif /* HUAnimationSettings_h */
