//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1166.6.7.1.1
//
#ifndef HUFaceRecognitionLibraryListItemManager_h
#define HUFaceRecognitionLibraryListItemManager_h
@import Foundation;

@class HFDemoModeFaceRecognitionDataSource, HFItem, HFItemManager, HFItemProvider, HFStaticItem, HFStaticItemProvider, HFUserPhotosLibraryItemProvider, HMHome;

@interface HUFaceRecognitionLibraryListItemManager : HFItemManager

@property (retain, nonatomic) HFItem *allowFacialRecognitionItem;
@property (readonly, nonatomic) HMHome *overrideHome;
@property (retain, nonatomic) HFStaticItemProvider *staticItemProvider;
@property (retain, nonatomic) HFUserPhotosLibraryItemProvider *userPhotosLibraryItemProvider;
@property (retain, nonatomic) HFItemProvider *recentEventsItemProvider;
@property (retain, nonatomic) HFStaticItem *knownToHomeItem;
@property (retain, nonatomic) HFDemoModeFaceRecognitionDataSource *demoDataSource;
@property (retain, nonatomic) NSArray *coalescedPersonEvents;
@property (nonatomic) _Bool didSendAnalyticsEvent;
@property (nonatomic) unsigned long long recentsLimit;

/* instance methods */
- (id)initWithDelegate:(id)delegate;
- (id)_buildItemProvidersForHome:(id)home;
- (id)_buildSectionsWithDisplayedItems:(id)items;
- (id)_homeFuture;
- (id)initWithDelegate:(id)delegate sourceItem:(id)item;
- (id)initWithHome:(id)home delegate:(id)delegate;
- (void)sendAnalyticsEvent;

@end

#endif /* HUFaceRecognitionLibraryListItemManager_h */
