//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1166.6.7.1.1
//
#ifndef HUNoInternetOnPhoneBannerItemProvider_h
#define HUNoInternetOnPhoneBannerItemProvider_h
@import Foundation;

#include "HFExecutionEnvironmentObserver-Protocol.h"
#include "HUNoInternetOnPhoneBannerItemProviderDelegate-Protocol.h"

@class HFItemProvider, HMHome;

@interface HUNoInternetOnPhoneBannerItemProvider : HFItemProvider <HFExecutionEnvironmentObserver>

@property (retain, nonatomic) NSMutableSet *bannerItems;
@property (retain, nonatomic) HMHome *home;
@property (weak, nonatomic) id <HUNoInternetOnPhoneBannerItemProviderDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)items;
- (id)init;
- (id)reloadItems;
- (void)executionEnvironmentDidBecomeActive:(id)active;
- (void)executionEnvironmentDidEnterBackground:(id)background;
- (id)initWithHome:(id)home delegate:(id)delegate;
- (void)notifyChangeForNoInternetOnPhone:(_Bool)phone;
- (void)startNetworkDiagnosticsObservationOnPhone;
- (void)stopNetworkDiagnosticsObservationOnPhone;

@end

#endif /* HUNoInternetOnPhoneBannerItemProvider_h */
