//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1166.6.7.1.1
//
#ifndef HUUserAccessoryAccessItemManager_h
#define HUUserAccessoryAccessItemManager_h
@import Foundation;

@class HFItemManager, HFTransformItemProvider, HMHome, HMUser;

@interface HUUserAccessoryAccessItemManager : HFItemManager

@property (readonly, nonatomic) HMHome *overrideHome;
@property (readonly, nonatomic) HMUser *user;
@property (readonly, nonatomic) NSString *accessoryCategoryType;
@property (retain, nonatomic) HFTransformItemProvider *transformedAllowedAccessoryItemProvider;

/* instance methods */
- (id)_buildItemProvidersForHome:(id)home;
- (id)_buildSectionsWithDisplayedItems:(id)items;
- (id)_homeFuture;
- (id)initWithHome:(id)home user:(id)user accessoryCategoryType:(id)type;

@end

#endif /* HUUserAccessoryAccessItemManager_h */
