//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1166.6.7.1.1
//
#ifndef HUCameraStreamAndRecordStateInfoProvider_h
#define HUCameraStreamAndRecordStateInfoProvider_h
@import Foundation;

@class HFStaticItemProvider;

@interface HUCameraStreamAndRecordStateInfoProvider : HFStaticItemProvider

/* instance methods */
- (id)initWithDisplayStyle:(unsigned long long)style;

@end

#endif /* HUCameraStreamAndRecordStateInfoProvider_h */
