//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3864.600.51.2.1
//
#ifndef MFComposePhotoPickerProgressManager_h
#define MFComposePhotoPickerProgressManager_h
@import Foundation;

@interface MFComposePhotoPickerProgressManager : NSObject { // (Swift)
    /* instance variables */
    struct CGSize { double x0; double x1; } progresses;
}

@property (nonatomic, readonly) _Bool hasAnyProgress;

/* instance methods */
- (id)init;
- (void)cancelEverything;
- (void)cancelProgressFor:(id)_for;
- (id)progressFor:(id)_for;
- (void)setProgress:(id)progress for:(id)_for;

@end

#endif /* MFComposePhotoPickerProgressManager_h */
