//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 301.23.4.7.0
//
#ifndef ICQRemoteContaineriPadViewController_h
#define ICQRemoteContaineriPadViewController_h
@import Foundation;

#include "ICQRemoteContainerViewController.h"

@interface ICQRemoteContaineriPadViewController : ICQRemoteContainerViewController

/* instance methods */
- (id)initWithRootViewController:(id)controller;

@end

#endif /* ICQRemoteContaineriPadViewController_h */
