//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 305.0.0.0.0
//
#ifndef WGWidgetListEditViewTableViewCell_h
#define WGWidgetListEditViewTableViewCell_h
@import Foundation;

@class UIButton, UIImageView, UITableViewCell;

@interface WGWidgetListEditViewTableViewCell : UITableViewCell {
    /* instance variables */
    UIImageView *_dotImageView;
}

@property (nonatomic) _Bool widgetEnabled;
@property (nonatomic) _Bool showsDot;
@property (readonly, weak, nonatomic) UIButton *insertWidgetAccessoryButton;

/* instance methods */
- (id)initWithStyle:(long long)style reuseIdentifier:(id)identifier;
- (void)layoutSubviews;
- (_Bool)isWidgetEnabled;

@end

#endif /* WGWidgetListEditViewTableViewCell_h */
