//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1061.50.12.0.0
//
#ifndef VUILabelFactory_h
#define VUILabelFactory_h
@import Foundation;

@interface VUILabelFactory : NSObject

/* class methods */
+ (id)labelWithElement:(id)element textLayout:(id)layout existingLabel:(id)label;

@end

#endif /* VUILabelFactory_h */
