//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1061.50.12.0.0
//
#ifndef VUIMPMediaLibraryIdentifier_h
#define VUIMPMediaLibraryIdentifier_h
@import Foundation;

#include "VUIMediaLibraryIdentifier-Protocol.h"

@interface VUIMPMediaLibraryIdentifier : NSObject <VUIMediaLibraryIdentifier>

@property (copy, nonatomic) NSString *identifier;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (id)initWithIdentifier:(id)identifier;
- (_Bool)isEqual:(id)equal;

@end

#endif /* VUIMPMediaLibraryIdentifier_h */
