//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1450.600.61.2.7
//
#ifndef CKChatEagerUploadController_h
#define CKChatEagerUploadController_h
@import Foundation;

@interface CKChatEagerUploadController : NSObject

@property (retain, nonatomic) NSMutableDictionary *identifierMap;
@property (retain, nonatomic) NSMutableArray *uploadUrls;
@property (retain, nonatomic) NSMutableDictionary *temporaryURLS;

/* instance methods */
- (id)init;
- (id)_newTransferForURL:(id)url transcoderUserInfo:(id)info attributionInfo:(id)info;
- (void)_uploadFileURL:(id)url filename:(id)filename transcoderUserInfo:(id)info videoComplementURL:(id)url attributionInfo:(id)info identifier:(id)identifier recipients:(id)recipients;
- (void)addURLToIdentifierMap:(id)map forIdentifier:(id)identifier;
- (void)asyncCopyFileAtURL:(id)url toDestinationURL:(id)url completion:(id /* block */)completion;
- (void)cancelAll;
- (void)cancelIdentifier:(id)identifier;
- (void)cancelURL:(id)url;
- (void)didSendComposition;
- (void)removeTemporaryURLForURL:(id)url;
- (void)uploadFileURL:(id)url filename:(id)filename transcoderUserInfo:(id)info videoComplementURL:(id)url attributionInfo:(id)info identifier:(id)identifier recipients:(id)recipients;
- (void)uploadPayload:(id)payload identifier:(id)identifier replace:(_Bool)replace recipients:(id)recipients;

@end

#endif /* CKChatEagerUploadController_h */
