//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1450.600.61.2.7
//
#ifndef CKSendAnimationContext_h
#define CKSendAnimationContext_h
@import Foundation;

#include "CKSendAnimationContextProtocol-Protocol.h"

@class CABackdropLayer, UIImageView, UIView;

@interface CKSendAnimationContext : NSObject <CKSendAnimationContextProtocol>

@property (nonatomic) unsigned long long sendAnimationType;
@property (copy, nonatomic) NSArray *animatableViews;
@property (copy, nonatomic) NSArray *animatableTextViews;
@property (copy, nonatomic) NSArray *throwBalloonViews;
@property (copy, nonatomic) NSArray *framesOfAddedChatItems;
@property (copy, nonatomic) NSArray *throwBalloonViewAttributesCollection;
@property (retain, nonatomic) UIView *containerView;
@property (retain, nonatomic) UIView *behindGlassContainerView;
@property (copy, nonatomic) NSString *impactIdentifier;
@property (nonatomic) _Bool shouldRepeat;
@property (nonatomic) _Bool isSender;
@property (nonatomic) _Bool beginAnimationFromTranscriptPresentedState;
@property (copy, nonatomic) NSArray *messages;
@property (retain, nonatomic) CABackdropLayer *backdropLayer;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } quickReplySourceRect;
@property (readonly, nonatomic) _Bool shouldUseQuickReplySourceRect;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } throwAnimationSourceRect;
@property (nonatomic) struct CGSize { double x0; double x1; } entryViewSize;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } audioMessageSourceRect;
@property (retain, nonatomic) UIImageView *audioRecordingPillViewSnapshot;
@property (retain, nonatomic) UIView *quickReplySnapshotView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */

@end

#endif /* CKSendAnimationContext_h */
