//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1061.50.12.0.0
//
#ifndef VUIActionPromise_h
#define VUIActionPromise_h
@import Foundation;

#include "VUIAction.h"
#include "VUIAppContext.h"

@interface VUIActionPromise : VUIAction

@property (readonly, nonatomic) NSDictionary *contextDataDictionary;
@property (weak, nonatomic) VUIAppContext *appContext;

/* instance methods */
- (id)initWithContextData:(id)data appContext:(id)context;
- (void)performWithTargetResponder:(id)responder completionHandler:(id /* block */)handler;

@end

#endif /* VUIActionPromise_h */
