//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1061.50.12.0.0
//
#ifndef VUILocalNotificationService_h
#define VUILocalNotificationService_h
@import Foundation;

@interface VUILocalNotificationService : NSObject // (Swift)

/* class methods */
+ (void)requestAuthorizationWithOptions:(unsigned long long)options completionHandler:(id /* block */)handler;
+ (void)authorizationStatusWithCompletionHandler:(id /* block */)handler;
+ (void)deliverNotificationWithIdentifier:(NSString *)identifier title:(NSString *)title body:(NSString *)body options:(NSDictionary *)options completionHandler:(id /* block */)handler;
+ (void)updateBadgeCount:(long long)count completionHandler:(id /* block */)handler;

/* instance methods */
- (id)init;

@end

#endif /* VUILocalNotificationService_h */
