//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.5.11.11.1
//
#ifndef AFDataStore_AFUIDataStoring_h
#define AFDataStore_AFUIDataStoring_h
@import Foundation;

@interface AFDataStore (AFUIDataStoring) <AFUIDataStoring>

/* instance methods */
- (id)imageForKey:(id)key;
- (void)setImage:(id)image forKey:(id)key;
- (id)afui_dataStoringShim;

@end

#endif /* AFDataStore_AFUIDataStoring_h */
