//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1322.0.0.0.0
//
#ifndef AVPlayerViewController_AdLibAdditions_h
#define AVPlayerViewController_AdLibAdditions_h
@import Foundation;

@interface AVPlayerViewController (AdLibAdditions)

/* class methods */
+ (void)preparePrerollAds;

/* instance methods */
- (void)cancelPreroll;
- (void)playPrerollAdWithCompletionHandler:(id /* block */)handler;

@end

#endif /* AVPlayerViewController_AdLibAdditions_h */
