//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1289.24.0.0.0
//
#ifndef NPKProtoStandaloneUserInfo_h
#define NPKProtoStandaloneUserInfo_h
@import Foundation;

@class PBCodable;

@interface NPKProtoStandaloneUserInfo : PBCodable <NSCopying>

@property (retain, nonatomic) NSString *key;
@property (readonly, nonatomic) _Bool hasValue;
@property (retain, nonatomic) NSString *value;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (void)copyTo:(id)to;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)writeTo:(id)to;
- (id)dictionaryRepresentation;
- (id)description;
- (_Bool)isEqual:(id)equal;

@end

#endif /* NPKProtoStandaloneUserInfo_h */
