//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 774.25.0.0.0
//
#ifndef APOVehicleStatus_h
#define APOVehicleStatus_h
@import Foundation;

@interface APOVehicleStatus : NSObject <NSSecureCoding, NSCoding>

@property (nonatomic, readonly) NSArray *climateStatusItems;
@property (nonatomic, readonly) NSString *description;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (id)initWithClimateStatusItems:(id)items;

@end

#endif /* APOVehicleStatus_h */
