//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2079.120.10.0.0
//
#ifndef KeyboardBacklightHIDCurveNits_h
#define KeyboardBacklightHIDCurveNits_h
@import Foundation;

#include "KeyboardBacklightHIDCurve.h"

@interface KeyboardBacklightHIDCurveNits : KeyboardBacklightHIDCurve

@property (readonly) float level;

/* instance methods */
- (float)brightness;
- (void)setBrightness:(float)brightness;
- (void)dealloc;
- (float)convertNitsToLevelPercentage:(float)percentage;
- (id)initWithQueue:(id)queue device:(id)device;
- (float)maxCapableNits;
- (float)maxLevelPercentage;
- (float)minCapableNits;
- (void)setBrightness:(float)brightness withFadeSpeed:(int)speed commit:(_Bool)commit;

@end

#endif /* KeyboardBacklightHIDCurveNits_h */
