//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1450.600.61.2.7
//
#ifndef IMHandleStatusObserverAssertion_h
#define IMHandleStatusObserverAssertion_h
@import Foundation;

#include "IMHandle.h"

@interface IMHandleStatusObserverAssertion : NSObject

@property (readonly, weak, nonatomic) IMHandle *handle;
@property (nonatomic) _Bool valid;

/* instance methods */
- (void)invalidate;
- (void)dealloc;
- (id)initWithHandle:(id)handle;

@end

#endif /* IMHandleStatusObserverAssertion_h */
