//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1.8.5.1.0
//
#ifndef FHTransactionStatistics_h
#define FHTransactionStatistics_h
@import Foundation;

@interface FHTransactionStatistics : NSObject <NSSecureCoding>

@property (readonly, copy, nonatomic) NSArray *aggregateRecords;
@property (readonly, nonatomic) unsigned long long timeWindow;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (unsigned long long)hash;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (id)initWithTransactionAggregateRecords:(id)records timeWindow:(unsigned long long)window;

@end

#endif /* FHTransactionStatistics_h */
