//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2952.120.8.0.0
//
#ifndef NSString_ICAttributedString_h
#define NSString_ICAttributedString_h
@import Foundation;

@interface NSString (ICAttributedString)

/* class methods */
+ (id)ic_attachmentCharacterString;
+ (id)ic_calculateEqualsSignString;
+ (id)ic_ellipsisCharacterString;
+ (id)ic_equalsSignCharacterString;
+ (id)ic_fullWidthEqualsSignCharacterString;
+ (id)ic_hashtagCharacterString;
+ (_Bool)ic_isCharacterInlineAttachmentPrefix:(unsigned short)prefix;
+ (id)ic_newURLForContentID:(id)id percentEscaped:(_Bool)escaped;
+ (id)ic_thinSpaceCharacterString;
+ (id)ic_calculateGraphExpressionString;
+ (id)ic_leftToRightCharacterString;
+ (id)ic_mentionCharacterString;
+ (id)ic_nonDelimeterSet;
+ (id)ic_rightToLeftCharacterString;
+ (id)ic_shortNameFromGivenName:(id)name familyName:(id)name;

/* instance methods */
- (unsigned long long)ic_HTMLInsertionPoint;
- (id)ic_checkedSubstringWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (_Bool)ic_containsNonWhitespaceCharacters;
- (void)ic_enumerateContentLineRangesInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range usingBlock:(id /* block */)block;
- (void)ic_enumerateParagraphsInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range usingBlock:(id /* block */)block;
- (id)ic_htmlStringEscapingQuotesAndLineBreaks;
- (id)ic_leadingTrimmedString;
- (unsigned long long)ic_lengthOfLongestLine;
- (struct _NSRange { unsigned long long x0; unsigned long long x1; })ic_paragraphRangeForRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range contentEnd:(unsigned long long *)end;
- (struct _NSRange { unsigned long long x0; unsigned long long x1; })ic_range;
- (_Bool)ic_range:(struct _NSRange { unsigned long long x0; unsigned long long x1; })ic_range onlyContainsCharacterSet:(id)set;
- (_Bool)ic_rangeIsValid:(struct _NSRange { unsigned long long x0; unsigned long long x1; })valid;
- (struct _NSRange { unsigned long long x0; unsigned long long x1; })ic_safeCharacterRangeForRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)ic_sanitizedFilenameString;
- (struct _NSRange { unsigned long long x0; unsigned long long x1; })ic_sentenceRangeForRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)ic_sha256;
- (id)ic_stringByRemovingLanguageDirectionCharacters;
- (id)ic_stringByRemovingWhitespaceOnlyLines;
- (id)ic_stringByReplacingCharactersInSet:(id)set withString:(id)string;
- (id)ic_stringReplacingUnsafeHTMLCharacters;
- (id)ic_stringReplacingUnsafeXMLCharacters;
- (id)ic_substringWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)ic_tokenSafeText;
- (id)ic_trailingTrimmedString;
- (id)ic_trimmedString;
- (id)ic_truncatedStringWithMaxLength:(unsigned long long)length truncated:(_Bool *)truncated;
- (id)ic_whitespaceAndNewlineCoalescedString;
- (id)ic_withHashtagPrefix;
- (struct _NSRange { unsigned long long x0; unsigned long long x1; })_HTMLRangeOfLastTagBeforeIndex:(unsigned long long)index;
- (_Bool)ic_containsWhitespaceCharacters;
- (id)ic_nilWhenEmpty;
- (id)_HTMLTagNameClosing:(_Bool *)closing;
- (id)ic_attributedString;
- (id)ic_attributedStringByAppendingAttributedString:(id)string;
- (_Bool)ic_canConvertToTag;
- (_Bool)ic_containsAlphanumericCharacters;
- (_Bool)ic_containsHashtagPrefix;
- (_Bool)ic_containsNonWhitespaceAndAttachmentCharacters;
- (unsigned long long)ic_countOfCharactersInSet:(id)set;
- (id)ic_dataValue;
- (_Bool)ic_endsWithDelimeter:(struct _NSRange { unsigned long long x0; unsigned long long x1; })delimeter;
- (id)ic_hashtagDisplayText;
- (_Bool)ic_isCaseInsensitiveEqualToString:(id)string;
- (_Bool)ic_isLastCharacterANewline;
- (_Bool)ic_isLastCharacterInRangeANewlineForRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (_Bool)ic_isNumeric;
- (id)ic_leftToRightString;
- (struct _NSRange { unsigned long long x0; unsigned long long x1; })ic_lineRangeIgnoringLineBreakCharactersForIndex:(unsigned long long)index;
- (id)ic_md5;
- (id)ic_mentionString;
- (unsigned long long)ic_numberOfLines;
- (_Bool)ic_rangeEncapsulatesWord:(struct _NSRange { unsigned long long x0; unsigned long long x1; })word;
- (id)ic_rightToLeftString;
- (_Bool)ic_startsWithDelimeter:(struct _NSRange { unsigned long long x0; unsigned long long x1; })delimeter;
- (id)ic_stringByRemovingAttachmentCharacters;
- (id)ic_stringByReplacingCharactersInStringMap:(id)map;
- (id)ic_stringByReplacingLeadingFullWidthHashSignIfPossible;
- (id)ic_stringByReplacingNewlineCharactersWithWhiteSpace;
- (id)ic_stringByTrimmingLeadingCharactersInSet:(id)set;
- (id)ic_stringWithoutSuffix:(id)suffix;
- (id)ic_substringFromIndex:(unsigned long long)index;
- (id)ic_substringToIndex:(unsigned long long)index;
- (id)ic_uniqueWordsWithMinLength:(unsigned long long)length;
- (id)ic_withoutHashtagPrefix;

@end

#endif /* NSString_ICAttributedString_h */
