//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 193.35.2.23.2
//
#ifndef FMMapGestureRecognizer_h
#define FMMapGestureRecognizer_h
@import Foundation;

#include "FMMapGestureRecognizerDelegate-Protocol.h"

@class UIGestureRecognizer, UITouch;

@interface FMMapGestureRecognizer : UIGestureRecognizer

@property (nonatomic) struct CGPoint { double x0; double x1; } initialTouchLocation;
@property (retain, nonatomic) UITouch *previousTouch;
@property (nonatomic) struct CGPoint { double x0; double x1; } lastTouchPoint;
@property (nonatomic) double swipeThreshold;
@property (nonatomic) double velocity;
@property (nonatomic) _Bool isTrackingTouches;
@property (nonatomic) _Bool isSwipingFromTheEdge;
@property (nonatomic) _Bool isSwipingGestureEnded;
@property (nonatomic) _Bool isRTLOrientation;
@property (retain, nonatomic) NSMutableArray *otherGestures;
@property (retain, nonatomic) NSTimer *doubleTapTimer;
@property (weak, nonatomic) id <FMMapGestureRecognizerDelegate> touchDelegate;
@property (nonatomic) int touchRadius;
@property (nonatomic) _Bool isSwipeEnabled;

/* instance methods */
- (void)touchesEnded:(id)ended withEvent:(id)event;
- (void)dealloc;
- (_Bool)canBePreventedByGestureRecognizer:(id)recognizer;
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;
- (_Bool)canPreventGestureRecognizer:(id)recognizer;
- (void)reset;
- (id)init;
- (void)touchesBegan:(id)began withEvent:(id)event;
- (void)touchesMoved:(id)moved withEvent:(id)event;
- (double)distanceBetweenPointA:(struct CGPoint { double x0; double x1; })a andPointB:(struct CGPoint { double x0; double x1; })b;
- (void)finishSwipeGesture:(double)gesture;
- (void)invalidateGesture;
- (void)mapTappedTimer;

@end

#endif /* FMMapGestureRecognizer_h */
