//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1021.3.0.0.0
//
#ifndef UCAppClipCodeURLEncodingResult_h
#define UCAppClipCodeURLEncodingResult_h
@import Foundation;

@interface UCAppClipCodeURLEncodingResult : NSObject

@property (retain, nonatomic) NSURL *url;
@property (readonly, copy, nonatomic) NSString *rawEncodedBits;
@property (readonly, nonatomic) NSData *appClipCodeBytes;
@property (nonatomic) long long hostEncodedBitCount;
@property (nonatomic) long long hostEncodingFormat;
@property (nonatomic) _Bool hasPathOrQueryEncoding;
@property (nonatomic) long long templateType;
@property (nonatomic) long long subdomainType;
@property (nonatomic) long long nonTemplatePathAndQueryEncodeType;

/* class methods */
+ (id)resultWithRawEncodedBits:(id)bits appClipCodeBytes:(id)bytes;

/* instance methods */
- (id)initWithRawEncodedBits:(id)bits appClipCodeBytes:(id)bytes;

@end

#endif /* UCAppClipCodeURLEncodingResult_h */
