//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2969.120.2.0.0
//
#ifndef MBNetworkPathMonitor_h
#define MBNetworkPathMonitor_h
@import Foundation;

#include "MBCellularDataSubscriptionMonitor.h"

@protocol OS_dispatch_group, OS_dispatch_queue, OS_nw_path_monitor;

@interface MBNetworkPathMonitor : NSObject {
    /* instance variables */
    _Atomic _Bool _started;
    NSObject<OS_nw_path_monitor> *_wifiPathMonitor;
    NSObject<OS_nw_path_monitor> *_wiredPathMonitor;
    NSObject<OS_nw_path_monitor> *_cellularPathMonitor;
    struct { _Bool isMonitored; _Bool isAvailable; _Bool isExpensive; _Bool isConstrained; } _wifiPathState;
    struct { _Bool isMonitored; _Bool isAvailable; _Bool isExpensive; _Bool isConstrained; } _wiredPathState;
    struct { _Bool isMonitored; _Bool isAvailable; _Bool isExpensive; _Bool isConstrained; } _cellularPathState;
    _Bool _backupOnCellularSupportChanged;
}

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain) NSObject<OS_dispatch_group> *initialWiFiStateGroup;
@property (retain) NSObject<OS_dispatch_group> *initialWiredStateGroup;
@property (retain) NSObject<OS_dispatch_group> *initialCellularStateGroup;
@property (retain) NSObject<OS_dispatch_group> *initialBackupOnCellularSupportGroup;
@property (retain) MBCellularDataSubscriptionMonitor *dataSubscriptionMonitor;
@property (copy, nonatomic) id /* block */ networkPathUpdateHandler;
@property (copy, nonatomic) id /* block */ backupOnCellularSupportUpdateHandler;
@property (readonly) unsigned long long backupOnCellularSupport;
@property (readonly) int cellularRadioType;

/* class methods */
+ (const char *)_pathTypeStringWithPathType:(int)type;

/* instance methods */
- (void)_handleCellularStateChange:(struct { _Bool x0; _Bool x1; _Bool x2; _Bool x3; })change backupOnCellularSupport:(unsigned long long)support;
- (_Bool)_updateState:(struct { _Bool x0; _Bool x1; _Bool x2; _Bool x3; } *)state path:(id)path pathType:(int)type;
- (void)_startWiFiMonitor;
- (id)initWithQueue:(id)queue;
- (void)fetchNetworkConnectivityWithBlock:(id /* block */)block;
- (void)cancel;
- (void)_performBlock:(id /* block */)block;
- (void)_startCellularMonitor;
- (void)dealloc;
- (struct { _Bool x0; _Bool x1; _Bool x2; int x3; unsigned long long x4; })networkConnectivity;
- (void)_cancelMonitors;
- (id)init;
- (void)_handleWiFiStateChange;
- (void)start;

@end

#endif /* MBNetworkPathMonitor_h */
