//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 852.0.102.0.0
//
#ifndef _PISliderNetLiftResult_h
#define _PISliderNetLiftResult_h
@import Foundation;

#include "PISliderNetLiftResult-Protocol.h"

@class _NURenderResult;
@protocol NURenderStatistics;

@interface _PISliderNetLiftResult : _NURenderResult <PISliderNetLiftResult>

@property (copy) NSData *styleFeatureVectorData;
@property (copy) NSData *contentFeatureVectorData;
@property (readonly) id <NURenderStatistics> statistics;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */

@end

#endif /* _PISliderNetLiftResult_h */
