//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 62.0.3.0.0
//
#ifndef ULLabelKey_h
#define ULLabelKey_h
@import Foundation;

@interface ULLabelKey : NSObject <NSCopying>

@property (retain, nonatomic) NSString *name;
@property (nonatomic) unsigned long long contextLayer;
@property (retain, nonatomic) NSString *mapItemType;

/* instance methods */
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isEqual:(id)equal;
- (id)initWithName:(id)name contextLayer:(unsigned long long)layer mapItemType:(id)type;

@end

#endif /* ULLabelKey_h */
