//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1450.2.0.0.0
//
#ifndef TSAudioTimeErrorCorrelatorPostUpsampler_h
#define TSAudioTimeErrorCorrelatorPostUpsampler_h
@import Foundation;

#include "TSAudioTimeErrorCorrelator.h"

@interface TSAudioTimeErrorCorrelatorPostUpsampler : TSAudioTimeErrorCorrelator {
    /* instance variables */
    float * _channelABuffer;
    float * _scratch1Buffer;
    float * _scratch2Buffer;
    float * _correlationBuffer;
    float * _upsamplerFilterCoefficientsBuffer;
    long long _upsamplerFilterCoefficientsLength;
}

/* instance methods */
- (void)dealloc;
- (void)_makeBlock;
- (id)initWithMaxCorrelationLength:(long long)length andUpscaleFactor:(long long)factor forSamplingRate:(double)rate;

@end

#endif /* TSAudioTimeErrorCorrelatorPostUpsampler_h */
