//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 5883.0.0.0.0
//
#ifndef FCForYouQueryResult_h
#define FCForYouQueryResult_h
@import Foundation;

@interface FCForYouQueryResult : NSObject <NSCopying>

@property (readonly, copy, nonatomic) NSArray *channelDefaultSectionRequests;
@property (readonly, copy, nonatomic) NSArray *channelOtherSectionsRequests;
@property (readonly, copy, nonatomic) NSArray *topicRequests;
@property (readonly, copy, nonatomic) NSArray *paidBundleRequests;
@property (readonly, copy, nonatomic) NSArray *hiddenFeedRequests;
@property (readonly, copy, nonatomic) NSArray *sidecarRequests;
@property (readonly, copy, nonatomic) NSArray *allRequests;
@property (readonly, copy, nonatomic) NSDictionary *feedContextByFeedID;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (id)initWithChannelDefaultSectionRequests:(id)requests channelOtherSectionsRequests:(id)requests topicRequests:(id)requests paidBundleRequests:(id)requests hiddenFeedRequests:(id)requests sidecarRequests:(id)requests feedContextByFeedID:(id)id;

@end

#endif /* FCForYouQueryResult_h */
