//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2109.120.16.0.0
//
#ifndef _BGContinuedProcessingTask_h
#define _BGContinuedProcessingTask_h
@import Foundation;

#include "BGTask.h"

@interface _BGContinuedProcessingTask : BGTask

@property (copy) NSString *title;
@property (copy) NSString *reason;
@property (retain, nonatomic) NSProgress *internalProgress;
@property (copy, nonatomic) id /* block */ _progressHandler;
@property (copy, nonatomic) id /* block */ _descriptionUpdateHandler;

/* instance methods */
- (void)cancel;
- (id)description;
- (void)updateProgress:(id)progress;
- (void)updateTitle:(id)title withReason:(id)reason;
- (id)_initWithIdentifier:(id)identifier activity:(id)activity;
- (void)_setDescriptionUpdateHandler:(id /* block */)handler;
- (void)_setProgressHandler:(id /* block */)handler;
- (void)updateProgressPercentage:(double)percentage;

@end

#endif /* _BGContinuedProcessingTask_h */
