//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 578.0.0.0.0
//
#ifndef ETCanvasViewDelegate_Protocol_h
#define ETCanvasViewDelegate_Protocol_h
@import Foundation;

@protocol ETCanvasViewDelegate <NSObject>

@required

/* required instance methods */
- (long long)recentHeartRate;
- (void)canvasView:(id)view didBeginComposingMessageType:(unsigned short)type;
- (void)canvasView:(id)view didBeginPlayingMessage:(id)message;
- (void)canvasView:(id)view didEndComposingMessageType:(unsigned short)type;
- (void)canvasView:(id)view didEndPlayingMessage:(id)message;
- (void)canvasView:(id)view didUpdateComposingMessageType:(unsigned short)type;
- (void)canvasView:(id)view sendMessage:(id)message;
- (void)canvasView:(id)view willEndPlayingMessage:(id)message;
- (void)canvasViewDidBeginStroke:(id)stroke;
- (void)canvasViewDidEndStroke:(id)stroke;
- (_Bool)canvasViewShouldSendWithTimer:(id)timer;
- (void)canvasViewWillReachComposingSizeLimit:(id)limit;

@optional

/* optional instance methods */
- (void)canvasView:(id)view angerUsesForceTouch:(_Bool)touch;
- (_Bool)canvasView:(id)view tapRecognizerShouldBegin:(id)begin;
- (void)canvasViewDidEndMediaAppearance:(id)appearance;
- (void)canvasViewDidPause:(id)pause;
- (void)canvasViewDidStartMediaAppearance:(id)appearance;
- (void)canvasViewDidUnpause:(id)unpause;
- (_Bool)canvasViewShouldUseFastVerticalWisp:(id)wisp;

@end

#endif /* ETCanvasViewDelegate_Protocol_h */
