//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1642.6.5.0.0
//
#ifndef PKPerformActionViewControllerDelegate_Protocol_h
#define PKPerformActionViewControllerDelegate_Protocol_h
@import Foundation;

@protocol PKPerformActionViewControllerDelegate <NSObject>

@required

/* required instance methods */
- (void)performActionViewControllerDidCancel:(id)cancel;
- (void)performActionViewControllerDidPerformAction:(id)action;

@optional

/* optional instance methods */
- (void)performActionViewControllerDidCompleteAutoReload:(id)reload;

@end

#endif /* PKPerformActionViewControllerDelegate_Protocol_h */
