//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1642.6.5.0.0
//
#ifndef PKSuperscriptedCurrencyAmountLabel_h
#define PKSuperscriptedCurrencyAmountLabel_h
@import Foundation;

@class UIColor, UIFont, UILabel, UIView;

@interface PKSuperscriptedCurrencyAmountLabel : UIView

@property (retain, nonatomic) UILabel *label;
@property (nonatomic) struct CGSize { double x0; double x1; } lastLayedOutBoundsSize;
@property (nonatomic) double labelScaleFactor;
@property (retain, nonatomic) NSString *currencyCode;
@property (retain, nonatomic) NSDecimalNumber *amount;
@property (retain, nonatomic) UIFont *primaryFont;
@property (retain, nonatomic) UIFont *superscriptFont;
@property (retain, nonatomic) UIColor *positiveValueTextColor;
@property (retain, nonatomic) UIColor *negativeValueTextColor;
@property (nonatomic) _Bool showsPositiveValueDesignation;
@property (nonatomic) _Bool showsNegativeValueDesignation;

/* instance methods */
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)layoutSubviews;
- (void)_updateLabel;
- (void)_addSuperscriptToAttributedString:(id)string formattedCurrencyAmount:(id)amount currencyAmountWithoutSymbols:(id)symbols;
- (void)_addSuperscriptToAttributedString:(id)string inRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)_attributedString;
- (id)initWithPrimaryFont:(id)font superscriptFont:(id)font positiveValueTextColor:(id)color negativeValueTextColor:(id)color;
- (void)setAmount:(id)amount currencyCode:(id)code;

@end

#endif /* PKSuperscriptedCurrencyAmountLabel_h */
