//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 830.22.0.0.0
//
#ifndef CUNANPairingShowInfo_h
#define CUNANPairingShowInfo_h
@import Foundation;

@interface CUNANPairingShowInfo : NSObject

@property (readonly, copy, nonatomic) NSString *name;
@property (readonly, copy, nonatomic) NSString *pinCode;
@property (readonly, copy, nonatomic) NSDictionary *textInfo;

/* instance methods */
- (id)description;
- (id)initWithSubscriberInfo:(id)info pinCode:(id)code;

@end

#endif /* CUNANPairingShowInfo_h */
