//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1418.6.20.0.0
//
#ifndef HMDCameraRecordingSettingsControl_h
#define HMDCameraRecordingSettingsControl_h
@import Foundation;

#include "HMDCameraRecordingGeneralConfiguration.h"
#include "HMDCameraRecordingSelectedConfiguration.h"
#include "HMDCameraRecordingSettingsControlDelegate-Protocol.h"
#include "HMDCameraRecordingSupportedAudioConfiguration.h"
#include "HMDCameraRecordingSupportedVideoConfiguration.h"
#include "HMDCharacteristic.h"
#include "HMDFeaturesDataSource-Protocol.h"
#include "HMDHAPAccessory.h"
#include "HMDService.h"
#include "HMFLogging-Protocol.h"

@class HMFObject;
@protocol OS_dispatch_queue;

@interface HMDCameraRecordingSettingsControl : HMFObject <HMFLogging>

@property (readonly) NSObject<OS_dispatch_queue> *workQueue;
@property (readonly) HMDService *recordingService;
@property (readonly, weak) HMDHAPAccessory *accessory;
@property (readonly) NSNotificationCenter *notificationCenter;
@property (readonly, copy) NSString *clientIdentifier;
@property (readonly, copy) NSArray *videoConfigurationsByPreferenceOrder;
@property (readonly) NSMutableArray *pendingConfigureCompletionHandlers;
@property (readonly) _Bool primaryResident;
@property (readonly) _Bool configurable;
@property (readonly) HMDCharacteristic *recordingActiveCharacteristic;
@property (readonly) HMDCharacteristic *recordingSupportedGeneralConfigurationCharacteristic;
@property (readonly) HMDCharacteristic *recordingSupportedAudioConfigurationCharacteristic;
@property (readonly) HMDCharacteristic *recordingSupportedVideoConfigurationCharacteristic;
@property (readonly) HMDCharacteristic *recordingSelectedConfigurationCharacteristic;
@property _Bool canUseCachedCharacteristicValues;
@property (retain) HMDCameraRecordingGeneralConfiguration *supportedRecordingConfiguration;
@property (retain) HMDCameraRecordingSupportedVideoConfiguration *supportedVideoConfiguration;
@property (retain) HMDCameraRecordingSupportedAudioConfiguration *supportedAudioConfiguration;
@property (retain) HMDCameraRecordingSelectedConfiguration *currentSelectedConfiguration;
@property (retain) NSDictionary *recordingConfigurationOverrides;
@property (readonly) id <HMDFeaturesDataSource> featuresDataSource;
@property (readonly) _Bool cameraConfiguredForRecording;
@property (weak) id <HMDCameraRecordingSettingsControlDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)logCategory;
+ (id)audioBitRateForCodecConfiguration:(id)configuration;
+ (id)audioCodecForCodecConfiguration:(id)configuration;
+ (id)audioConfigurationsByPreferenceOrder;
+ (id)h264ProfileForCodecConfiguration:(id)configuration;
+ (_Bool)isSupportedAudioCodec:(id)codec;
+ (_Bool)isSupportedH264Profile:(id)profile;
+ (_Bool)isSupportedVideoCodec:(id)codec;
+ (id)videoCodecForCodecConfiguration:(id)configuration;

/* instance methods */
- (id)logIdentifier;
- (void)dealloc;
- (void)start;
- (_Bool)isConfigurable;
- (_Bool)isPrimaryResident;
- (id)_dataValueForCharacteristicOfType:(id)type inResponses:(id)responses;
- (id)_defaultRecordingGeneralConfiguration;
- (id)_generalRecordingConfigurationInResponses:(id)responses;
- (void)_handleCurrentIsRecordingActive:(id)active selectedConfiguration:(id)configuration;
- (void)_handleSupportedConfigurationCharacteristicsReadResponses:(id)responses;
- (void)_invokePendingConfigureCompletionHandlersWithError:(id)error;
- (void)_invokePendingConfigureCompletionHandlersWithGeneralConfiguration:(id)configuration;
- (void)_invokePendingConfigureCompletionHandlersWithGeneralConfiguration:(id)configuration error:(id)error;
- (id)_isRecordingActiveValueInResponses:(id)responses;
- (id)_numberValueForCharacteristicOfType:(id)type inResponses:(id)responses;
- (id)_preferredAudioConfigurationOverride;
- (id)_preferredVideoConfigurationOverride;
- (void)_readCameraRecordingActiveSetting;
- (void)_readCameraRecordingSettings;
- (void)_readSupportedCameraRecordingConfiguration;
- (id)_recordingAudioConfiguration;
- (id)_recordingGeneralConfiguration;
- (id)_recordingVideoConfiguration;
- (id)_selectedRecordingConfigurationInResponses:(id)responses;
- (void)_setSelectedRecordingConfiguration:(id)configuration;
- (_Bool)_shouldReconfigureForChangedCharacteristic:(id)characteristic;
- (id)_supportedAudioConfigurationInResponses:(id)responses;
- (id)_supportedVideoConfigurationInResponses:(id)responses;
- (void)_updateSelectedRecordingConfiguration:(id)configuration;
- (void)_writeCameraRecordingSettings;
- (id)characteristicsToMonitor;
- (void)configureCameraRecordingSettings;
- (void)configureCameraRecordingSettingsWithCompletion:(id /* block */)completion;
- (void)enableCharacteristicNotifications;
- (void)handleAccessoryConnectedNotification:(id)notification;
- (void)handleAccessoryDisconnectedNotification:(id)notification;
- (void)handleAccessoryIsNotConfiguredError;
- (void)handleCharacteristicsChangedNotification:(id)notification;
- (void)handleCharacteristicsUpdatedNotification:(id)notification;
- (void)handleHomePersonManagerSettingsDidChangeNotification:(id)notification;
- (id)initWithWorkQueue:(id)queue accessory:(id)accessory recordingManagementService:(id)service;
- (id)initWithWorkQueue:(id)queue accessory:(id)accessory recordingManagementService:(id)service featuresDataSource:(id)source notificationCenter:(id)center;
- (_Bool)isCameraConfiguredForRecording;
- (void)reconfigureCameraRecordingSettingsWithReason:(id)reason;

@end

#endif /* HMDCameraRecordingSettingsControl_h */
