//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1418.6.20.0.0
//
#ifndef MKFAnalysisEventBulletinRegistrationPublicExtensions_Protocol_h
#define MKFAnalysisEventBulletinRegistrationPublicExtensions_Protocol_h
@import Foundation;

@protocol MKFAnalysisEventBulletinRegistrationPublicExtensions

@required

/* class methods */
+ (id)modelIDForParentRelationshipTo:(id)to;

@optional

@end

#endif /* MKFAnalysisEventBulletinRegistrationPublicExtensions_Protocol_h */
