//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1418.6.20.0.0
//
#ifndef MKFMatterAttributeValueEvent_Protocol_h
#define MKFMatterAttributeValueEvent_Protocol_h
@import Foundation;

#include "MKFHome-Protocol.h"
#include "MKFMatterAttributeEvent-Protocol.h"
#include "MKFMatterAttributeValueEventDatabaseID.h"
#include "MKFMatterAttributeValueEventPublicExtensions-Protocol.h"

@protocol MKFMatterAttributeValueEvent <MKFMatterAttributeEvent, MKFMatterAttributeValueEventPublicExtensions>

@required

@property (retain, nonatomic) NSObject *eventValue;
@property (readonly, copy, nonatomic) MKFMatterAttributeValueEventDatabaseID *databaseID;
@property (readonly) id <MKFHome> home;

@optional

@end

#endif /* MKFMatterAttributeValueEvent_Protocol_h */
