//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.1.2.0.0
//
#ifndef _TtC18SiriSuggestionsKit23DefaultSignalSubscriber_h
#define _TtC18SiriSuggestionsKit23DefaultSignalSubscriber_h
@import Foundation;

@class _$sSD -> SiriSuggestionsKit.SignalLookupKey _$sSa -> SiriSuggestionsKit.CandidateSuggestionConfigurator _$sG, _TtCs12_SwiftObject;

@interface _TtC18SiriSuggestionsKit23DefaultSignalSubscriber : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSD -> SiriSuggestionsKit.SignalLookupKey _$sSa -> SiriSuggestionsKit.CandidateSuggestionConfigurator _$sG signalSubscriptions;
}

@end

#endif /* _TtC18SiriSuggestionsKit23DefaultSignalSubscriber_h */
