//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 13.5.1.0.0
//
#ifndef GCGenericDeviceModel_DeviceDelegate_h
#define GCGenericDeviceModel_DeviceDelegate_h
@import Foundation;

@interface GCGenericDeviceModel (DeviceDelegate) <_GCDefaultPhysicalDeviceDelegate, _GCDefaultLogicalDeviceDelegate>

/* class methods */
+ (id)defaultLocalizedNameForElement:(id)element;
+ (id)defaultSymbolNameForElement:(id)element;
+ (_Bool)elementsMakeValidExtendedGamepad:(id)gamepad;
+ (_Bool)elementsMakeValidGamepad:(id)gamepad;

/* instance methods */
- (_Bool)logicalDevice:(id)device getSystemButtonName:(out id *)name sfSymbolName:(out id *)name needsMFiCompatibility:(_Bool *)compatibility;
- (id)logicalDevice:(id)device makeControllerMotionWithIdentifier:(id)identifier;
- (id)physicalDeviceGetHapticCapabilityGraph:(id)graph;
- (_Bool)physicalDeviceSupportsMotion:(id)motion;
- (id)logicalDevice:(id)device makeControllerInputDescriptionWithIdentifier:(id)identifier bindings:(id)bindings;
- (id)physicalDeviceGetHapticCapabilities:(id)capabilities;
- (_Bool)respondsToSelector:(SEL)selector;
- (id)logicalDeviceControllerProductCategory:(id)category;
- (id)logicalDevice:(id)device makeControllerPhysicalInputProfileWithIdentifier:(id)identifier;
- (void)physicalDevice:(id)device setSensorsActive:(_Bool)active;
- (id)logicalDevice:(id)device makeControllerPhysicalInputProfileDescriptionWithIdentifier:(id)identifier bindings:(id)bindings;
- (Class)logicalDeviceControllerDescriptionClass:(id)_class;
- (_Bool)logicalDeviceControllerIsAttachedToHost:(id)host;
- (id)logicalDeviceControllerVendorName:(id)name;
- (void)physicalDevice:(id)device getSensorsActiveWithReply:(id /* block */)reply;

@end

#endif /* GCGenericDeviceModel_DeviceDelegate_h */
