//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 822.5.2.0.0
//
#ifndef TPSTipsManager_h
#define TPSTipsManager_h
@import Foundation;

#include "TPSDeviceProfileDataSource-Protocol.h"
#include "TPSNotificationController.h"
#include "TPSWidgetControllerDelegate-Protocol.h"

@class TPSExperiment, TPSTipStatusController, TPSWidgetController;
@protocol OS_dispatch_queue, TPSTipsManagerDelegate;

@interface TPSTipsManager : NSObject <TPSWidgetControllerDelegate, TPSDeviceProfileDataSource>

@property (nonatomic) _Bool contextualTipsInactive;
@property (retain, nonatomic) TPSTipStatusController *tipStatusController;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *syncQueue;
@property (retain, nonatomic) NSMutableArray *sessionItems;
@property (copy, nonatomic) TPSExperiment *experiment;
@property (copy, nonatomic) NSString *rulesVersion;
@property (retain, nonatomic) TPSWidgetController *widgetController;
@property (weak, nonatomic) id <TPSTipsManagerDelegate> delegate;
@property (retain, nonatomic) NSDictionary *cachedUserGuideMap;
@property (retain, nonatomic) NSString *lastFetchedLanguage;
@property (retain, nonatomic) TPSNotificationController *notificationController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)deviceLocalesContainLanguage:(id)language;
+ (id)rulesVersion;
+ (id)experiment;
+ (_Bool)supportsFeaturedCollection;
+ (id)immediateNotificationIdentifierForType:(unsigned long long)type;
+ (_Bool)tipKitProcessingEligible;
+ (_Bool)needImmediateNotificationForType:(unsigned long long)type;
+ (void)presentReentryNotificationIfNeeded;
+ (void)removeWidgetUpdateDate;
+ (void)removeWelcomeDocumentCache;
+ (void)removeExperimentCache;

/* instance methods */
- (id)processUserGuidesFromContentPackage:(id)package;
- (id)updatedHMTCollectionSectionMapFromMap:(id)map featuredCollections:(id)collections;
- (_Bool)isHardwareWelcome;
- (id)collectionSectionsFromCollectionMap:(id)map exclude:(id)exclude;
- (id)buildCollectionLabelLookupMap:(id)map;
- (id)createFilteredPayload:(id)payload withTipIds:(id)ids fromTipDeliveryInfoMap:(id)map;
- (void)contentWithMetaDictionary:(id)dictionary documentsDictionary:(id)dictionary processTipKitContent:(_Bool)content contextualEligibility:(_Bool)eligibility widgetEligibility:(_Bool)eligibility notificationEligibility:(_Bool)eligibility userGuideEligibility:(_Bool)eligibility preferredNotificationIdentifiers:(id)identifiers completionHandler:(id /* block */)handler;
- (id)filteredPayload:(id)payload forDocumentIds:(id)ids;
- (id)collectionStatusForCollection:(id)collection;
- (void)_updatePauseStatus:(_Bool)status;
- (void)requestWithURL:(id)url identifier:(id)identifier attributionIdentifier:(id)identifier requestType:(id)type priority:(float)priority shouldDeferBlock:(id /* block */)block completionHandler:(id /* block */)handler;
- (_Bool)widgetController:(id)controller validForDocument:(id)document documentDeliveryInfoMap:(id)map deliveryInfoMap:(id)map;
- (id)featureCollectionFromCollectionMap:(id)map collectionOrder:(id)order tipMap:(id)map;
- (void)deleteAllSearchableItemsWithCompletionHandler:(id /* block */)handler;
- (id)filteredPayload:(id)payload forCollectionIds:(id)ids;
- (id)hmtFeaturedCollectionsWithCollectionMap:(id)map collectionDeliveryInfoMap:(id)map deliveryInfoMap:(id)map;
- (id)welcomeDocumentFromContentPackage:(id)package;
- (void)updateContentIfOverrideImmediately:(_Bool)immediately;
- (id)collectionSectionsWithEligibleCollectionSections:(id)sections collectionSectionMap:(id)map featuredCollection:(id)collection;
- (id)categorizedMapWithDocumentMap:(id)map;
- (void)contentFromOrigin:(_Bool)origin systemEducationRequest:(_Bool)request processTipKitContent:(_Bool)content contextualEligibility:(_Bool)eligibility widgetEligibility:(_Bool)eligibility notificationEligibility:(_Bool)eligibility preferredNotificationIdentifiers:(id)identifiers shouldDeferBlock:(id /* block */)block limitToCollectionIds:(id)ids limitToDocumentIds:(id)ids completionHandler:(id /* block */)handler;
- (void)processClientConditions:(id)conditions targetingCache:(id)cache completionHandler:(id /* block */)handler;
- (id)initWithTipStatusController:(id)controller;
- (void)contentForVariantIdentifiers:(id)identifiers completionHandler:(id /* block */)handler;
- (void)reindexAllSearchableItemsWithCompletionHandler:(id /* block */)handler;
- (id)collectionSectionMapWithCollections:(id)collections availableCollectionSections:(id)sections collectionIdToCollectionLabelMap:(id)map;
- (id)extractTipIdsFromCollections:(id)collections usingLookupMap:(id)map;
- (void)reindexSearchableItemsWithIdentifiers:(id)identifiers completionHandler:(id /* block */)handler;
- (id)updateDocumentContent:(id)content withClientConditions:(id)conditions metadata:(id)metadata checklistCompletedConditions:(id)conditions usingDictionary:(id)dictionary;
- (void)processTipDocumentsDictionary:(id)dictionary completionHandler:(id /* block */)handler;
- (void)_updateExperimentCache;
- (void)updateSupplementalIdentifiersForIdentifier:(id)identifier fromDictionary:(id)dictionary;
- (void)clearCachedUserGuides;
- (void)userGuideMapWithUserGuideCollection:(id)collection tipMap:(id)map completionHandler:(id /* block */)handler;
- (void)processCollection:(id)collection collectionsMap:(id)map deliveryInfoMap:(id)map ignoreSection:(_Bool)section completionHandler:(id /* block */)handler;
- (_Bool)checklistCollectionHasMinSuggestedTips:(id)tips tipMap:(id)map;
- (void)processTipsDeliveryInfo:(id)info deliveryInfoMap:(id)map targetingCache:(id)cache completionHandler:(id /* block */)handler;
- (_Bool)shouldPerformWidgetUpdate;
- (void)finalEligibleContentWithCollectionData:(id)data tipData:(id)data deliveryInfoMap:(id)map metadata:(id)metadata completionHandler:(id /* block */)handler;
- (_Bool)hasWidgetDocument;
- (id)welcomeCollectionFromContentPackage:(id)package;
- (_Bool)isContentIdentifierHoldoutCamp:(id)camp;

@end

#endif /* TPSTipsManager_h */
