//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1452.4.2.0.0
//
#ifndef SSItemOffer_h
#define SSItemOffer_h
@import Foundation;

#include "SSDialog.h"
#include "SSItem.h"
#include "SSItemMedia.h"
#include "SSNetworkConstraints.h"

@interface SSItemOffer : NSObject <NSCopying> {
    /* instance variables */
    SSItem *_item;
    NSMutableDictionary *_offerDictionary;
}

@property (nonatomic) SSItem *_offerItem;
@property (readonly, nonatomic) NSSet *accountIdentifiers;
@property (readonly, nonatomic) NSString *actionType;
@property (readonly, nonatomic) long long estimatedDiskSpaceNeeded;
@property (readonly, nonatomic) id requiredSoftwareCapabilities;
@property (readonly, nonatomic) _Bool shouldShowPlusIcon;
@property (readonly, nonatomic) NSString *offerIdentifier;
@property (readonly, nonatomic) NSString *buyParameters;
@property (readonly, nonatomic) NSString *priceDisplay;
@property (readonly, nonatomic) NSString *actionDisplayName;
@property (readonly, nonatomic) _Bool oneTapOffer;
@property (readonly, nonatomic) _Bool preorder;
@property (readonly, nonatomic) SSItemMedia *offerMedia;
@property (readonly, nonatomic) SSDialog *confirmationDialog;
@property (readonly, nonatomic) SSDialog *successDialog;
@property (readonly, nonatomic) NSArray *supportedDevices;
@property (readonly, nonatomic) SSNetworkConstraints *networkConstraints;

/* class methods */
+ (id)_preferredOfferIdentifiers;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)dealloc;
- (_Bool)isPreorder;
- (id)valueForProperty:(id)property;
- (id)init;
- (id)description;
- (id)allowedToneStyles;
- (id)documentCannotOpenDialog;
- (id)documentRequiredHandlers;
- (id)documentUTI;
- (id)initWithOfferIdentifier:(id)identifier dictionary:(id)dictionary;
- (_Bool)isOneTapOffer;
- (id)playableMedia;
- (void)_setOfferItem:(id)item;

@end

#endif /* SSItemOffer_h */
