//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4557.5.7.101.0
//
#ifndef SBAbstractWindowSceneDelegate_h
#define SBAbstractWindowSceneDelegate_h
@import Foundation;

#include "BSInvalidatable-Protocol.h"
#include "FBSDisplayLayoutPublishing-Protocol.h"
#include "SBAlertItemsController.h"
#include "SBAmbientPresentationController.h"
#include "SBAssistantSceneControlling-Protocol.h"
#include "SBCommandTabController.h"
#include "SBControlCenterController.h"
#include "SBCoverSheetPresentationManager.h"
#include "SBDisplayAppInteractionEventSource.h"
#include "SBFSecureDisplayStateProviding-Protocol.h"
#include "SBFloatingDockController.h"
#include "SBHardwareButtonBezelEffectsCoordinator.h"
#include "SBHardwareButtonZStackClient.h"
#include "SBHomeAffordanceInteractionManager.h"
#include "SBHomeScreenController.h"
#include "SBIconController.h"
#include "SBLayoutStateTransitionCoordinator.h"
#include "SBLockScreenManager.h"
#include "SBLockStateProviding-Protocol.h"
#include "SBLockedPointerManager.h"
#include "SBMainDisplayLayoutStateManager.h"
#include "SBMedusaHostedKeyboardWindowController.h"
#include "SBMenuBarManager.h"
#include "SBModalAlertPresentationCoordinator.h"
#include "SBModalLibraryController.h"
#include "SBModalUIFluidDismissGestureManager.h"
#include "SBReachabilitySceneOffsetProviding-Protocol.h"
#include "SBRecordingIndicatorManager.h"
#include "SBSceneLayoutStateProvider.h"
#include "SBSceneManager.h"
#include "SBSwitcherController.h"
#include "SBSystemApertureController.h"
#include "SBSystemGestureManager.h"
#include "SBSystemPointerInteractionManager.h"
#include "SBTraitsPipelineManager.h"
#include "SBTransientOverlayPresenting-Protocol.h"
#include "SBTransientUIInteractionManager.h"
#include "SBUICommandValidating-Protocol.h"
#include "SBWallpaperController.h"
#include "SBWindowHidingManager.h"
#include "SBWindowScene.h"
#include "SBWindowSceneAccessorySceneProvider.h"
#include "SBWindowSceneContext.h"
#include "SBWindowSceneContextProviding-Protocol.h"
#include "SBWindowSceneDelegate-Protocol.h"
#include "SBWindowScenePIPManager.h"
#include "SSKDisplayEndpointDelegate-Protocol.h"

@class BNBannerController, CSCoverSheetViewController, SBFZStackResolver, TRAArbiter, UIWindow;
@protocol SBFAuthenticationStatusProvider;

@interface SBAbstractWindowSceneDelegate : NSObject <SBWindowSceneContextProviding, SBWindowSceneDelegate, SSKDisplayEndpointDelegate> {
    /* instance variables */
    SBTraitsPipelineManager *_pipelineManager;
    SBHardwareButtonZStackClient *_hardwareButtonZStackClient;
    SBWindowSceneContext *_windowSceneContext;
    id <BSInvalidatable> _pointerAssertion;
    _Bool _invalidated;
}

@property (readonly, nonatomic) SBAlertItemsController *alertItemsController;
@property (readonly, nonatomic) SBAmbientPresentationController *ambientPresentationController;
@property (readonly, nonatomic) SBDisplayAppInteractionEventSource *appInteractionEventSource;
@property (readonly, nonatomic) id <SBAssistantSceneControlling> assistantController;
@property (readonly, nonatomic) id <SBFAuthenticationStatusProvider> authenticationStatusProvider;
@property (readonly, nonatomic) BNBannerController *bannerController;
@property (readonly, nonatomic) SBControlCenterController *controlCenterController;
@property (readonly, nonatomic) SBCoverSheetPresentationManager *coverSheetPresentationManager;
@property (readonly, nonatomic) CSCoverSheetViewController *coverSheetViewController;
@property (readonly, nonatomic) id <FBSDisplayLayoutPublishing> displayLayoutPublisher;
@property (readonly, nonatomic) SBFloatingDockController *floatingDockController;
@property (readonly, nonatomic) SBHomeAffordanceInteractionManager *homeAffordanceInteractionManager;
@property (readonly, nonatomic) SBHomeScreenController *homeScreenController;
@property (readonly, nonatomic) SBSceneLayoutStateProvider *layoutStateProvider;
@property (readonly, nonatomic) SBMainDisplayLayoutStateManager *layoutStateManager;
@property (readonly, nonatomic) SBLayoutStateTransitionCoordinator *layoutStateTransitionCoordinator;
@property (readonly, nonatomic) SBLockedPointerManager *lockedPointerManager;
@property (readonly, nonatomic) SBLockScreenManager *lockScreenManager;
@property (readonly, nonatomic) SBMedusaHostedKeyboardWindowController *medusaHostedKeyboardWindowController;
@property (readonly, nonatomic) id <SBLockStateProviding> uiLockStateProvider;
@property (readonly, nonatomic) SBModalAlertPresentationCoordinator *modalAlertPresentationCoordinator;
@property (readonly, nonatomic) SBModalLibraryController *modalLibraryController;
@property (readonly, nonatomic) SBModalUIFluidDismissGestureManager *modalUIFluidDismissGestureManager;
@property (readonly, nonatomic) SBWindowScenePIPManager *pictureInPictureManager;
@property (readonly, nonatomic) id <SBReachabilitySceneOffsetProviding> reachabilitySceneOffsetProvider;
@property (readonly, nonatomic) SBRecordingIndicatorManager *recordingIndicatorManager;
@property (readonly, nonatomic) id <SBFSecureDisplayStateProviding> secureDisplayStateProvider;
@property (readonly, nonatomic) SBSwitcherController *switcherController;
@property (readonly, nonatomic) SBSystemApertureController *systemApertureController;
@property (readonly, nonatomic) SBSystemGestureManager *systemGestureManager;
@property (readonly, nonatomic) SBSystemPointerInteractionManager *systemPointerInteractionManager;
@property (readonly, nonatomic) TRAArbiter *traitsArbiter;
@property (readonly, nonatomic) SBTraitsPipelineManager *traitsPipelineManager;
@property (readonly, nonatomic) id <SBTransientOverlayPresenting> transientOverlayPresenter;
@property (readonly, nonatomic) SBWallpaperController *wallpaperController;
@property (readonly, nonatomic) SBWindowHidingManager *windowHidingManager;
@property (readonly, nonatomic) SBFZStackResolver *zStackResolver;
@property (readonly, nonatomic) SBTransientUIInteractionManager *transientUIInteractionManager;
@property (readonly, nonatomic) id <SBUICommandValidating> commandValidator;
@property (readonly, nonatomic) SBHardwareButtonBezelEffectsCoordinator *hardwareButtonBezelEffectsCoordinator;
@property (readonly, nonatomic) SBIconController *iconController;
@property (readonly, nonatomic) SBCommandTabController *commandTabController;
@property (readonly, nonatomic) SBMenuBarManager *menuBarManager;
@property (readonly, nonatomic) SBSceneManager *sceneManager;
@property (readonly, nonatomic) SBWindowSceneAccessorySceneProvider *accessorySceneProvider;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) SBWindowScene *windowScene;
@property (retain, nonatomic) UIWindow *window;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)scene:(id)scene willConnectToSession:(id)session options:(id)options;
- (void)_windowScene:(id)scene windowWillBecomeVisible:(id)visible;
- (void)sceneDidDisconnect:(id)disconnect;
- (double)_windowScene:(id)scene levelForWindow:(id)window preferredLevel:(double)level;
- (id)_sceneManagerForConnectingWindowScene:(id)scene;
- (id)_pipelineManager;
- (_Bool)_isWindowContentVisible:(id)visible;
- (_Bool)_shouldManageParticipantWithRole:(id)role;
- (void)_setParticipant:(id)participant forWindow:(id)window;
- (id)_displayLayoutPublisherForWindowScene:(id)scene;
- (void)_commonSceneSetupForScene:(id)scene;
- (id)_createTraitsArbiterWithPipelineManager:(id)manager;
- (void)_windowScene:(id)scene windowWillAttach:(id)attach;
- (void)dealloc;
- (id)_traitsDelegateForWindowRole:(id)role;
- (id)_sbWindowSceneContext;
- (void)_windowScene:(id)scene windowWillBecomeHidden:(id)hidden;
- (id)_acquireParticipantForWindow:(id)window reason:(id)reason;
- (_Bool)_shouldHandleWindowWillBecomeHiddenForRole:(id)role;
- (void)windowScene:(id)scene didUpdateCoordinateSpace:(id)space interfaceOrientation:(long long)orientation traitCollection:(id)collection;
- (id)init;
- (void)_windowScene:(id)scene window:(id)window didUpdateSupportedInterfaceOrientations:(unsigned long long)orientations preferredOrientation:(long long)orientation;
- (void)_windowScene:(id)scene windowWillDetach:(id)detach;
- (void)_windowScene:(id)scene windowDidBecomeVisible:(id)visible;
- (void)_configureForConnectingWindowScene:(id)scene windowSceneContext:(id)context;
- (id)_participantForWindow:(id)window;
- (void)_configureNewPresentationBinderForWindowScene:(id)scene sceneManager:(id)manager;
- (_Bool)isInvalidated;
- (void)setInvalidated:(_Bool)invalidated;

@end

#endif /* SBAbstractWindowSceneDelegate_h */
