//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4557.5.7.101.0
//
#ifndef SBBacklightStudyLogger_h
#define SBBacklightStudyLogger_h
@import Foundation;

#include "SBBacklightController.h"
#include "SBBacklightControllerObserver-Protocol.h"

@class SLGLog;

@interface SBBacklightStudyLogger : NSObject <SBBacklightControllerObserver> {
    /* instance variables */
    SLGLog *_logger;
    SBBacklightController *_controller;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (void)backlightController:(id)controller didAnimateBacklightToFactor:(float)factor source:(long long)source;
- (id)initWithController:(id)controller;

@end

#endif /* SBBacklightStudyLogger_h */
