//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4557.5.7.101.0
//
#ifndef SBDeviceApplicationSceneEntity_h
#define SBDeviceApplicationSceneEntity_h
@import Foundation;

#include "SBApplicationSceneEntity.h"
#include "SBDeviceApplicationSceneHandle.h"

@interface SBDeviceApplicationSceneEntity : SBApplicationSceneEntity

@property (readonly, nonatomic) SBDeviceApplicationSceneHandle *sceneHandle;

/* class methods */
+ (id)newEntityWithApplicationForMainDisplay:(id)display;
+ (id)entityWithApplication:(id)application scenePersistenceIdentifier:(id)identifier sceneHandleProvider:(id)provider displayIdentity:(id)identity;
+ (id)newEntityWithApplication:(id)application sceneHandleProvider:(id)provider displayIdentity:(id)identity;
+ (id)defaultEntityWithApplication:(id)application targetContentIdentifier:(id)identifier sceneHandleProvider:(id)provider displayIdentity:(id)identity;
+ (id)defaultEntityWithApplicationForMainDisplay:(id)display;
+ (id)entityWithApplicationForMainDisplay:(id)display withScenePersistenceIdentifier:(id)identifier;
+ (id)defaultEntityWithApplicationForMainDisplay:(id)display targetContentIdentifier:(id)identifier;
+ (id)defaultEntityWithApplication:(id)application sceneHandleProvider:(id)provider displayIdentity:(id)identity;

/* instance methods */
- (id)initWithApplication:(id)application uniqueIdentifier:(id)identifier sceneHandleProvider:(id)provider displayIdentity:(id)identity;
- (id)supportedLayoutRoles;
- (id)initWithApplicationForMainDisplay:(id)display;
- (id)initWithApplicationForMainDisplay:(id)display generatingNewSceneIfRequiredWithSpecification:(id)specification;
- (_Bool)wantsExclusiveForeground;
- (id)initWithApplicationForMainSecureDisplay:(id)display;
- (id)deviceApplicationSceneEntity;
- (id)initWithApplication:(id)application generatingNewPrimarySceneIfRequired:(_Bool)required sceneHandleProvider:(id)provider displayIdentity:(id)identity;
- (id)initWithApplication:(id)application generatingNewSceneIfRequiredWithSpecification:(id)specification sceneHandleProvider:(id)provider displayIdentity:(id)identity;
- (id)initWithApplicationSceneHandle:(id)handle;
- (_Bool)isDeviceApplicationSceneEntity;
- (_Bool)supportsPresentationAtAnySize;
- (Class)viewControllerClass;
- (_Bool)supportsSplitView;
- (id)initWithApplicationForMainDisplay:(id)display targetContentIdentifier:(id)identifier;
- (id)initWithApplication:(id)application targetContentIdentifier:(id)identifier sceneHandleProvider:(id)provider displayIdentity:(id)identity;
- (id)initWithApplication:(id)application sceneHandleProvider:(id)provider displayIdentity:(id)identity;
- (id)initWithApplicationForMainDisplay:(id)display generatingNewPrimarySceneIfRequired:(_Bool)required;
- (id)initWithApplicationForMainDisplay:(id)display uniqueIdentifier:(id)identifier;
- (id)initWithApplication:(id)application uniqueIdentifier:(id)identifier targetContentIdentifier:(id)identifier sceneHandleProvider:(id)provider displayIdentity:(id)identity;

@end

#endif /* SBDeviceApplicationSceneEntity_h */
