//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1397.600.2.0.0
//
#ifndef CNLaunchServices_h
#define CNLaunchServices_h
@import Foundation;

#include "CNLaunchServicesAdapter-Protocol.h"

@protocol OS_os_log;

@interface CNLaunchServices : NSObject

@property (retain, nonatomic) id <CNLaunchServicesAdapter> adapter;
@property (retain, nonatomic) NSObject<OS_os_log> *log;

/* instance methods */
- (id)initWithAdapter:(id)adapter;
- (id)applicationForBundleIdentifier:(id)identifier;
- (id)applicationsAvailableForHandlingURLScheme:(id)urlscheme;
- (void)openSensitiveURLInBackground:(id)background withOptions:(id)options completionHandler:(id /* block */)handler;
- (id)applicationsAvailableForDefaultAppCategory:(unsigned long long)category;
- (id)defaultApplicationForDefaultAppCategory:(unsigned long long)category;
- (id)init;
- (id)applicationsForUserActivityType:(id)type;
- (void)openUserActivityData:(id)data inApplication:(id)application completionHandler:(id /* block */)handler;

@end

#endif /* CNLaunchServices_h */
