//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 664.5.28.100.0
//
#ifndef _TtC9ChronoKit18ReloadStateService_h
#define _TtC9ChronoKit18ReloadStateService_h
@import Foundation;

@class ChronoKit.ReloadStatePersisting, ChronoKit.UnfairLock, _$sSD -> ChronoKit._ReloadStateKey ChronoKit._ReloadState, _TtCs12_SwiftObject;

@interface _TtC9ChronoKit18ReloadStateService : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    ChronoKit.ReloadStatePersisting _persistenceStore;
    ChronoKit.UnfairLock _lock;
    _$sSD -> ChronoKit._ReloadStateKey ChronoKit._ReloadState _lock_reloadState;
}

@end

#endif /* _TtC9ChronoKit18ReloadStateService_h */
