//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1450.600.61.2.7
//
#ifndef _TtC6IMCore43IMServiceReachabilityControllerLiveDelegate_h
#define _TtC6IMCore43IMServiceReachabilityControllerLiveDelegate_h
@import Foundation;

#include "IMServiceReachabilityControllerDelegate-Protocol.h"

@class _TtCs12_SwiftObject;

@interface _TtC6IMCore43IMServiceReachabilityControllerLiveDelegate : _TtCs12_SwiftObject <IMServiceReachabilityControllerDelegate> // (Swift)

@property (nonatomic, readonly) NSArray *serviceNamesForSending;
@property (nonatomic, readonly) long long taskDeadlineSeconds;

/* instance methods */
- (void)calculateReachabilityWithRequest:(id)request responseHandler:(id)handler;
- (id)preconditionsForServiceName:(id)name;
- (id)preferredAccountIDForServiceName:(id)name;
- (long long)sortOrderForServiceName:(id)name;

@end

#endif /* _TtC6IMCore43IMServiceReachabilityControllerLiveDelegate_h */
