//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4557.5.7.101.0
//
#ifndef SBSOSMigrationHomeScreenLayoutItem_h
#define SBSOSMigrationHomeScreenLayoutItem_h
@import Foundation;

#include "SBSOSMigrationHomeScreenLeafItem-Protocol.h"

@interface SBSOSMigrationHomeScreenLayoutItem : NSObject <NSSecureCoding>

@property (readonly, nonatomic) long long identifier;
@property (readonly, nonatomic) unsigned long long rowIndex;
@property (readonly, nonatomic) unsigned long long columnIndex;
@property (readonly, copy, nonatomic) id <SBSOSMigrationHomeScreenLeafItem> item;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)appendDescriptionToStream:(id)stream;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)description;
- (id)initWithIdentifier:(long long)identifier rowIndex:(unsigned long long)index columnIndex:(unsigned long long)index item:(id)item;

@end

#endif /* SBSOSMigrationHomeScreenLayoutItem_h */
