//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.2.11.1
//
#ifndef PARSafariSummarizationSummarizeResponse_h
#define PARSafariSummarizationSummarizeResponse_h
@import Foundation;

#include "PARResponse.h"

@interface PARSafariSummarizationSummarizeResponse : PARResponse

@property (retain, nonatomic) NSArray *summaryCandidates;
@property (retain, nonatomic) NSArray *summaryCandidates;

/* class methods */
+ (id)responseFromReply:(id)reply;

/* instance methods */
- (id)initWithReply:(id)reply factory:(id)factory data:(id)data;

@end

#endif /* PARSafariSummarizationSummarizeResponse_h */
