//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 192.600.1.0.0
//
#ifndef SLShareableContentActionResponse_h
#define SLShareableContentActionResponse_h
@import Foundation;

#include "BSXPCSecureCoding-Protocol.h"

@interface SLShareableContentActionResponse : NSObject <BSXPCSecureCoding, NSSecureCoding>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (_Bool)supportsBSXPCSecureCoding;
+ (id)response;

/* instance methods */
- (void)encodeWithBSXPCCoder:(id)bsxpccoder;
- (id)initWithCoder:(id)coder;
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (id)initWithBSXPCCoder:(id)bsxpccoder;

@end

#endif /* SLShareableContentActionResponse_h */
