//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 761.0.0.0.0
//
#ifndef TSKThreadDispatcher_h
#define TSKThreadDispatcher_h
@import Foundation;

@interface TSKThreadDispatcher : NSObject

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (void)dispatch:(id /* block */)dispatch;
- (id)p_dispatchQueue;
- (void)dispatchSelector:(SEL)selector target:(id)target argument:(id)argument;

@end

#endif /* TSKThreadDispatcher_h */
