//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 627.13.0.1.0
//
#ifndef ATXMagicalMomentsStatistics_h
#define ATXMagicalMomentsStatistics_h
@import Foundation;

@interface ATXMagicalMomentsStatistics : NSObject

/* class methods */
+ (double)betaDistributionCdfAtX:(double)x paramA:(double)a paramB:(double)b;
+ (double)calculateModelConfidenceWithCorrectPredictions:(double)predictions incorrectPredictions:(double)predictions;

@end

#endif /* ATXMagicalMomentsStatistics_h */
