//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 725.120.2.0.0
//
#ifndef MCMContainerManager_h
#define MCMContainerManager_h
@import Foundation;

@interface MCMContainerManager : NSObject

/* class methods */
+ (id)defaultManager;

/* instance methods */
- (id)init;
- (id)containersWithClass:(long long)_class error:(id *)error;
- (id)_containersWithClass:(long long)_class temporary:(_Bool)temporary error:(id *)error;
- (id)containerWithContentClass:(long long)_class identifier:(id)identifier createIfNecessary:(_Bool)necessary existed:(_Bool *)existed error:(id *)error;
- (id)containerWithContentClass:(long long)_class identifier:(id)identifier error:(id *)error;
- (id)deleteContainers:(id)containers withCompletion:(id /* block */)completion;
- (_Bool)replaceContainer:(id)container withContainer:(id)container error:(id *)error;
- (_Bool)replaceContainer:(id)container withContainer:(id)container error:(id *)error withCompletion:(id /* block */)completion;
- (id)temporaryContainerWithContentClass:(long long)_class identifier:(id)identifier existed:(_Bool *)existed error:(id *)error;
- (id)temporaryContainersWithClass:(long long)_class error:(id *)error;

@end

#endif /* MCMContainerManager_h */
