//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 25610.26.16.301.0
//
#ifndef MPCRequestController_h
#define MPCRequestController_h
@import Foundation;

#include "MPCRequestControllerDelegate-Protocol.h"
#include "OS_dispatch_source-Protocol.h"

@protocol MPRequestCancellationToken, OS_dispatch_queue;

@interface MPCRequestController : NSObject {
    /* instance variables */
    long long _numberOfObservers;
    NSString *_requestID;
    _Bool _shouldAutomaticallyLoad;
    _Bool _needsReload;
    id <MPRequestCancellationToken> _cancelToken;
    double _retryInterval;
    NSObject<OS_dispatch_source> *_retryTimer;
    NSError *_lastError;
    id _pendingResponse;
    unsigned long long _stateHandle;
}

@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *calloutQueue;
@property (retain, nonatomic) id response;
@property (retain, nonatomic) id request;
@property (weak, nonatomic) id <MPCRequestControllerDelegate> delegate;

/* instance methods */
- (void)setNeedsReload;
- (void)beginAutomaticResponseLoading;
- (void)_onQueue_updateRequestID;
- (void)dealloc;
- (void)reloadIfNeeded;
- (id)_onQueue_stateDictionary;
- (void)setNeedsReloadForSignificantRequestChange;
- (void)_onQueue_scheduleRetryAfterInterval:(double)interval;
- (void)_responseDidInvalidate:(id)invalidate;
- (id)init;
- (void)endAutomaticResponseLoading;
- (void)_onQueue_reloadIfNeeded;

@end

#endif /* MPCRequestController_h */
