//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 860.7.0.0.0
//
#ifndef WiFiP2PSPITransactionRequestor_h
#define WiFiP2PSPITransactionRequestor_h
@import Foundation;

#include "WiFiP2PXPCConnection.h"
#include "WiFiP2PXPCConnectionDelegate-Protocol.h"

@interface WiFiP2PSPITransactionRequestor : NSObject <WiFiP2PXPCConnectionDelegate> {
    /* instance variables */
    NSMutableArray *_openTransactions;
    WiFiP2PXPCConnection *_xpcConnection;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)shared;

/* instance methods */
- (void)endTransaction:(long long)transaction;
- (void)startConnectionUsingProxy:(id)proxy completionHandler:(id /* block */)handler;
- (void)endTransaction:(long long)transaction completionHandler:(id /* block */)handler;
- (id)remoteObjectInterface;
- (id)init;
- (void)_removeOpenTransaction:(long long)transaction;
- (void)beginTransaction:(long long)transaction completionHandler:(id /* block */)handler;
- (void)handleConnectionEstablishedWithProxy:(id)proxy;

@end

#endif /* WiFiP2PSPITransactionRequestor_h */
