//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 125.3.2.0.0
//
#ifndef _TtC26SensitiveContentAnalysisML13PeopleCounter_h
#define _TtC26SensitiveContentAnalysisML13PeopleCounter_h
@import Foundation;

@class SensitiveContentAnalysisML.CoherentLoadedAssets SensitiveContentAnalysisML.PeopleCounter.LoadedAssets, _TtCs12_SwiftObject, s.Logger, s.OSSignposter;

@interface _TtC26SensitiveContentAnalysisML13PeopleCounter : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    out s.Logger logger;
    out s.OSSignposter signposter;
    SensitiveContentAnalysisML.CoherentLoadedAssets SensitiveContentAnalysisML.PeopleCounter.LoadedAssets coherentAssets;
}

@end

#endif /* _TtC26SensitiveContentAnalysisML13PeopleCounter_h */
