//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 649.40.2.0.0
//
#ifndef IKAppDynamicUIResult_h
#define IKAppDynamicUIResult_h
@import Foundation;

@class AMSCarrierLinkResult, AMSPurchaseResult;

@interface IKAppDynamicUIResult : NSObject

@property (retain, nonatomic) AMSPurchaseResult *purchaseResult;
@property (retain, nonatomic) AMSCarrierLinkResult *carrierLinkResult;

/* class methods */
+ (id)_rawResultWithDynamicUIResult:(id)uiresult;
+ (id)_responseDictionaryWithCarrierLinkResult:(id)result;

/* instance methods */
- (id)rawResponse;
- (id)initWithCarrierLinkResult:(id)result;
- (id)initWithPurchaseResult:(id)result;

@end

#endif /* IKAppDynamicUIResult_h */
