//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 416.575.9.0.0
//
#ifndef _TtC15CoreCDPInternal28CDPExponentialRetryScheduler_h
#define _TtC15CoreCDPInternal28CDPExponentialRetryScheduler_h
@import Foundation;

@class AKAppleIDAuthenticationContext, CDPContext, OTConfigurationContext, SecureBackup;

@interface _TtC15CoreCDPInternal28CDPExponentialRetryScheduler : NSObject // (Swift)

/* instance methods */
- (id)init;
- (void)retryFetchAccountInfo:(SecureBackup *)info cdpContext:(CDPContext *)context completionHandler:(id /* block */)handler;
- (void)retryFetchAllEscrowRecord:(OTConfigurationContext *)record cdpContext:(CDPContext *)context completionHandler:(id /* block */)handler;
- (void)retryFetchEscrowRecord:(OTConfigurationContext *)record cdpContext:(CDPContext *)context completionHandler:(id /* block */)handler;
- (void)retrySilentAuthWithAuthContext:(AKAppleIDAuthenticationContext *)context completionHandler:(id /* block */)handler;

@end

#endif /* _TtC15CoreCDPInternal28CDPExponentialRetryScheduler_h */
