//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4025.610.1.0.0
//
#ifndef _TtC16MusicKitInternal33MusicLibraryPlaylistEditViewModel_h
#define _TtC16MusicKitInternal33MusicLibraryPlaylistEditViewModel_h
@import Foundation;

@class Combine.Published _$sySa -> MusicKit.Playlist.Entry, Combine.Published _$syXlSg, MusicKit.MusicLibrary, MusicKit.NotificationObserver ?, MusicKit.Playlist ?, Swift.Bool, _$sSa -> MusicKit.Playlist.Entry ?, _$sSa -> MusicKitInternal.CoverArtworkRecipe ?, _$sSo57MusicKit_SoftLinking_MPModelLibraryPlaylistEditControllerC, _TtCs12_SwiftObject;

@interface _TtC16MusicKitInternal33MusicLibraryPlaylistEditViewModel : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    Combine.Published _$sySa -> MusicKit.Playlist.Entry _entries;
    _$sSa -> MusicKit.Playlist.Entry ? initialEntries;
    Combine.Published _$syXlSg _underlyingTracklist;
    MusicKit.Playlist ? playlist;
    MusicKit.MusicLibrary library;
    _$sSo57MusicKit_SoftLinking_MPModelLibraryPlaylistEditControllerC _underlyingEditController;
    MusicKit.NotificationObserver ? underlyingPlaylistDidChangeObserver;
    _$sSa -> MusicKitInternal.CoverArtworkRecipe ? _coverArtworkRecipes;
    Swift.Bool didBeginSession;
}

@end

#endif /* _TtC16MusicKitInternal33MusicLibraryPlaylistEditViewModel_h */
