//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 655.10.5.3.0
//
#ifndef _TtC18ControlCenterUIKit22LabelWithAccessoryView_h
#define _TtC18ControlCenterUIKit22LabelWithAccessoryView_h
@import Foundation;

@class UIView, _$sSo7UIImageCSg, _$sSo7UILabelC;

@interface _TtC18ControlCenterUIKit22LabelWithAccessoryView : UIView { // (Swift)
    /* instance variables */
    _$sSo7UIImageCSg accessoryImage;
    _$sSo7UILabelC textLabel;
    _$sSo7UILabelC accessoryLabel;
}

@property (nonatomic) double gaussianBlurRadius;

/* instance methods */
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (id)initWithCoder:(id)coder;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (void)ensureGaussianBlurFilter;
- (void)removeGaussianBlurFilter;

@end

#endif /* _TtC18ControlCenterUIKit22LabelWithAccessoryView_h */
