//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 106.600.51.2.2
//
#ifndef _TtCC41_CommunicationsUICore_PosterBoardServices20PosterViewController21PosterStatusTextModel_h
#define _TtCC41_CommunicationsUICore_PosterBoardServices20PosterViewController21PosterStatusTextModel_h
@import Foundation;

@class Swift.Bool, _$sSS;

@interface _TtCC41_CommunicationsUICore_PosterBoardServices20PosterViewController21PosterStatusTextModel : NSObject { // (Swift)
    /* instance variables */
    _$sSS status;
    Swift.Bool callIsActive;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtCC41_CommunicationsUICore_PosterBoardServices20PosterViewController21PosterStatusTextModel_h */
