//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1428.0.0.0.0
//
#ifndef _TtC13TeaFoundation19NetworkReachability_h
#define _TtC13TeaFoundation19NetworkReachability_h
@import Foundation;

@class DispatchQueue, TeaFoundation.Lazy TeaFoundation.AsyncObservable TeaFoundation.NetworkStatus _$sGGSg ->, _TtCs12_SwiftObject, etwork.NWPathMonitor;

@interface _TtC13TeaFoundation19NetworkReachability : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    TeaFoundation.Lazy TeaFoundation.AsyncObservable TeaFoundation.NetworkStatus _$sGGSg -> lazyObservableNetworkStatus;
    DispatchQueue observationQueue;
    inout etwork.NWPathMonitor networkPathMonitor;
}

@end

#endif /* _TtC13TeaFoundation19NetworkReachability_h */
