//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 486.0.0.0.0
//
#ifndef TSTCategoryTranslator_h
#define TSTCategoryTranslator_h
@import Foundation;

#include "TSTGroupByChangeProtocol-Protocol.h"
#include "TSTTableTranslator.h"

@class 0, 1, 2, TSCECellRef, TSUViewCellRect;

@interface TSTCategoryTranslator : TSTTableTranslator <TSTGroupByChangeProtocol> {
    /* instance variables */
    unsigned long long _groupingsChangingLevel;
    _Bool _sawGroupingChangeNeedingReset;
}

@property (nonatomic) _Bool suspendNotify;
@property (nonatomic) _Bool cachedIndexSetsAreValid;
@property (nonatomic) struct os_unfair_lock_s { unsigned int x0; } cachedIndexesUnfairLock;
@property (retain, nonatomic) NSIndexSet *cachedIndexesForSummaryRows;
@property (retain, nonatomic) NSMapTable *cachedSummaryRowIndexesAtLevels;
@property (retain, nonatomic) NSIndexSet *cachedIndexesForLabelRows;
@property (retain, nonatomic) NSMapTable *cachedLabelRowIndexesAtLevels;
@property (retain, nonatomic) NSIndexSet *cachedIndexesForSummaryAndLabelRows;
@property (retain, nonatomic) NSIndexSet *cachedIndexesForLeadingRows;
@property (retain, nonatomic) NSMapTable *cachedLeadingRowIndexesAtLevels;
@property (retain, nonatomic) NSIndexSet *cachedIndexesForLeadingSummaryRows;
@property (retain, nonatomic) NSMapTable *cachedLeadingSummaryRowIndexesAtLevels;

/* class methods */
+ (unsigned long long)tableStyleAreaForCategoryLevel:(unsigned char)level isLabel:(_Bool)label;

/* instance methods */
- (id)columnWidths;
- (id)rowHeights;
- (_Bool)isCategorized;
- (void)didCreateGroup:(id)group;
- (void)didRemoveGroup:(id)group;
- (void)i_populateIndexesForSummaryRows;
- (_Bool)mergeCellRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (double)widthOfColumnAtIndex:(struct TSUViewColumnIndex { unsigned short x0; })index isDefault:(out _Bool *)_default;
- (id)allRowGroupUIDs;
- (void)i_populateIndexesForLeadingRows;
- (struct TSUModelRowIndex { unsigned int x0; })summaryRowIndexForViewRowIndex:(struct TSUViewRowIndex { unsigned int x0; })index;
- (void)addReceiverToGroupBy:(id)by;
- (id)aggregateFormulaOwner;
- (id)allRichTextStorages;
- (_Bool)areMapsStale;
- (struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })baseCellCoordForCellUID:(struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; })uid;
- (struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })baseCellCoordForChromeCellCoord:(struct TSUChromeCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })baseCellCoordForViewCellCoord:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (struct RefTypeHolder<TSCECellRef, 0> { struct TSCECellRef { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } x0; })baseCellRefForViewCellRef:(const void *)ref;
- (id)baseCellRegionForViewCellRect:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })rect;
- (id)baseCellRegionForViewCellRegion:(id)region;
- (struct TSUModelColumnIndex { unsigned short x0; })baseColumnIndexForChromeColumnIndex:(struct TSUChromeColumnIndex { unsigned short x0; })index;
- (struct TSUModelColumnIndex { unsigned short x0; })baseColumnIndexForViewColumnIndex:(struct TSUViewColumnIndex { unsigned short x0; })index;
- (id)baseColumnIndexesForViewColumnIndexes:(id)indexes;
- (struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; })baseCoordFromViewCoord:(struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; })coord;
- (struct TSUModelRowIndex { unsigned int x0; })baseRowIndexForChromeRowIndex:(struct TSUChromeRowIndex { unsigned int x0; })index;
- (struct TSUModelRowIndex { unsigned int x0; })baseRowIndexForViewRowIndex:(struct TSUViewRowIndex { unsigned int x0; })index;
- (id)baseRowIndexesForViewRowIndexes:(id)indexes;
- (id)baseShuffleMapForViewShuffleMap:(id)map;
- (struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })bodyBoundingRangeForBaseLevel;
- (struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })bodyRangeForLowestLevelGroupEnclosingCellAtCellID:(struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; })id;
- (_Bool)cellExistsAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })cellIDForCellContainingRichTextStorage:(id)storage;
- (id)cellRegionForTableStyleArea:(unsigned long long)area;
- (id)cellStyleAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id isDefault:(out _Bool *)_default;
- (id)cellStyleAtCellUID:(const struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } *)uid isDefault:(out _Bool *)_default;
- (id)cellStyleOfColumnAtIndex:(struct TSUViewColumnIndex { unsigned short x0; })index isDefault:(out _Bool *)_default;
- (id)cellStyleOfRowAtIndex:(struct TSUViewRowIndex { unsigned int x0; })index isDefault:(out _Bool *)_default;
- (struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; })cellUIDForSummaryCellCoord:(struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (unsigned char)cellValueTypeAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (_Bool)checkMapsAndAssert:(_Bool)assert;
- (struct TSUChromeCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })chromeCellCoordForBaseCellCoord:(struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (struct TSUChromeCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })chromeCellCoordForViewCellCoord:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (struct RefTypeHolder<TSCECellRef, 2> { struct TSCECellRef { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } x0; })chromeCellRefForBaseCellRef:(const void *)ref;
- (struct RefTypeHolder<TSCECellRef, 2> { struct TSCECellRef { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } x0; })chromeCellRefForViewCellRef:(const void *)ref;
- (struct TSUChromeColumnIndex { unsigned short x0; })chromeColumnIndexForBaseColumnIndex:(struct TSUModelColumnIndex { unsigned short x0; })index;
- (struct TSUChromeColumnIndex { unsigned short x0; })chromeColumnIndexForViewColumnIndex:(struct TSUViewColumnIndex { unsigned short x0; })index;
- (id)chromeColumnIndexesForViewColumnIndexes:(id)indexes;
- (struct TSUChromeRowIndex { unsigned int x0; })chromeRowIndexForBaseRowIndex:(struct TSUModelRowIndex { unsigned int x0; })index;
- (struct TSUChromeRowIndex { unsigned int x0; })chromeRowIndexForViewRowIndex:(struct TSUViewRowIndex { unsigned int x0; })index;
- (id)chromeRowIndexesForViewRowIndexes:(id)indexes;
- (struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; })columnUIDForBaseColumnIndex:(struct TSUModelColumnIndex { unsigned short x0; })index;
- (id)commentHostingAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (id)commentHostingAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id forCommentStorage:(id)storage updateCommentMaps:(_Bool)maps;
- (id)conditionalStyleSetAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (id)coordinateMapper;
- (id)defaultCellStyleForCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id useSoftDefault:(_Bool)_default outSource:(out unsigned long long *)source;
- (void)defaultStyleHandlesForCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id useSoftDefault:(_Bool)_default styleDefaultsCache:(id)cache outCellStyleHandle:(id *)handle outTextStyleHandle:(id *)handle;
- (id)defaultTextStyleForCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id useSoftDefault:(_Bool)_default outSource:(out unsigned long long *)source;
- (void)didAddRowUID:(struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; })uid toGroup:(id)group;
- (void)didChangeGroupByStructure;
- (void)didMakeGroupingChangesInRowUIDs:(id)uids;
- (void)didRemoveRowUID:(struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; })uid fromGroup:(id)group;
- (void)endOfGroupingChangesBatch;
- (void)enumerateMergesIntersectingCellRegion:(id)region usingBlock:(id /* block */)block;
- (struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })expandCellRangeToCoverMergedCells:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })cells;
- (id)expandCellRegionToCoverMergedCells:(id)cells;
- (void)flushCachedIndexSets;
- (void)forceGroupingChangeReset;
- (id)formulaAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (int)getCell:(id)cell atCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id suppressCellBorder:(_Bool)border;
- (int)getDefaultCell:(out id)cell forCellUID:(const struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } *)uid;
- (int)getValue:(id *)value atCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id fetchRichTextAttributesIfPlainText:(_Bool)text;
- (unsigned char)groupLevelAtLabelRow:(struct TSUViewRowIndex { unsigned int x0; })row;
- (unsigned char)groupLevelAtSummaryRow:(struct TSUViewRowIndex { unsigned int x0; })row;
- (_Bool)hasCommentAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (_Bool)hasFormulaAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (_Bool)hasFormulaAtCellUID:(const struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } *)uid;
- (_Bool)hasMergeRangeSpanningRowsForCellRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (_Bool)hasMergeRangesIntersectingCellRegion:(id)region;
- (_Bool)hasRangeSpanningRowsForCellRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (_Bool)hasSpillRangesIntersectingCellRegion:(id)region;
- (double)heightOfRowAtIndex:(struct TSUViewRowIndex { unsigned int x0; })index isDefault:(out _Bool *)_default;
- (id)i_indexesForLabelRowsAtGroupLevel:(unsigned char)level;
- (id)i_indexesForLeadingRowsAtGroupLevel:(unsigned char)level;
- (id)i_indexesForLeadingSummaryRowsAtGroupLevel:(unsigned char)level;
- (id)i_indexesForSummaryRowsAtGroupLevel:(unsigned char)level;
- (void)i_populateCachedIndexSetsIfNeeded;
- (void)i_populateIndexesForLabelRows;
- (void)i_populateIndexesForLeadingSummaryRows;
- (void)i_populateIndexesForSummaryAndLabelRows;
- (id)indexesForLabelRows;
- (id)indexesForLabelRowsAtGroupLevel:(unsigned char)level;
- (id)indexesForLeadingRows;
- (id)indexesForLeadingRowsAtGroupLevel:(unsigned char)level;
- (id)indexesForLeadingSummaryRows;
- (id)indexesForLeadingSummaryRowsAtGroupLevel:(unsigned char)level;
- (id)indexesForRowsContainedByGroupUIDs:(id)uids;
- (id)indexesForSummaryAndLabelRows;
- (id)indexesForSummaryRows;
- (id)indexesForSummaryRowsAtGroupLevel:(unsigned char)level;
- (id)initWithTableInfo:(id)info;
- (int)insertColumnsAtIndex:(struct TSUViewColumnIndex { unsigned short x0; })index uids:(const void *)uids metadatas:(id)metadatas tableArea:(unsigned long long)area;
- (int)insertRowsAtIndex:(struct TSUViewRowIndex { unsigned int x0; })index uids:(const void *)uids metadatas:(id)metadatas tableArea:(unsigned long long)area unsetFilterHidingAction:(_Bool)action;
- (_Bool)isGroupedForRows;
- (_Bool)isLabelRow:(unsigned int)row;
- (_Bool)isSummaryColumn:(unsigned short)column;
- (_Bool)isSummaryOrLabelRow:(unsigned int)row;
- (_Bool)isSummaryRow:(unsigned int)row;
- (_Bool)isValidMergeRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (Class)iteratorClass;
- (unsigned int)maxNumberOfHeaderColumns;
- (unsigned char)maxRowLevel;
- (unsigned char)maxVisibleRowLevel;
- (id)mergeActionForRegion:(id)region;
- (id)mergeActionForRegion:(id)region nonOriginPartialsOnly:(_Bool)only;
- (struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })mergeOriginForCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })mergeRangeAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (struct vector<TSUViewCellRect, std::allocator<TSUViewCellRect>> { struct TSUViewCellRect *x0; struct TSUViewCellRect *x1; struct { struct TSUViewCellRect *x0; } x2; })mergeRangesAndCrumbsIntersectingRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (struct vector<TSUViewCellRect, std::allocator<TSUViewCellRect>> { struct TSUViewCellRect *x0; struct TSUViewCellRect *x1; struct { struct TSUViewCellRect *x0; } x2; })mergeRangesIntersectingCellRegion:(id)region;
- (struct vector<TSUViewCellRect, std::allocator<TSUViewCellRect>> { struct TSUViewCellRect *x0; struct TSUViewCellRect *x1; struct { struct TSUViewCellRect *x0; } x2; })mergeRangesIntersectingRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (_Bool)mergeRangesPartiallyIntersectCellRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (_Bool)mergeRangesPartiallyIntersectCellRegion:(id)region;
- (id)mergedGridIndicesForDimension:(long long)dimension;
- (id)metadataForColumnIndex:(struct TSUViewColumnIndex { unsigned short x0; })index;
- (id)metadataForRowIndex:(struct TSUViewRowIndex { unsigned int x0; })index;
- (unsigned int)minNumberOfHeaderColumns;
- (unsigned char)minRowLevel;
- (void)moveColumnRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range toColumnIndex:(struct TSUViewColumnIndex { unsigned short x0; })index;
- (struct TSUViewColumnIndex { unsigned short x0; })numberOfCategoryColumns;
- (struct TSUViewColumnIndex { unsigned short x0; })numberOfHeaderColumns;
- (unsigned long long)numberOfPopulatedCells;
- (unsigned long long)numberOfRowLevels;
- (int)p_applyViewCellCoord:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord toSummaryUsingBlock:(id /* block */)block toLabelUsingBlock:(id /* block */)block toCategoryColumnUsingBlock:(id /* block */)block toBaseUsingBlock:(id /* block */)block;
- (void)p_applyViewColumnIndex:(struct TSUViewColumnIndex { unsigned short x0; })index toCategoryColumnUsingBlock:(id /* block */)block toBaseUsingBlock:(id /* block */)block toBeyondBoundsUsingBlock:(id /* block */)block;
- (void)p_applyViewRowIndex:(struct TSUViewRowIndex { unsigned int x0; })index toSummaryUsingBlock:(id /* block */)block toLabelUsingBlock:(id /* block */)block toBaseUsingBlock:(id /* block */)block toBeyondBoundsUsingBlock:(id /* block */)block;
- (id)p_defaultCellStyleOfSummaryOrLabelRowAtLevel:(unsigned char)level isLabel:(_Bool)label;
- (void)p_defaultStyleHandlesOfSummaryOrLabelRowAtLevel:(unsigned char)level isLabel:(_Bool)label styleDefaultsCache:(id)cache outCellStyleHandle:(id *)handle outTextStyleHandle:(id *)handle;
- (void)p_defaultStylesOfSummaryOrLabelRowAtLevel:(unsigned char)level isLabel:(_Bool)label outCellStyle:(id *)style outTextStyle:(id *)style;
- (id)p_defaultTextStyleOfSummaryOrLabelRowAtLevel:(unsigned char)level isLabel:(_Bool)label;
- (id)populatedCategoryGroupLevelsInColumn:(struct TSUViewColumnIndex { unsigned short x0; })column;
- (void)postCommentNotificationForStorage:(id)storage atViewCellCoord:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord notificationKey:(id)key;
- (id)regionForValueOrCommentCellsInRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (void)removeAnnotationsFromColumnsAtIndexes:(id)indexes;
- (void)removeAnnotationsFromRowsAtIndexes:(id)indexes;
- (void)removeColumnsAtIndex:(struct TSUViewColumnIndex { unsigned short x0; })index count:(struct TSUViewColumnIndex { unsigned short x0; })count;
- (void)removeColumnsAtIndexes:(id)indexes;
- (id)removeReturningInverseForRegion:(id)region;
- (void)removeRowsAtIndex:(struct TSUViewRowIndex { unsigned int x0; })index count:(struct TSUViewRowIndex { unsigned int x0; })count;
- (void)removeRowsAtIndexes:(id)indexes;
- (void)resetViewMap;
- (void)resetViewMapAndNotify;
- (unsigned int)rowAggregateGroupSize;
- (int)setCellStyle:(id)style ofColumnAtIndex:(struct TSUViewColumnIndex { unsigned short x0; })index;
- (int)setCellStyle:(id)style ofRowAtIndex:(struct TSUViewRowIndex { unsigned int x0; })index;
- (void)setHeight:(double)height ofRowAtIndex:(struct TSUViewRowIndex { unsigned int x0; })index;
- (void)setNumberOfHeaderColumns:(struct TSUViewColumnIndex { unsigned short x0; })columns;
- (int)setTextStyle:(id)style ofColumnAtIndex:(struct TSUViewColumnIndex { unsigned short x0; })index;
- (int)setTextStyle:(id)style ofRowAtIndex:(struct TSUViewRowIndex { unsigned int x0; })index;
- (void)setWidth:(double)width ofColumnAtIndex:(struct TSUViewColumnIndex { unsigned short x0; })index;
- (id)shrinkReturningInverseForRegion:(id)region;
- (void)startOfGroupingChangesBatch;
- (id)stringAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id optionalCell:(id)cell;
- (struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })summaryCellCoordForCellUID:(const struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } *)uid;
- (struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })summaryCellCoordForViewCellCoord:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (id)summaryCellVendor;
- (struct TSUModelColumnIndex { unsigned short x0; })summaryColumnIndexForViewColumnIndex:(struct TSUViewColumnIndex { unsigned short x0; })index;
- (id)summaryModel;
- (void)suspendChangeDescriptorNotificationsDuringBlock:(id /* block */)block;
- (unsigned long long)tableAreaForCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (unsigned long long)tableStyleAreaForCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id;
- (unsigned long long)tableStyleAreaForCellUID:(struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; })uid;
- (unsigned long long)tableStyleAreaForRow:(struct TSUViewRowIndex { unsigned int x0; })row;
- (id)textStyleAtCellID:(struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })id isDefault:(out _Bool *)_default;
- (id)textStyleAtCellUID:(const struct TSKUIDStructCoord { struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } *)uid isDefault:(out _Bool *)_default;
- (id)textStyleOfColumnAtIndex:(struct TSUViewColumnIndex { unsigned short x0; })index isDefault:(out _Bool *)_default;
- (id)textStyleOfRowAtIndex:(struct TSUViewRowIndex { unsigned int x0; })index isDefault:(out _Bool *)_default;
- (id)translatedCellRangeName:(const void *)name usedSymbolicName:(out _Bool *)name;
- (_Bool)unmergeCellRange:(struct TSUViewCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })range;
- (struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })viewCellCoordForBaseCellCoord:(struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })viewCellCoordForChromeCellCoord:(struct TSUChromeCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (struct TSUViewCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })viewCellCoordForSummaryCellCoord:(struct TSUModelCellCoord { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; })coord;
- (struct RefTypeHolder<TSCECellRef, 1> { struct TSCECellRef { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } x0; })viewCellRefForBaseCellRef:(const void *)ref;
- (struct RefTypeHolder<TSCECellRef, 1> { struct TSCECellRef { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct TSKUIDStruct { unsigned long long x0; unsigned long long x1; } x1; } x0; })viewCellRefForChromeCellRef:(const void *)ref;
- (id)viewCellRegionForBaseCellRect:(struct TSUModelCellRect { struct TSUCellRect { struct TSUCellCoord { unsigned int x0; unsigned short x1; _Bool x2; _Bool x3; } x0; struct { unsigned int x0; unsigned int x1; } x1; } x0; })rect;
- (id)viewCellRegionForBaseCellRegion:(id)region;
- (id)viewColumnGridIndexesForBaseColumnGridIndexes:(id)indexes;
- (struct TSUViewColumnIndex { unsigned short x0; })viewColumnIndexForBaseColumnIndex:(struct TSUModelColumnIndex { unsigned short x0; })index;
- (struct TSUViewColumnIndex { unsigned short x0; })viewColumnIndexForChromeColumnIndex:(struct TSUChromeColumnIndex { unsigned short x0; })index;
- (id)viewColumnIndexesForBaseColumnIndexes:(id)indexes;
- (id)viewColumnIndexesForChromeColumnIndexes:(id)indexes;
- (struct TSUViewRowIndex { unsigned int x0; })viewRowIndexForBaseRowIndex:(struct TSUModelRowIndex { unsigned int x0; })index;
- (struct TSUViewRowIndex { unsigned int x0; })viewRowIndexForChromeRowIndex:(struct TSUChromeRowIndex { unsigned int x0; })index;
- (id)viewRowIndexesForBaseRowIndexes:(id)indexes;
- (id)viewRowIndexesForChromeRowIndexes:(id)indexes;
- (void)willRemoveGroup:(id)group;
- (_Bool)withinGroupingChangesBatch;

@end

#endif /* TSTCategoryTranslator_h */
