//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 314.14.0.0.0
//
#ifndef GTCaptureArchiveHeapRestoreTextureSliceOverrideKey_h
#define GTCaptureArchiveHeapRestoreTextureSliceOverrideKey_h
@import Foundation;

@interface GTCaptureArchiveHeapRestoreTextureSliceOverrideKey : NSObject <NSSecureCoding, NSCopying>

@property unsigned long long slice;
@property unsigned long long mipLevel;
@property unsigned long long depthPlane;
@property (retain) NSNumber *plane;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (id)debugDescription;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (id)initWithSlice:(long long)slice mipLevel:(long long)level depthPlane:(long long)plane plane:(id)plane;

@end

#endif /* GTCaptureArchiveHeapRestoreTextureSliceOverrideKey_h */
