//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2.5.15.2.1
//
#ifndef _TtC12GameStoreKit21ArcadeDownloadPackApp_h
#define _TtC12GameStoreKit21ArcadeDownloadPackApp_h
@import Foundation;

#include "_TtP12GameStoreKitP33_34DA4300AF69A3083E9798A3B263256634ArcadeDownloadPackAppObjectExports_-Protocol.h"

@class _$sSS;

@interface _TtC12GameStoreKit21ArcadeDownloadPackApp : NSObject <_TtP12GameStoreKitP33_34DA4300AF69A3083E9798A3B263256634ArcadeDownloadPackAppObjectExports_> // (Swift)

@property (nonatomic, readonly) NSString *adamId;
@property (nonatomic, readonly) NSString *categoryId;

/* instance methods */
- (id)init;

@end

#endif /* _TtC12GameStoreKit21ArcadeDownloadPackApp_h */
