//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2.8.0.0.0
//
#ifndef _TtC15UIUnderstanding15UIFingerprinter_h
#define _TtC15UIUnderstanding15UIFingerprinter_h
@import Foundation;

@class UIUnderstanding.ModelPlatform, UIUnderstanding.TwinTransformerEmbeddingGenerator, UIUnderstanding.UIUDetector, _$sSf, _TtCs12_SwiftObject;

@interface _TtC15UIUnderstanding15UIFingerprinter : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    UIUnderstanding.UIUDetector uiDetector;
    UIUnderstanding.ModelPlatform platform;
    UIUnderstanding.TwinTransformerEmbeddingGenerator screenEmbeddingGen;
    _$sSf embeddingThreshold;
}

@end

#endif /* _TtC15UIUnderstanding15UIFingerprinter_h */
