//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 270.50.4.0.0
//
#ifndef _TtCO15HomePodSettings13CarrySettings24LivabilityDataDownloader_h
#define _TtCO15HomePodSettings13CarrySettings24LivabilityDataDownloader_h
@import Foundation;

@class _$sSS, _$sSo12NSURLSessionC, _TtCs12_SwiftObject, s.Logger;

@interface _TtCO15HomePodSettings13CarrySettings24LivabilityDataDownloader : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSS acToken;
    out s.Logger logger;
    _$sSo12NSURLSessionC urlSession;
}

@end

#endif /* _TtCO15HomePodSettings13CarrySettings24LivabilityDataDownloader_h */
