//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 474.2.18.2.0
//
#ifndef TRIFetchOnDemandFactorsPersistedTask_FactorPackAssetIds_h
#define TRIFetchOnDemandFactorsPersistedTask_FactorPackAssetIds_h
@import Foundation;

@class TRIPBMessage;

@interface TRIFetchOnDemandFactorsPersistedTask_FactorPackAssetIds : TRIPBMessage

@property (copy, nonatomic) NSString *factorPackId;
@property (nonatomic) _Bool hasFactorPackId;
@property (retain, nonatomic) NSMutableArray *assetIdArray;
@property (readonly, nonatomic) unsigned long long assetIdArray_Count;
@property (retain, nonatomic) NSMutableArray *assetIdFactorNameArray;
@property (readonly, nonatomic) unsigned long long assetIdFactorNameArray_Count;

/* class methods */
+ (id)descriptor;

@end

#endif /* TRIFetchOnDemandFactorsPersistedTask_FactorPackAssetIds_h */
