//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2422.120.23.0.9
//
#ifndef SUCoreConnectClientProxy_h
#define SUCoreConnectClientProxy_h
@import Foundation;

#include "SUCoreConnectClientProxyProtocol-Protocol.h"

@protocol OS_dispatch_queue;

@interface SUCoreConnectClientProxy : NSObject <NSSecureCoding, SUCoreConnectClientProxyProtocol>

@property (readonly, retain, nonatomic) NSObject<OS_dispatch_queue> *completionQueue;
@property (readonly, nonatomic) id /* block */ genericBlock;
@property (readonly, nonatomic) id /* block */ progressBlock;
@property (readonly, retain, nonatomic) NSString *clientID;
@property (readonly, retain, nonatomic) NSString *clientIDRaw;
@property (readonly, nonatomic) int clientProcessIdentifier;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithClientID:(id)id completionQueue:(id)queue progressBlock:(id /* block */)block;
- (id)initWithClientID:(id)id completionQueue:(id)queue genericBlock:(id /* block */)block;
- (void)executeProgressBlock:(id)block disableVerboseLogging:(_Bool)logging;
- (id)initWithClientID:(id)id completionQueue:(id)queue genericBlock:(id /* block */)block progressBlock:(id /* block */)block;
- (id)summary;
- (void)executeGenericBlock:(id)block disableVerboseLogging:(_Bool)logging;
- (id)initWithCoder:(id)coder;
- (void)executeProgressBlock:(id)block;
- (void)encodeWithCoder:(id)coder;
- (void)executeGenericBlock:(id)block;

@end

#endif /* SUCoreConnectClientProxy_h */
