//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 6200.6.8.2.1
//
#ifndef HDCloudSyncModifyRecordZonesOperation_h
#define HDCloudSyncModifyRecordZonesOperation_h
@import Foundation;

#include "HDCloudSyncOperation.h"
#include "HDSynchronousTaskGroupDelegate-Protocol.h"

@class CKContainer, CKDatabase, HDSynchronousTaskGroup;

@interface HDCloudSyncModifyRecordZonesOperation : HDCloudSyncOperation <HDSynchronousTaskGroupDelegate> {
    /* instance variables */
    CKContainer *_container;
    CKDatabase *_database;
    HDSynchronousTaskGroup *_taskGroup;
}

@property (copy, nonatomic) NSArray *recordZonesToSave;
@property (copy, nonatomic) NSArray *recordZoneIDsToDelete;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)shouldLogAtOperationStart;

/* instance methods */
- (void)main;
- (void)_limitExceededForSavingRecordZones:(id)zones deletingRecordZoneIDs:(id)ids error:(id)error;
- (void)_saveRecordZones:(id)zones deleteRecordZoneIDs:(id)ids;
- (id)initWithConfiguration:(id)configuration container:(id)container recordZonesToSave:(id)save recordZoneIDsToDelete:(id)_delete;
- (id)initWithConfiguration:(id)configuration container:(id)container scope:(long long)scope recordZonesToSave:(id)save recordZoneIDsToDelete:(id)_delete;
- (void)synchronousTaskGroup:(id)group didFinishWithSuccess:(_Bool)success errors:(id)errors;

@end

#endif /* HDCloudSyncModifyRecordZonesOperation_h */
