//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3864.600.51.2.1
//
#ifndef EDSearchableIndexUpdates_h
#define EDSearchableIndexUpdates_h
@import Foundation;

#include "EDIndexedItems.h"
#include "EFPubliclyDescribable-Protocol.h"

@interface EDSearchableIndexUpdates : NSObject <EFPubliclyDescribable>

@property (readonly, nonatomic) EDIndexedItems *indexedItems;
@property (readonly, nonatomic) NSArray *removedIdentifiers;
@property (readonly, nonatomic) NSArray *removedDomainIdentifiers;
@property (readonly, nonatomic) _Bool hasUpdates;
@property (readonly, copy, nonatomic) NSString *ef_publicDescription;
@property (readonly, copy, nonatomic) NSString *ef_shortPublicDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithIndexableItems:(id)items;
- (id)initWithIndexableItems:(id)items removedIdentifiers:(id)identifiers removedDomainIdentifiers:(id)identifiers;
- (id)initWithIdentifiers:(id)identifiers;
- (id)initWithRemovedDomainIdentifiers:(id)identifiers;
- (id)initWithRemovedIdentifiers:(id)identifiers;
- (id)initWithIndexedItems:(id)items removedIdentifiers:(id)identifiers removedDomainIdentifiers:(id)identifiers;

@end

#endif /* EDSearchableIndexUpdates_h */
