//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 468.5.5.0.0
//
#ifndef DNDRemoteAvailabilityServiceServerProtocol_Protocol_h
#define DNDRemoteAvailabilityServiceServerProtocol_Protocol_h
@import Foundation;

@protocol DNDRemoteAvailabilityServiceServerProtocol <NSObject>

@required

/* required instance methods */
- (void)getIsLocalUserAvailableWithRequestDetails:(id)details completionHandler:(id /* block */)handler;

@optional

@end

#endif /* DNDRemoteAvailabilityServiceServerProtocol_Protocol_h */
