//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1418.6.20.0.0
//
#ifndef HMDRemoteEventRouterProtoFetchEventsMessage_h
#define HMDRemoteEventRouterProtoFetchEventsMessage_h
@import Foundation;

@class PBCodable;

@interface HMDRemoteEventRouterProtoFetchEventsMessage : PBCodable <NSCopying> {
    /* instance variables */
    struct { unsigned int fetchType:1; } _has;
}

@property (retain, nonatomic) NSMutableArray *topics;
@property (nonatomic) _Bool hasFetchType;
@property (nonatomic) int fetchType;

/* class methods */
+ (Class)topicsType;

/* instance methods */
- (void)clearTopics;
- (_Bool)readFrom:(id)from;
- (void)copyTo:(id)to;
- (unsigned long long)hash;
- (unsigned long long)topicsCount;
- (void)mergeFrom:(id)from;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)topicsAtIndex:(unsigned long long)index;
- (void)writeTo:(id)to;
- (void)addTopics:(id)topics;
- (id)dictionaryRepresentation;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (int)StringAsFetchType:(id)type;
- (id)fetchTypeAsString:(int)string;

@end

#endif /* HMDRemoteEventRouterProtoFetchEventsMessage_h */
