//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1418.6.20.0.0
//
#ifndef HMDSettingTransaction_h
#define HMDSettingTransaction_h
@import Foundation;

#include "HMDSettingTransaction-Protocol.h"

@interface HMDSettingTransaction : NSObject <HMDSettingTransaction>

@property (readonly) NSString *transactionLabel;
@property (readonly) NSMutableSet *updateModels;
@property (readonly) NSMutableSet *removeUUIDs;
@property (readonly) _Bool initialCreation;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)addModel:(id)model;
- (void)addModelToBeUpdated:(id)updated;
- (void)addSettingModel:(id)model;
- (id)initForInitialCreationWithTransactionLabel:(id)label;
- (id)initWithTransactionLabel:(id)label;
- (void)removeModelWithIdentifier:(id)identifier;

@end

#endif /* HMDSettingTransaction_h */
