//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 655.10.5.3.0
//
#ifndef CCUIMenuModuleViewController_h
#define CCUIMenuModuleViewController_h
@import Foundation;

#include "CCUIButtonModuleViewController.h"
#include "CCUIContentModuleContext.h"
#include "CCUIControlTemplateViewContextMenuDelegate-Protocol.h"
#include "CCUIMenuModuleItemView.h"
#include "UIGestureRecognizerDelegate-Protocol.h"

@class MTMaterialView, UIActivityIndicatorView, UILabel, UILongPressGestureRecognizer, UIMenu, UIScrollView, UISelectionFeedbackGenerator, UIStackView, UIView;
@protocol CCUIMenuItemsUpdating;

@interface CCUIMenuModuleViewController : CCUIButtonModuleViewController <UIGestureRecognizerDelegate, CCUIControlTemplateViewContextMenuDelegate> {
    /* instance variables */
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIView *_transformView;
    UIView *_headerSeparatorView;
    UIView *_footerSeparatorView;
    MTMaterialView *_platterMaterialView;
    NSMutableDictionary *_categoriesToVisualStylingProviders;
    UIStackView *_menuItemsContainer;
    NSMutableArray *_menuItems;
    NSMutableDictionary *_identiferToActivityIndicatorView;
    UIScrollView *_contentScrollView;
    UIView *_darkeningBackgroundView;
    UIActivityIndicatorView *_busyIndicatorView;
    UILongPressGestureRecognizer *_pressGestureRecognizer;
    UISelectionFeedbackGenerator *_feedbackGenerator;
    _Bool _allowsMenuInteraction;
    _Bool _ignoreMenuItemAtTouchLocationAfterExpanded;
    struct CGPoint { double x; double y; } _touchLocationToIgnore;
    CCUIMenuModuleItemView *_footerButtonView;
    _Bool _shouldShowFooterButton;
    UIView *_customContentView;
    _Bool _customContentViewScrolls;
    _Bool _forceLimitContentSizeCategory;
}

@property (copy, nonatomic) NSString *subtitle;
@property (readonly, nonatomic) unsigned long long actionsCount;
@property (readonly, nonatomic) unsigned long long menuItemCount;
@property (readonly, nonatomic) double headerHeight;
@property (readonly, nonatomic) UIView *contentView;
@property (readonly, nonatomic) _Bool hasFooterButton;
@property (nonatomic) unsigned long long minimumMenuItems;
@property (nonatomic) double visibleMenuItems;
@property (nonatomic) unsigned long long indentation;
@property (nonatomic) _Bool busy;
@property (nonatomic) _Bool shouldProvideOwnPlatter;
@property (nonatomic) _Bool useTrailingCheckmarkLayout;
@property (nonatomic) _Bool useTrailingInset;
@property (nonatomic) _Bool useTallLayout;
@property (weak, nonatomic) CCUIContentModuleContext *contentModuleContext;
@property (nonatomic) _Bool hideGlyphInHeader;
@property (weak, nonatomic) id <CCUIMenuItemsUpdating> menuUpdatingDelegate;
@property (readonly, nonatomic) _Bool prefersContextMenuDisplayStyle;
@property (nonatomic) _Bool alwaysExpanded;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy, nonatomic) NSString *menuDisplayName;
@property (readonly, nonatomic) UIMenu *contextMenu;

/* class methods */
+ (id)checkmarkImageForPreferredContentSizeCategory:(id)category;

/* instance methods */
- (void)_handlePressGesture:(id)gesture;
- (void)willTransitionToExpandedContentMode:(_Bool)mode;
- (double)preferredExpandedContentHeight;
- (void)removeAllActions;
- (id)leadingImageForMenuItem:(id)item;
- (double)preferredExpandedContentWidth;
- (void)didTransitionToExpandedContentMode:(_Bool)mode;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewWillLayoutSubviews;
- (void)viewDidMoveToWindow:(id)window shouldAppearOrDisappear:(_Bool)disappear;
- (void)_updatePreferredContentSize;
- (void)contentModuleWillTransitionToExpandedContentMode:(_Bool)mode;
- (id)_titleFont;
- (void)_contentSizeCategoryDidChange;
- (_Bool)shouldPerformClickInteraction;
- (_Bool)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)recognizer;
- (_Bool)_canShowWhileLocked;
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (void)setGlyphPackageDescription:(id)description;
- (void)setCustomContentView:(id)view;
- (double)_separatorHeight;
- (_Bool)shouldBeginTransitionToExpandedContentModule;
- (id)contextMenuItems;
- (_Bool)isBusy;
- (id)viewForTouchContinuation;
- (void)viewDidDisappear:(_Bool)disappear;
- (id)initWithContentModuleContext:(id)context;
- (void)setTitle:(id)title;
- (void)setGlyphImage:(id)image;
- (void)_updateTitleFont;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })size withTransitionCoordinator:(id)coordinator;
- (id)_subtitleFont;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)setMenuItems:(id)items;
- (void)_setupTitleLabel;
- (void)_setupSubtitleLabel;
- (_Bool)_shouldLimitContentSizeCategory;
- (void)_setTransformViewClipsToBounds:(_Bool)bounds;
- (double)_aggregateModuleHeight;
- (id)_busyIndicatorView;
- (double)_contentScaleForSize:(struct CGSize { double x0; double x1; })size;
- (double)_defaultMenuItemHeight;
- (double)_desiredExpandedHeight;
- (void)_fadeViewsForExpandedState:(_Bool)state;
- (double)_footerHeight;
- (_Bool)_forceLimitContentSizeCategoryFromContentHeightIfNecessary:(double)necessary expanded:(_Bool)expanded;
- (void)_handleActionTapped:(id)tapped;
- (void)_layoutBusyIndicatorForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutContentViewForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutFooterButtonForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutFooterSeparatorForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutGlyphViewForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutHeaderSeparatorForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutSubtitleLabelForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutTitleLabelForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutTransformViewForSize:(struct CGSize { double x0; double x1; })size;
- (void)_layoutViewSubviews;
- (id)_leadingViewForMenuItem:(id)item;
- (double)_maximumHeight;
- (id)_menuItemFromPlaceholderIndex:(unsigned long long)index;
- (double)_menuItemsHeightForWidth:(double)width;
- (id)_preferredFontForTextStyle:(id)style hiFontStyle:(long long)style;
- (_Bool)_setForceLimitContentSizeCategory:(_Bool)category;
- (void)_setMenuItems:(id)items;
- (void)_setRootViewClipsToBounds:(_Bool)bounds;
- (void)_setView:(id)view clipsToBounds:(_Bool)bounds;
- (_Bool)_shouldHideGlyphForLimitedContentSizeCategory;
- (_Bool)_shouldShowFooterChin;
- (_Bool)_shouldShowFooterSeparator;
- (double)_titleWidthForContainerWidth:(double)width;
- (_Bool)_toggleSelectionForMenuItem:(id)item;
- (id)_trailingViewForMenuItem:(id)item;
- (void)_updateLeadingAndTrailingViews;
- (void)_updateMenuItemsSeparatorVisiblity;
- (void)_updateSubtitleFont;
- (void)addActionWithTitle:(id)title glyph:(id)glyph handler:(id /* block */)handler;
- (void)addActionWithTitle:(id)title subtitle:(id)subtitle glyph:(id)glyph handler:(id /* block */)handler;
- (id)contextMenuPreviewForControlTemplateView:(id)view;
- (_Bool)hasGlyph;
- (double)headerHeightForWidth:(double)width;
- (_Bool)isAlwaysExpanded;
- (id)leadingViewForMenuItem:(id)item;
- (id)menuItemForIdentifier:(id)identifier;
- (id)mostRecentMenuItems;
- (double)preferredExpandedContentHeightWithWidth:(double)width;
- (void)removeFooterButton;
- (void)scrollToTop:(_Bool)top;
- (double)scrollViewContentHeightForWidth:(double)width;
- (void)setFooterButtonTitle:(id)title handler:(id /* block */)handler;
- (void)setUseIndentedLayout:(_Bool)layout;
- (id)trailingImageForMenuItem:(id)item;
- (id)trailingViewForMenuItem:(id)item;

@end

#endif /* CCUIMenuModuleViewController_h */
