//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1450.600.61.2.7
//
#ifndef _TtC14IMDPersistence13MessageRecord_h
#define _TtC14IMDPersistence13MessageRecord_h
@import Foundation;

@class IMDPersistence.MessageRecord._SwiftDataNoType, IMDPersistence.MessageRecord._SwiftDataNoType ?, _$sl9SwiftData07BackingB0_px5ModelAaBPRts_XP IMDPersistence.MessageRecord _$sXj, _TtCs12_SwiftObject;

@interface _TtC14IMDPersistence13MessageRecord : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    IMDPersistence.MessageRecord._SwiftDataNoType _guid;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _text;
    IMDPersistence.MessageRecord._SwiftDataNoType _replaceID;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _serviceCenter;
    IMDPersistence.MessageRecord._SwiftDataNoType _handleID;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _subject;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _country;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _attributedBody;
    IMDPersistence.MessageRecord._SwiftDataNoType _version;
    IMDPersistence.MessageRecord._SwiftDataNoType _type;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _service;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _account;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _accountGUID;
    IMDPersistence.MessageRecord._SwiftDataNoType _error;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _date;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _dateRead;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _dateDelivered;
    IMDPersistence.MessageRecord._SwiftDataNoType _isDelivered;
    IMDPersistence.MessageRecord._SwiftDataNoType _isFinished;
    IMDPersistence.MessageRecord._SwiftDataNoType _isEmote;
    IMDPersistence.MessageRecord._SwiftDataNoType _isFromMe;
    IMDPersistence.MessageRecord._SwiftDataNoType _isEmpty;
    IMDPersistence.MessageRecord._SwiftDataNoType _isDelayed;
    IMDPersistence.MessageRecord._SwiftDataNoType _isAutoReply;
    IMDPersistence.MessageRecord._SwiftDataNoType _isPrepared;
    IMDPersistence.MessageRecord._SwiftDataNoType _isRead;
    IMDPersistence.MessageRecord._SwiftDataNoType _isSystemMessage;
    IMDPersistence.MessageRecord._SwiftDataNoType _isSent;
    IMDPersistence.MessageRecord._SwiftDataNoType _hasDDResults;
    IMDPersistence.MessageRecord._SwiftDataNoType _isServiceMessage;
    IMDPersistence.MessageRecord._SwiftDataNoType _isForward;
    IMDPersistence.MessageRecord._SwiftDataNoType _wasDowngraded;
    IMDPersistence.MessageRecord._SwiftDataNoType _isArchive;
    IMDPersistence.MessageRecord._SwiftDataNoType _cacheHasAttachments;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _cacheRoomnames;
    IMDPersistence.MessageRecord._SwiftDataNoType _wasDataDetected;
    IMDPersistence.MessageRecord._SwiftDataNoType _wasDeduplicated;
    IMDPersistence.MessageRecord._SwiftDataNoType _isAudioMessage;
    IMDPersistence.MessageRecord._SwiftDataNoType _isPlayed;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _datePlayed;
    IMDPersistence.MessageRecord._SwiftDataNoType _itemType;
    IMDPersistence.MessageRecord._SwiftDataNoType _otherHandle;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _groupTitle;
    IMDPersistence.MessageRecord._SwiftDataNoType _groupActionType;
    IMDPersistence.MessageRecord._SwiftDataNoType _shareStatus;
    IMDPersistence.MessageRecord._SwiftDataNoType _shareDirection;
    IMDPersistence.MessageRecord._SwiftDataNoType _isExpirable;
    IMDPersistence.MessageRecord._SwiftDataNoType _expireState;
    IMDPersistence.MessageRecord._SwiftDataNoType _messageActionType;
    IMDPersistence.MessageRecord._SwiftDataNoType _messageSource;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _associatedMessageGUID;
    IMDPersistence.MessageRecord._SwiftDataNoType _associatedMessageType;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _balloonBundleID;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _payloadData;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _expressiveSendStyleID;
    IMDPersistence.MessageRecord._SwiftDataNoType _associatedMessageRangeLocation;
    IMDPersistence.MessageRecord._SwiftDataNoType _associatedMessageRangeLength;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _timeExpressiveSendPlayed;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _messageSummaryInfo;
    IMDPersistence.MessageRecord._SwiftDataNoType _ckSyncState;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _ckRecordID;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _ckRecordChangeTag;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _destinationCallerID;
    IMDPersistence.MessageRecord._SwiftDataNoType _isCorrupt;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _replyToGUID;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _sortID;
    IMDPersistence.MessageRecord._SwiftDataNoType _isSpam;
    IMDPersistence.MessageRecord._SwiftDataNoType _hasUnseenMention;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _threadOriginatorGUID;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _threadOriginatorPart;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _syndicationRanges;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _syncedSyndicationRanges;
    IMDPersistence.MessageRecord._SwiftDataNoType _wasDeliveredQuietly;
    IMDPersistence.MessageRecord._SwiftDataNoType _didNotifyRecipient;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _dateRetracted;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _dateEdited;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _dateRecovered;
    IMDPersistence.MessageRecord._SwiftDataNoType _wasDetonated;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _partCount;
    IMDPersistence.MessageRecord._SwiftDataNoType _isStewie;
    IMDPersistence.MessageRecord._SwiftDataNoType _isSOS;
    IMDPersistence.MessageRecord._SwiftDataNoType _isCritical;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _biaReferenceID;
    IMDPersistence.MessageRecord._SwiftDataNoType _isKTVerified;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _fallbackHash;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _associatedMessageEmoji;
    IMDPersistence.MessageRecord._SwiftDataNoType _isPendingSatelliteSend;
    IMDPersistence.MessageRecord._SwiftDataNoType _needsRelay;
    IMDPersistence.MessageRecord._SwiftDataNoType _scheduleType;
    IMDPersistence.MessageRecord._SwiftDataNoType _scheduleState;
    IMDPersistence.MessageRecord._SwiftDataNoType _sentOrReceivedOffGrid;
    IMDPersistence.MessageRecord._SwiftDataNoType _isTimeSensitive;
    IMDPersistence.MessageRecord._SwiftDataNoType ? _cloudKitChatID;
    IMDPersistence.MessageRecord._SwiftDataNoType _indexState;
    _$sl9SwiftData07BackingB0_px5ModelAaBPRts_XP IMDPersistence.MessageRecord _$sXj _$backingData;
    bycopy unsigned int _$observationRegistrar:0;
}

@end

#endif /* _TtC14IMDPersistence13MessageRecord_h */
