//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 820.5.18.0.0
//
#ifndef _TtC12GameCenterUI23CircularProgressBarView_h
#define _TtC12GameCenterUI23CircularProgressBarView_h
@import Foundation;

@class CoreGraphics.CGFloat, UIView, _$sSd, _$sSo12CAShapeLayerC;

@interface _TtC12GameCenterUI23CircularProgressBarView : UIView { // (Swift)
    /* instance variables */
    _$sSo12CAShapeLayerC circleLayer;
    _$sSo12CAShapeLayerC progressLayer;
    CoreGraphics.CGFloat startPoint;
    CoreGraphics.CGFloat endPoint;
    _$sSd progressPercentage;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;

@end

#endif /* _TtC12GameCenterUI23CircularProgressBarView_h */
