//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 556.5.31.0.0
//
#ifndef _TtC12APFoundation16WorkOrderBuilder_h
#define _TtC12APFoundation16WorkOrderBuilder_h
@import Foundation;

@class Foundation.Date ?, PFoundation.WorkOrderFlags, PFoundation.WorkState, _$sSSSg, _TtCs12_SwiftObject;

@interface _TtC12APFoundation16WorkOrderBuilder : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSSSg dataId;
    _Atomic PFoundation.WorkOrderFlags flags;
    Foundation.Date ? scheduledTime;
    _Atomic PFoundation.WorkState state;
    _$sSSSg requestorId;
    _$sSSSg requestorData;
    Foundation.Date ? created;
    _$sSSSg retryState;
}

@end

#endif /* _TtC12APFoundation16WorkOrderBuilder_h */
