//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1037.120.10.0.0
//
#ifndef SKWaitingForDiskElement_h
#define SKWaitingForDiskElement_h
@import Foundation;

@interface SKWaitingForDiskElement : NSObject

@property (retain) NSDictionary *diskDictionary;
@property (copy) id /* block */ block;

/* instance methods */

@end

#endif /* SKWaitingForDiskElement_h */
