//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4018.120.24.0.0
//
#ifndef _TtC18FileProviderDaemon20InternalPathsManager_h
#define _TtC18FileProviderDaemon20InternalPathsManager_h
@import Foundation;

@class FileProviderDaemon.TelemetrySession ?, Foundation.URL ?, _$sSSSg, _$sSo19FPDExtensionManagerCSg, _$sSo9FPDVolumeCSg, __C.FPProviderDomainID;

@interface _TtC18FileProviderDaemon20InternalPathsManager : NSObject { // (Swift)
    /* instance variables */
    __C.FPProviderDomainID providerDomainID;
    _$sSSSg personaIdentifier;
    _$sSo19FPDExtensionManagerCSg extensionManager;
    _$sSo9FPDVolumeCSg volume;
    FileProviderDaemon.TelemetrySession ? telemetrySession;
    Foundation.URL ? appSupportURL;
    Foundation.URL ? wharfDirectoryURL;
    Foundation.URL ? dbDirectoryURL;
    Foundation.URL ? dbURL;
    Foundation.URL ? temporaryDirectoryURL;
    Foundation.URL ? stateDirectoryURL;
    Foundation.URL ? diagnosticsDirectoryURL;
}

/* class methods */
+ (id)purgatoryPrefix;
+ (_Bool)_test_removeUnOwnedDirectoryAt:(id)at volume:(id)volume error:(id *)error;

/* instance methods */
- (id)init;
- (id)initWithProviderDomainID:(id)id;

@end

#endif /* _TtC18FileProviderDaemon20InternalPathsManager_h */
