//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 98.100.21.0.0
//
#ifndef _TtC21ImmersiveMediaSupport21AVCStreamSynchronizer_h
#define _TtC21ImmersiveMediaSupport21AVCStreamSynchronizer_h
@import Foundation;

@class Swift.Bool, _TtCs12_SwiftObject, __C.CMTime;

@interface _TtC21ImmersiveMediaSupport21AVCStreamSynchronizer : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    Swift.Bool enableLogs;
    __C.CMTime hostTimeT0;
    __C.CMTime firstVideoFrame;
    __C.CMTime firstAudioFrame;
    __C.CMTime lastVideoFrame;
    __C.CMTime lastAudioFrame;
}

@end

#endif /* _TtC21ImmersiveMediaSupport21AVCStreamSynchronizer_h */
