//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 98.100.21.0.0
//
#ifndef IMSComfortPipelineSupportConfig_h
#define IMSComfortPipelineSupportConfig_h
@import Foundation;

@protocol IMSComfortPipelineInputProvider;

@interface IMSComfortPipelineSupportConfig : NSObject

@property (weak) id <IMSComfortPipelineInputProvider> inputProvider;
@property int pipelineFrameRate;
@property int cropFrameWidth;
@property int cropFrameHeight;
@property float cropFOVVerticalDegree;

/* instance methods */
- (_Bool)validate;

@end

#endif /* IMSComfortPipelineSupportConfig_h */
