//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 373.2.0.0.0
//
#ifndef _MTL4ComputeCommandEncoder_h
#define _MTL4ComputeCommandEncoder_h
@import Foundation;

#include "MTL4CommandAllocator-Protocol.h"
#include "MTL4CommandBuffer-Protocol.h"
#include "MTL4ComputeCommandEncoderGGDSPI-Protocol.h"
#include "_MTL4CommandEncoder.h"

@interface _MTL4ComputeCommandEncoder : _MTL4CommandEncoder <MTL4ComputeCommandEncoderGGDSPI>

@property (copy) NSString *label;
@property (readonly, nonatomic) id <MTL4CommandBuffer> commandBuffer;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) id <MTL4CommandAllocator> commandAllocator;

/* instance methods */
- (void)optimizeContentsForCPUAccess:(id)cpuaccess slice:(unsigned long long)slice level:(unsigned long long)level;
- (void)resetCommandsInBuffer:(id)buffer withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)executeCommandsInBuffer:(id)buffer withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)fillTexture:(id)texture level:(unsigned long long)level slice:(unsigned long long)slice region:(struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; })region bytes:(const void *)bytes length:(unsigned long long)length;
- (void)copyFromTexture:(id)texture toTexture:(id)texture;
- (void)optimizeContentsForCPUAccess:(id)cpuaccess;
- (void)fillTexture:(id)texture level:(unsigned long long)level slice:(unsigned long long)slice region:(struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; })region color:(struct { double x0; double x1; double x2; double x3; })color;
- (void)setComputePipelineState:(id)state;
- (void)copyIndirectCommandBuffer:(id)buffer sourceRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range destination:(id)destination destinationIndex:(unsigned long long)index;
- (void)optimizeContentsForGPUAccess:(id)gpuaccess slice:(unsigned long long)slice level:(unsigned long long)level;
- (void)copyFromTexture:(id)texture sourceSlice:(unsigned long long)slice sourceLevel:(unsigned long long)level toTexture:(id)texture destinationSlice:(unsigned long long)slice destinationLevel:(unsigned long long)level sliceCount:(unsigned long long)count levelCount:(unsigned long long)count;
- (void)fillTexture:(id)texture level:(unsigned long long)level slice:(unsigned long long)slice region:(struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; })region color:(struct { double x0; double x1; double x2; double x3; })color pixelFormat:(unsigned long long)format;
- (void)dispatchThreadgroups:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroups threadsPerThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)fillBuffer:(id)buffer range:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range pattern4:(unsigned int)pattern4;
- (void)dispatchThreads:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threads threadsPerThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)optimizeIndirectCommandBuffer:(id)buffer withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)optimizeContentsForGPUAccess:(id)gpuaccess;
- (void)copyFromBuffer:(id)buffer sourceOffset:(unsigned long long)offset toBuffer:(id)buffer destinationOffset:(unsigned long long)offset size:(unsigned long long)size;
- (void)copyFromTexture:(id)texture sourceSlice:(unsigned long long)slice sourceLevel:(unsigned long long)level sourceOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toTexture:(id)texture destinationSlice:(unsigned long long)slice destinationLevel:(unsigned long long)level destinationOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin;
- (void)generateMipmapsForTexture:(id)texture;
- (void)setImageblockWidth:(unsigned long long)width height:(unsigned long long)height;
- (void)setThreadgroupMemoryLength:(unsigned long long)length atIndex:(unsigned long long)index;
- (unsigned long long)stages;
- (void)encodeStartElse;
- (void)setThreadgroupDistributionMode:(long long)mode;
- (void)signalProgress:(unsigned int)progress;
- (void)beginVirtualSubstream;
- (void)buildAccelerationStructure:(id)structure descriptor:(id)descriptor scratchBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)copyAccelerationStructure:(id)structure toAccelerationStructure:(id)structure;
- (void)copyAndCompactAccelerationStructure:(id)structure toAccelerationStructure:(id)structure;
- (void)copyFromBuffer:(id)buffer sourceOffset:(unsigned long long)offset sourceBytesPerRow:(unsigned long long)row sourceBytesPerImage:(unsigned long long)image sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toTexture:(id)texture destinationSlice:(unsigned long long)slice destinationLevel:(unsigned long long)level destinationOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin;
- (void)copyFromBuffer:(id)buffer sourceOffset:(unsigned long long)offset sourceBytesPerRow:(unsigned long long)row sourceBytesPerImage:(unsigned long long)image sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toTexture:(id)texture destinationSlice:(unsigned long long)slice destinationLevel:(unsigned long long)level destinationOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin options:(unsigned long long)options;
- (void)copyFromTensor:(id)tensor sourceOrigin:(id)origin sourceDimensions:(id)dimensions toTensor:(id)tensor destinationOrigin:(id)origin destinationDimensions:(id)dimensions;
- (void)copyFromTensor:(id)tensor sourceSlice:(struct MTLTensorSlice { id x0; id x1; })slice toTensor:(id)tensor destinationSlice:(struct MTLTensorSlice { id x0; id x1; })slice;
- (void)copyFromTexture:(id)texture sourceSlice:(unsigned long long)slice sourceLevel:(unsigned long long)level sourceOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toBuffer:(id)buffer destinationOffset:(unsigned long long)offset destinationBytesPerRow:(unsigned long long)row destinationBytesPerImage:(unsigned long long)image;
- (void)copyFromTexture:(id)texture sourceSlice:(unsigned long long)slice sourceLevel:(unsigned long long)level sourceOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toBuffer:(id)buffer destinationOffset:(unsigned long long)offset destinationBytesPerRow:(unsigned long long)row destinationBytesPerImage:(unsigned long long)image options:(unsigned long long)options;
- (void)deserializeInstanceAccelerationStructure:(id)structure referencedAccelerationStructures:(id)structures fromBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)deserializePrimitiveAccelerationStructure:(id)structure fromBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)dispatchThreadgroupsWithIndirectBuffer:(unsigned long long)buffer threadsPerThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)dispatchThreadsWithIndirectBuffer:(unsigned long long)buffer;
- (void)enableNullBufferBinds:(_Bool)binds;
- (_Bool)encodeEndDoWhile:(unsigned long long)_while comparison:(unsigned long long)comparison referenceValue:(unsigned int)value;
- (_Bool)encodeEndIf;
- (_Bool)encodeEndWhile;
- (void)encodeStartDoWhile;
- (void)encodeStartIf:(unsigned long long)_if comparison:(unsigned long long)comparison referenceValue:(unsigned int)value;
- (void)encodeStartWhile:(unsigned long long)_while comparison:(unsigned long long)comparison referenceValue:(unsigned int)value;
- (void)endVirtualSubstream;
- (void)executeCommandsInBuffer:(id)buffer indirectBuffer:(unsigned long long)buffer;
- (void)fillBuffer:(id)buffer range:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range value:(unsigned char)value;
- (id)initWithCommandAllocator:(id)allocator;
- (void)insertCompressedTextureReinterpretationFlush;
- (void)invalidateCompressedTexture:(id)texture;
- (void)invalidateCompressedTexture:(id)texture slice:(unsigned long long)slice level:(unsigned long long)level;
- (unsigned long long)nextVirtualSubstream;
- (void)refitAccelerationStructure:(id)structure descriptor:(id)descriptor destination:(id)destination scratchBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)refitAccelerationStructure:(id)structure descriptor:(id)descriptor destination:(id)destination scratchBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer options:(unsigned long long)options;
- (void)serializeInstanceAccelerationStructure:(id)structure referencedAccelerationStructures:(id)structures toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)serializePrimitiveAccelerationStructure:(id)structure toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)setArgumentTable:(id)table;
- (void)setSubstream:(unsigned int)substream;
- (void)setThreadgroupDistributionModeWithClusterGroupIndex:(unsigned int)index;
- (void)setToolsDispatchBufferSPI:(unsigned long long)spi atIndex:(unsigned long long)index;
- (void)waitForProgress:(unsigned int)progress;
- (void)waitForVirtualSubstream:(unsigned long long)substream;
- (void)writeAccelerationStructureSerializationData:(id)data toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)writeAccelerationStructureTraversalDepth:(id)depth toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)writeCompactedAccelerationStructureSize:(id)size toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)writeDeserializedAccelerationStructureSize:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })size toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (_Bool)writeGenericBVHStructureOfAccelerationStructure:(id)structure into:(id)into;
- (_Bool)writeGenericBVHStructureSizesOfAccelerationStructure:(id)structure into:(id)into;
- (void)writeGenericBVHStructureSizesOfAccelerationStructure:(id)structure toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)writeSerializedAccelerationStructureSize:(id)size toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)writeTimestampWithGranularity:(long long)granularity intoHeap:(id)heap atIndex:(unsigned long long)index;

@end

#endif /* _MTL4ComputeCommandEncoder_h */
