//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 252.5.1.0.0
//
#ifndef STStatusDomainDataChangeRecordDataEntry_h
#define STStatusDomainDataChangeRecordDataEntry_h
@import Foundation;

#include "BSDebugDescriptionProviding-Protocol.h"
#include "STStatusDomainData-Protocol.h"
#include "STStatusDomainDataChangeRecordEntry-Protocol.h"
#include "STStatusDomainDataDiff-Protocol.h"
#include "STStatusDomainDataDifferencing-Protocol.h"

@interface STStatusDomainDataChangeRecordDataEntry : NSObject <STStatusDomainDataChangeRecordEntry, NSSecureCoding, BSDebugDescriptionProviding>

@property (readonly, nonatomic) id <STStatusDomainData, STStatusDomainDataDifferencing> data;
@property (readonly, nonatomic) id clientKey;
@property (readonly, nonatomic) unsigned long long entryType;
@property (readonly, nonatomic) id <STStatusDomainDataDiff> diff;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithData:(id)data clientKey:(id)key;
- (id)succinctDescriptionBuilder;
- (id)debugDescriptionWithMultilinePrefix:(id)prefix;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)initWithCoder:(id)coder;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;

@end

#endif /* STStatusDomainDataChangeRecordDataEntry_h */
