//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 252.5.1.0.0
//
#ifndef STStewieStatusDomainData_h
#define STStewieStatusDomainData_h
@import Foundation;

#include "BSDebugDescriptionProviding-Protocol.h"
#include "STStatusDomainData-Protocol.h"
#include "STStatusDomainDataDifferencing-Protocol.h"

@interface STStewieStatusDomainData : NSObject <BSDebugDescriptionProviding, STStatusDomainDataDifferencing, NSSecureCoding, STStatusDomainData>

@property (readonly, nonatomic) _Bool stewieActive;
@property (readonly, nonatomic) _Bool stewieConnected;
@property (readonly, nonatomic) unsigned long long stewieSignalStrengthBars;
@property (readonly, nonatomic) unsigned long long maxStewieSignalStrengthBars;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)diffFromData:(id)data;
- (_Bool)isStewieActive;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)succinctDescriptionBuilder;
- (id)debugDescriptionWithMultilinePrefix:(id)prefix;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)dataByApplyingDiff:(id)diff;
- (id)initWithCoder:(id)coder;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;
- (_Bool)isStewieConnected;

@end

#endif /* STStewieStatusDomainData_h */
