//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 5883.0.0.0.0
//
#ifndef _TtC7NewsUI223PushNotificationService_h
#define _TtC7NewsUI223PushNotificationService_h
@import Foundation;

@class _$sSo24FCNotificationControllerC, _TtCs12_SwiftObject;

@interface _TtC7NewsUI223PushNotificationService : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSo24FCNotificationControllerC notificationController;
    union objc_protocol 0x21e08c290 configurationManager;
}

@end

#endif /* _TtC7NewsUI223PushNotificationService_h */
