//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 5883.0.0.0.0
//
#ifndef _TtC7NewsUI218TagFeedAsyncModule_h
#define _TtC7NewsUI218TagFeedAsyncModule_h
@import Foundation;

@class TeaFoundation.ResolverType, _TtCs12_SwiftObject, ewsFeed.OfflineManager NewsUI2.TagFeedOfflineModel, ewsUI2.TagFeedAsyncViewControllerFactory;

@interface _TtC7NewsUI218TagFeedAsyncModule : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    TeaFoundation.ResolverType resolver;
    inout ewsUI2.TagFeedAsyncViewControllerFactory viewControllerFactory;
    inout ewsFeed.OfflineManager NewsUI2.TagFeedOfflineModel offlineManager;
}

@end

#endif /* _TtC7NewsUI218TagFeedAsyncModule_h */
