//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1704.0.100.0.0
//
#ifndef OKActionEdgePan_h
#define OKActionEdgePan_h
@import Foundation;

#include "OKActionEdgePanExports-Protocol.h"
#include "OKActionPan.h"

@interface OKActionEdgePan : OKActionPan <OKActionEdgePanExports, NSSecureCoding>

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)edgePanActionWithState:(unsigned long long)state location:(struct CGPoint { double x0; double x1; })location touchCount:(unsigned long long)count translation:(struct CGPoint { double x0; double x1; })translation previousTranslation:(struct CGPoint { double x0; double x1; })translation velocity:(struct CGPoint { double x0; double x1; })velocity previousVelocity:(struct CGPoint { double x0; double x1; })velocity direction:(unsigned long long)direction context:(id)context;
+ (void)setupJavascriptContext:(id)context;

/* instance methods */
- (void)dealloc;
- (id)initWithCoder:(id)coder;
- (id)init;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* OKActionEdgePan_h */
