//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1704.0.100.0.0
//
#ifndef OKMediaItemMetadata_h
#define OKMediaItemMetadata_h
@import Foundation;

@class CLLocation;

@interface OKMediaItemMetadata : NSObject

@property unsigned long long type;
@property unsigned long long subType;
@property struct CGSize { double x0; double x1; } resolution;
@property (retain) NSDate *creationDate;
@property unsigned long long orientation;
@property double duration;
@property double displayTime;
@property double latitude;
@property double longitude;
@property _Bool opaque;
@property (copy) NSString *UTI;
@property (copy) NSString *name;
@property (copy) NSString *caption;
@property _Bool regionsOfInterestDetected;
@property (copy) NSArray *regionsOfInterest;
@property struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } regionOfInterestContainerBounds;
@property (readonly) double aspectRatio;
@property (readonly) CLLocation *location;
@property (readonly) struct CLLocationCoordinate2D { double x0; double x1; } locationCoordinate;
@property (readonly) _Bool hasRegionsOfInterest;
@property (readonly) _Bool hasRegionsOfInterestName;
@property (readonly) NSArray *regionsOfInterestName;

/* class methods */
+ (unsigned long long)alignResolution:(unsigned long long)resolution;
+ (id)keyPathsForValuesAffectingAspectRatio;
+ (id)keyPathsForValuesAffectingHasRegionsOfInterest;
+ (id)keyPathsForValuesAffectingHasRegionsOfInterestName;
+ (id)keyPathsForValuesAffectingLocation;
+ (id)keyPathsForValuesAffectingLocationCoordinate;
+ (id)keyPathsForValuesAffectingRegionsOfInterestName;

/* instance methods */
- (id)initWithFileURL:(id)url;
- (void)invalidate;
- (void)dealloc;
- (id)init;
- (id)initWithDictionary:(id)dictionary;
- (id)dictionary;
- (_Bool)isMediaSubtype:(unsigned long long)subtype;
- (id)dictionaryValueForKey:(id)key;
- (_Bool)writeToFileURL:(id)url;
- (unsigned long long)bestResolutionForSize:(struct CGSize { double x0; double x1; })size scale:(double)scale quality:(double)quality;
- (id)regionsOfInterestDictionary;
- (void)setPropertiesFromDictionary:(id)dictionary;

@end

#endif /* OKMediaItemMetadata_h */
