//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 416.575.9.0.0
//
#ifndef CDPWalrusStatusProvider_Protocol_h
#define CDPWalrusStatusProvider_Protocol_h
@import Foundation;

@protocol CDPWalrusStatusProvider <NSObject>

@required

/* required instance methods */
- (void)repairWalrusStatusWithCompletion:(id /* block */)completion;
- (unsigned long long)walrusStatus:(id *)status;
- (void)walrusStatusWithCompletion:(id /* block */)completion;
- (void)combinedWalrusStatusWithCompletion:(id /* block */)completion;
- (id)combinedWalrusStatus:(id *)status;

@optional

@end

#endif /* CDPWalrusStatusProvider_Protocol_h */
