//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 25610.26.16.301.0
//
#ifndef _TtC18_SonicKit_MusicKit18MusicLiveLinkQueue_h
#define _TtC18_SonicKit_MusicKit18MusicLiveLinkQueue_h
@import Foundation;

@class _$sSo10ICLiveLinkCSg, _TtCs12_SwiftObject;

@interface _TtC18_SonicKit_MusicKit18MusicLiveLinkQueue : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSo10ICLiveLinkCSg liveLink;
}

@end

#endif /* _TtC18_SonicKit_MusicKit18MusicLiveLinkQueue_h */
