//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 496.22.0.0.0
//
#ifndef AXSDVoiceTriggerAssetManager_h
#define AXSDVoiceTriggerAssetManager_h
@import Foundation;

#include "AXAssetControllerObserver-Protocol.h"
#include "AXSDVoiceTriggerAssetManagerDelegate-Protocol.h"

@class AXAsset, AXAssetController, AXVoiceTriggerAssetPolicy;

@interface AXSDVoiceTriggerAssetManager : NSObject <AXAssetControllerObserver>

@property (retain, nonatomic) AXAssetController *assetController;
@property (retain, nonatomic) AXVoiceTriggerAssetPolicy *assetPolicy;
@property (retain, nonatomic) AXAsset *latestDownloadedAsset;
@property (weak, nonatomic) id <AXSDVoiceTriggerAssetManagerDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDelegate:(id)delegate;
- (void)assetController:(id)controller didFinishDownloadingAsset:(id)asset wasSuccessful:(_Bool)successful error:(id)error hasRemainingDownloads:(_Bool)downloads;
- (void)assetController:(id)controller didFinishRefreshingAssets:(id)assets wasSuccessful:(_Bool)successful error:(id)error;
- (void)assetDidUpdateWithError:(id)error;

@end

#endif /* AXSDVoiceTriggerAssetManager_h */
