//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 305.0.0.0.0
//
#ifndef _NCWidgetViewControllerView_h
#define _NCWidgetViewControllerView_h
@import Foundation;

#include "NCSizeObservingView.h"
#include "UIScrollViewDelayedTouchesBeganGestureRecognizerClient-Protocol.h"

@interface _NCWidgetViewControllerView : NCSizeObservingView <UIScrollViewDelayedTouchesBeganGestureRecognizerClient>

@property (readonly, nonatomic) _Bool delaysContentTouches;
@property (readonly, nonatomic) double touchDelayForScrollDetection;
@property (readonly, nonatomic) double scrollHysteresis;
@property (readonly, nonatomic) _Bool canScrollX;
@property (readonly, nonatomic) _Bool canScrollY;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)didMoveToWindow;
- (_Bool)_canScrollX;
- (_Bool)_canScrollY;
- (double)_scrollHysteresis;
- (double)_touchDelayForScrollDetection;
- (_Bool)touchesShouldBegin:(id)begin withEvent:(id)event inContentView:(id)view;

@end

#endif /* _NCWidgetViewControllerView_h */
