//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2026.5.2.0.0
//
#ifndef ACHActivitySummaryIterator_h
#define ACHActivitySummaryIterator_h
@import Foundation;

#include "_HKXPCExportable-Protocol.h"

@class HKHealthStore, HKTaskServerProxyProvider;

@interface ACHActivitySummaryIterator : NSObject <_HKXPCExportable>

@property (retain, nonatomic) HKHealthStore *healthStore;
@property (retain, nonatomic) NSCalendar *calendar;
@property (retain, nonatomic) HKTaskServerProxyProvider *proxyProvider;
@property (nonatomic) _Bool includePrivateProperties;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)remoteInterface;
- (id)initWithHealthStore:(id)store shouldIncludePrivateProperties:(_Bool)properties;
- (id)newEmptyActivitySummaryFromSummary:(id)summary;
- (id)exportedInterface;
- (void)enumerateActivitySummariesForDateComponentInterval:(id)interval handler:(id /* block */)handler errorHandler:(id /* block */)handler;
- (void)enumerateActivitySummariesForDateComponentInterval:(id)interval includeNilSummaries:(_Bool)summaries handler:(id /* block */)handler errorHandler:(id /* block */)handler;
- (void)_enumerateActivitySummariesIncludingEmptySummariesForDateComponentInterval:(id)interval handler:(id /* block */)handler errorHandler:(id /* block */)handler;
- (void)connectionInvalidated;

@end

#endif /* ACHActivitySummaryIterator_h */
