//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4610.0.0.0.0
//
#ifndef WFMessage_h
#define WFMessage_h
@import Foundation;

#include "WFNaming-Protocol.h"

@interface WFMessage : NSObject <NSCopying, NSSecureCoding, WFNaming>

@property (readonly, copy, nonatomic) NSString *content;
@property (readonly, copy, nonatomic) NSString *conversationID;
@property (readonly, copy, nonatomic) NSArray *recipientContactIDs;
@property (readonly, copy, nonatomic) NSArray *recipients;
@property (readonly, copy, nonatomic) NSString *senderContactID;
@property (readonly, copy, nonatomic) NSArray *senderHandles;
@property (readonly, copy, nonatomic) NSString *wfName;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)initWithContent:(id)content conversationID:(id)id recipientContactIDs:(id)ids recipients:(id)recipients senderContactID:(id)id senderHandles:(id)handles;

@end

#endif /* WFMessage_h */
