//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 26.4.5.0.0
//
#ifndef _TtC17CoreODIEssentials14ProfileManager_h
#define _TtC17CoreODIEssentials14ProfileManager_h
@import Foundation;

@class Builtin.DefaultActorStorage, CoreODIEssentials.AssessmentWebService, CoreODIEssentials.CoreODILogger, CoreODIEssentials.PersistenceCommand, CoreODIEssentials.ServerTimeSeedProvider, _$sSS, _$sScT -> CoreODIEssentials.EncapsulatingProfile _$s_p Swift.Error ?, _TtCs12_SwiftObject;

@interface _TtC17CoreODIEssentials14ProfileManager : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    Builtin.DefaultActorStorage $defaultActor;
    CoreODIEssentials.AssessmentWebService webService;
    _$sSS workflowID;
    CoreODIEssentials.PersistenceCommand persistenceCommand;
    CoreODIEssentials.ServerTimeSeedProvider stsProvider;
    CoreODIEssentials.CoreODILogger logger;
    _$sScT -> CoreODIEssentials.EncapsulatingProfile _$s_p Swift.Error ? inMemoryProfile;
}

@end

#endif /* _TtC17CoreODIEssentials14ProfileManager_h */
