//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 2952.120.8.0.0
//
#ifndef UITextDropDelegate_Private_Protocol_h
#define UITextDropDelegate_Private_Protocol_h
@import Foundation;

#include "UITextDropDelegate-Protocol.h"

@protocol UITextDropDelegate_Private <UITextDropDelegate>

@required

@optional

/* optional instance methods */
- (id)textDroppableView:(id)view rangeForDrop:(id)drop;
- (long long)_textDroppableView:(id)view dataOwnerForDrop:(id)drop;
- (void)textDroppableView:(id)view dropSession:(id)session didMoveCaretToRange:(id)range;
- (_Bool)textDroppableView:(id)view dropSession:(id)session willMoveCaretToRange:(id)range;
- (id)textDroppableView:(id)view positionForDrop:(id)drop;

@end

#endif /* UITextDropDelegate_Private_Protocol_h */
