//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 4097.122.2.0.0
//
#ifndef CEKTickMarksContainer_Protocol_h
#define CEKTickMarksContainer_Protocol_h
@import Foundation;

#include "CEKSliderTickMarksDelegate-Protocol.h"
#include "_TtC13CameraEditKit14TickMarksModel.h"

@protocol CEKTickMarksContainer

@required

@property (weak, nonatomic) id <CEKSliderTickMarksDelegate> delegate;
@property (readonly, nonatomic) _TtC13CameraEditKit14TickMarksModel *tickMarksModel;

/* required instance methods */
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameForTickMarkAtIndex:(unsigned long long)index;

@optional

@end

#endif /* CEKTickMarksContainer_Protocol_h */
