//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 665.120.8.0.0
//
#ifndef FigCameraViewfinderStream_h
#define FigCameraViewfinderStream_h
@import Foundation;

#include "FigCaptureFrameCounter.h"
#include "FigDelegateStorage.h"
#include "FigStateMachine.h"

@interface FigCameraViewfinderStream : NSObject {
    /* instance variables */
    FigDelegateStorage *_delegateStorage;
    FigStateMachine *_stateMachine;
    struct OpaqueFigEndpoint * _endpoint;
    struct OpaqueFigEndpointStream * _stream;
    struct OpaqueFigVirtualDisplaySource * _displaySource;
    FigCaptureFrameCounter *_frameCounter;
    id _endpointsChangedNotificationToken;
    id _streamsChangedNotificationToken;
}

/* class methods */
+ (void)initialize;

/* instance methods */
- (void)setDelegate:(id)delegate queue:(id)queue;
- (void)dealloc;
- (void)openWithDestination:(id)destination;
- (id)init;
- (int)enqueueVideoSampleBuffer:(struct opaqueCMSampleBuffer *)buffer;
- (void)close;

@end

#endif /* FigCameraViewfinderStream_h */
