//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.2.11.1
//
#ifndef _SFPBRFSimpleItemRichSearchResultCardSection_h
#define _SFPBRFSimpleItemRichSearchResultCardSection_h
@import Foundation;

#include "_SFPBRFSimpleItemRichSearchResultCardSection-Protocol.h"
#include "_SFPBRFTextProperty.h"
#include "_SFPBRFVisualProperty.h"

@class PBCodable;

@interface _SFPBRFSimpleItemRichSearchResultCardSection : PBCodable <_SFPBRFSimpleItemRichSearchResultCardSection, NSSecureCoding>

@property (retain, nonatomic) _SFPBRFTextProperty *text_1;
@property (retain, nonatomic) _SFPBRFTextProperty *text_2;
@property (copy, nonatomic) NSArray *text_3s;
@property (retain, nonatomic) _SFPBRFTextProperty *text_4;
@property (copy, nonatomic) NSArray *text_5s;
@property (retain, nonatomic) _SFPBRFTextProperty *text_6;
@property (retain, nonatomic) _SFPBRFTextProperty *text_7;
@property (retain, nonatomic) _SFPBRFTextProperty *text_8;
@property (retain, nonatomic) _SFPBRFVisualProperty *thumbnail;
@property (readonly, nonatomic) NSData *jsonData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (_Bool)readFrom:(id)from;
- (id)initWithFacade:(id)facade;
- (void)writeTo:(id)to;
- (id)initWithJSON:(id)json;
- (id)initWithDictionary:(id)dictionary;
- (id)dictionaryRepresentation;
- (_Bool)isEqual:(id)equal;
- (void)addText_3:(id)text_3;
- (void)addText_5:(id)text_5;
- (void)clearText_3;
- (void)clearText_5;
- (void)setText_3:(id)text_3;
- (void)setText_5:(id)text_5;
- (id)text_3AtIndex:(unsigned long long)index;
- (unsigned long long)text_3Count;
- (id)text_5AtIndex:(unsigned long long)index;
- (unsigned long long)text_5Count;

@end

#endif /* _SFPBRFSimpleItemRichSearchResultCardSection_h */
