//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 3525.4.2.11.1
//
#ifndef RFVisualPropertyWithAction_h
#define RFVisualPropertyWithAction_h
@import Foundation;

#include "RFVisualProperty.h"
#include "RFVisualPropertyWithAction-Protocol.h"
#include "SFCommandButtonItem.h"

@interface RFVisualPropertyWithAction : RFVisualProperty <RFVisualPropertyWithAction, NSSecureCoding, NSCopying>

@property (retain, nonatomic) SFCommandButtonItem *commandItem;
@property (readonly, nonatomic) NSDictionary *dictionaryRepresentation;
@property (readonly, nonatomic) NSData *jsonData;
@property (copy, nonatomic) NSArray *visual_elements;
@property (nonatomic) _Bool is_safe_for_logging;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (id)initWithProtobuf:(id)protobuf;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isEqual:(id)equal;

@end

#endif /* RFVisualPropertyWithAction_h */
