//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 1003.5.19.0.0
//
#ifndef NCCAPackageView_h
#define NCCAPackageView_h
@import Foundation;

@class CALayer, CAPackage, CAStateController, UIView;

@interface NCCAPackageView : UIView {
    /* instance variables */
    CAPackage *_package;
    CAStateController *_stateController;
    UIView *_packageContentView;
    CALayer *_packageLayer;
}

@property (nonatomic) double scale;

/* instance methods */
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)removeAllStateChanges;
- (void)setStateName:(id)name;
- (void)layoutSubviews;
- (void)_setupPackageNamed:(id)named inBundle:(id)bundle;
- (id)initWithPackageNamed:(id)named inBundle:(id)bundle;

@end

#endif /* NCCAPackageView_h */
