//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 11.5.10.0.0
//
#ifndef _TtC11AppStoreKit20NWPathNetworkInquiry_h
#define _TtC11AppStoreKit20NWPathNetworkInquiry_h
@import Foundation;

@class Combine.Published Swift.Bool, Foundation.NSKeyValueObservation ?, _$sSo15NWPathEvaluatorC, _TtCs12_SwiftObject;

@interface _TtC11AppStoreKit20NWPathNetworkInquiry : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSo15NWPathEvaluatorC evaluator;
    Foundation.NSKeyValueObservation ? pathObservation;
    Combine.Published Swift.Bool _isInternetOffline;
}

@end

#endif /* _TtC11AppStoreKit20NWPathNetworkInquiry_h */
