//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 191.80.1.0.0
//
#ifndef UIView_DC_h
#define UIView_DC_h
@import Foundation;

@interface UIView (DC)

/* class methods */
+ (void)dc_animateWithDuration:(double)duration timingFunction:(id)function animations:(id /* block */)animations;
+ (void)dc_animateWithDuration:(double)duration timingFunction:(id)function animations:(id /* block */)animations completion:(id /* block */)completion;

/* instance methods */
- (void)dc_addConstraintsToFillSuperview;
- (id)dc_animator;
- (void)dc_crashIfWindowIsSecure;
- (struct NSDirectionalEdgeInsets { double x0; double x1; double x2; double x3; })dc_directionalSafeAreaInsets;
- (id)dc_imageRenderedFromLayer;
- (id)dc_imageRenderedFromViewHierarchy;
- (id)dc_imageViewRenderedFromLayer;
- (id)dc_imageViewRenderedFromViewHierarchy;
- (_Bool)dc_isInSecureWindow;
- (_Bool)dc_isRTL;
- (void)dc_removeAllConstraintsForSubview:(id)subview;
- (id)dc_renderImage;
- (id)dc_renderImageView;

@end

#endif /* UIView_DC_h */
