//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 577.4.4.0.0
//
#ifndef PKOverlayDrawingController_h
#define PKOverlayDrawingController_h
@import Foundation;

#include "PKOverlayDrawingControllerDelegate-Protocol.h"

@class UIView;

@interface PKOverlayDrawingController : NSObject {
    /* instance variables */
    id <PKOverlayDrawingControllerDelegate> _delegate;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _currentViewFrame;
    double _currentWidthForCachedViews;
    NSMutableDictionary *_activeTokens;
    NSMutableDictionary *_drawingViews;
    NSMutableDictionary *_drawingViewStrokesMap;
    NSMutableDictionary *_drawingViewResultMap;
    UIView *_view;
}

/* instance methods */
- (void)_updateDrawingViews;

@end

#endif /* PKOverlayDrawingController_h */
